//! The binder's cheap gate, over the REAL corpus, riding the ordinary workspace suite.
//!
//! Placing it here rather than behind a mise task is what makes it run on both platform legs
//! for free, with no external toolchain: `cargo nextest run --workspace` is the gate, and
//! `301` §5 wants exactly these checks at that tier.

use dorc_verify::badge::{Badge, Evidence, Expectation};
use dorc_verify::catalogue_lock::LAWS;
use dorc_verify::evidence::{self, Tier};
use dorc_verify::{check, promote, repo_root, seat, unit};

#[test]
fn the_catalogue_and_the_corpus_agree() {
    let findings = check::run(repo_root()).expect("the corpus must be readable");
    assert!(
        findings.failures.is_empty(),
        "dorc-verify check found {} failure(s):\n  {}",
        findings.failures.len(),
        findings.failures.join("\n  ")
    );
}

#[test]
fn the_committed_lock_is_byte_identical_to_what_promote_generates() {
    // This is what turns the header's `@generated by dorc-verify promote` from a claim into a
    // fact. It holds both directions at once: the generator cannot silently reshape the file,
    // and a hand-edit that promote would not have produced stops being invisible — which
    // matters because a hand-edit is exactly how the lock's badge expectations could drift away
    // from the evidence that is supposed to write them.
    let root = repo_root();
    let units = unit::load_all(root).expect("the corpus must be readable");
    let claimed = promote::claims(&units, &LAWS, &promote::Inputs::default())
        .expect("every catalogued law has its seat");
    let rows = promote::finish(root, Tier::Cheap, &units, &claimed);
    let committed =
        std::fs::read_to_string(promote::path(root)).expect("the lock must be readable");
    assert_eq!(
        promote::render(&rows),
        committed,
        "the committed lock is not what `dorc-verify promote` writes — re-run the promote"
    );
}

#[test]
fn every_cited_seat_resolves_to_a_real_function() {
    // The citation is a checked confirmation, not new information — which is precisely why it
    // earns its keep: this is the assertion that goes red when a rename moves a chokepoint out
    // from under a law, in a directory the renamer never opened.
    for law in &LAWS {
        seat::resolve(law.seat, repo_root()).unwrap_or_else(|why| panic!("{}: {why}", law.slug));
    }
}

#[test]
fn a_citation_reaches_one_of_the_seven_join_declarations_and_refuses_a_wrong_owner() {
    // `analysis::lattice` declares `fn join` seven times. Against the REAL file, because the
    // property being pinned is about that file: each citation reaches its own owner's
    // declaration and no other, and an owner that does not have the function is a refusal
    // rather than a fallback to somebody else's.
    let root = repo_root();
    let trait_seat = seat::resolve("dorc_analysis::lattice::Lattice::join", root)
        .expect("the trait declares it");
    let flat_seat =
        seat::resolve("dorc_analysis::lattice::Flat::join", root).expect("so does the Flat impl");
    assert_ne!(
        trait_seat.line, flat_seat.line,
        "two citations landing on one line means neither is being resolved"
    );
    let refused = seat::resolve("dorc_analysis::lattice::Powerset::top", root)
        .expect_err("a bare powerset is unbounded — it has no `top`, and four other types do");
    assert!(refused.contains("none of them under"), "{refused}");
}

#[test]
fn the_cheap_tier_never_mints_an_external_engine_badge() {
    // The whole tier split rests on this. A cheap run that answered `earned` for a Lean or
    // Kani badge would be laundering a committed expectation into an evidence claim — the
    // exact stale-coverage lie the catalogue exists to catch, wearing the catalogue's clothes.
    let units = unit::load_all(repo_root()).expect("the corpus must be readable");
    for law in &LAWS {
        let found = evidence::compute(
            law,
            units.iter().find(|u| u.slug == law.slug),
            repo_root(),
            Tier::Cheap,
        );
        for (badge, verdict) in Badge::ALL.iter().zip(&found) {
            if badge.needs_external_engine() {
                assert_ne!(
                    *verdict,
                    Evidence::Earned,
                    "{} minted `{badge}` without running its engine",
                    law.slug
                );
            }
        }
    }
}

#[test]
fn an_unlooked_at_badge_cannot_contradict_and_a_looked_at_one_can() {
    // `NotAtThisTier` agreeing with everything is load-bearing and easy to misread as
    // permissiveness, so it is pinned beside the cases that DO refuse.
    assert!(Evidence::NotAtThisTier.agrees_with(Expectation::Earned));
    assert!(Evidence::NotAtThisTier.agrees_with(Expectation::Todo));
    assert!(Evidence::Earned.agrees_with(Expectation::Earned));
    assert!(Evidence::Absent("x".to_owned()).agrees_with(Expectation::Todo));
    assert!(Evidence::Absent("x".to_owned()).agrees_with(Expectation::Excepted("why")));

    // Both directions refuse: rot (promoted earned, evidence gone) and ambition (promoted
    // todo, evidence present).
    assert!(!Evidence::Absent("x".to_owned()).agrees_with(Expectation::Earned));
    assert!(!Evidence::Earned.agrees_with(Expectation::Todo));
    assert!(!Evidence::Earned.agrees_with(Expectation::Excepted("why")));
}
