-- generated by assay from spike/crates/internal-tooling/tests/assay_fixture/widgets.assay.md; edit the spec, not this file
-- the harness, `notes/30Y` § 2.2
module assay

sig Shword { class: set Class }
sig Class {}
abstract sig Claim {}
sig Line { above: set Line, speech: set Claim, cmd: one Shword, argv: seq Shword }
