-- generated by assay from spike/crates/internal-tooling/tests/assay_fixture/widgets.md; edit the spec, not this file
module book_corpus
open claims

-- assay: the corpus book, one null-command line with every claim atom in force
one sig line_1 extends Line {}
fact { line_1.cmd = assay_colon  no line_1.argv  no line_1.above }
fact { line_1.speech = alice__frob_wobbles + bob__spin_wobbles + bob__twirl_wobbles_on_the_sprocket_heap }

-- widgets.md:21
check everySpokenWobbleIsHeard { Wobble & Line.speech in Heard } for 4 but 3 Int, 3 seq, exactly 14 Shword, exactly 1 Class, exactly 1 Line, exactly 3 Claim

-- assay: the corpus book's inhabitation run
run book_corpus {} for 4 but 3 Int, 3 seq, exactly 14 Shword, exactly 1 Class, exactly 1 Line, exactly 3 Claim
