-- generated by assay from spike/crates/internal-tooling/tests/assay_fixture/widgets.md; edit the spec, not this file
module book_twirls
open claims

-- widgets.md:45
fact { some k: Knob | k.tag = knob_word }

-- widgets.md:39
one sig line_2, line_3 extends Line {}

-- widgets.md:49
one sig bob__this_spin_jiggles extends Jiggle {} { speaker = bob  at = line_2 }

-- widgets.md:47: spin /tmp/sprocket >>/tmp/spin.log 2>&1
fact { line_2.cmd = spin  line_2.argv = 0->sprocket_path + 1->append_spin_log + 2->stderr_to_stdout  no line_2.above }

-- widgets.md:52: twirl /tmp/sprocket
fact { line_3.cmd = twirl  line_3.argv = 0->sprocket_path  line_3.above = line_2 }

-- widgets.md:47
fact { line_2.speech = alice_kit + bob__twirl_wobbles_on_the_sprocket_heap + bob__this_spin_jiggles }

-- widgets.md:52
fact { line_3.speech = line_2.speech }

-- widgets.md:47
check line_2 { (some j: Jiggle & line_2.speech | j.at = line_2) } for 5 but 3 Int, 3 seq, exactly 11 Shword, exactly 1 Class, exactly 2 Line, exactly 4 Claim

-- widgets.md:52
check line_3 { (some j: Jiggle & line_2.speech | j.at = line_2) implies (line_3.argv[0] in gizmo.~class) } for 4 but 3 Int, 3 seq, exactly 11 Shword, exactly 1 Class, exactly 2 Line, exactly 4 Claim

-- widgets.md:39
run twirls { (some j: Jiggle & line_2.speech | j.at = line_2) and (line_3.argv[0] in gizmo.~class) } for 5 but 3 Int, 3 seq, exactly 11 Shword, exactly 1 Class, exactly 2 Line, exactly 4 Claim
