-- generated by assay from spike/crates/internal-tooling/tests/assay_fixture/widgets.md; edit the spec, not this file
module claims
open species
open words

-- widgets.md:27
one sig alice__frob_wobbles extends Wobble {} { speaker = alice  of = frob }

-- widgets.md:28
one sig bob__spin_wobbles extends Wobble {} { speaker = bob  of = spin }

-- widgets.md:29
one sig bob__twirl_wobbles_on_the_sprocket_heap extends Wobble {} { speaker = bob  of = sprocket_heap }

-- widgets.md:33
fun alice_kit: set Claim { alice__frob_wobbles + bob__spin_wobbles }
