-- generated by assay from spike/crates/internal-tooling/tests/assay_fixture/widgets.md; edit the spec, not this file
module laws
open species

-- widgets.md:18
check everyWobbleIsHeardWhenSpoken { all l: Line, w: Wobble & l.speech | w in Heard } for 3 but 2 Int

-- widgets.md:19
run everyWobbleIsHeardWhenSpoken_premise { some l: Line | some Wobble & l.speech } for 3 but 2 Int

-- shared-laws.assay.md:8
check wobblyNeedsAWobble { all l: Line | wobbly[l] implies some Wobble & l.speech } for 3 but 2 Int
