-- generated by assay from spike/crates/internal-tooling/tests/assay_fixture/widgets.assay.md; edit the spec, not this file
module shared
open assay

-- shared.assay.md:8
sig Speaker {}

-- shared.assay.md:9
abstract sig Blurb extends Claim { speaker: one Speaker }

-- shared.assay.md:10
sig Heard in Blurb {}

-- shared.assay.md:11
fact { all b: Blurb | b in Heard iff b in Line.speech }

-- shared.assay.md:12
fact { all l: Line | l not in l.^above }
