-- generated by assay from spike/crates/internal-tooling/tests/assay_fixture/widgets.md; edit the spec, not this file
module species
open assay
open shared

-- widgets.md:6
one sig alice, bob extends Speaker {}

-- widgets.md:8
sig Wobble extends Blurb { of: one Shword }

-- widgets.md:9
sig Jiggle extends Blurb { at: one Line }

-- widgets.md:10
sig Knob { tag: one Shword }

-- widgets.md:12
pred wobbly[l: Line] { some w: Wobble & l.speech | w.of = l.cmd }
