-- generated by assay from spike/crates/internal-tooling/tests/assay_fixture/widgets.assay.md; edit the spec, not this file
module words
open shared

one sig frob extends Shword {} -- widgets.assay.md:27
one sig spin extends Shword {} -- widgets.assay.md:28
one sig sprocket_heap extends Shword {} -- widgets.assay.md:29
one sig dash_dash_mode extends Shword {} -- widgets.assay.md:43
one sig fast extends Shword {} -- widgets.assay.md:43
one sig sprocket_path extends Shword {} -- widgets.assay.md:43
one sig knob_word extends Shword {} -- widgets.assay.md:45
one sig append_spin_log extends Shword {} -- widgets.assay.md:47
one sig stderr_to_stdout extends Shword {} -- widgets.assay.md:47
one sig twirl extends Shword {} -- widgets.assay.md:52
one sig w__dash_c extends Shword {} -- widgets.assay.md:56
one sig w__sq_x_sp_y_sq_ extends Shword {} -- widgets.assay.md:56
one sig w__slash_tmp_slash_gadget extends Shword {} -- widgets.assay.md:56
one sig assay_colon extends Shword {} -- assay: the corpus book's null command
one sig gizmo extends Class {} -- widgets.assay.md:47
fact { class = w__slash_tmp_slash_gadget->gizmo + sprocket_path->gizmo }
