-- generated by assay from spike/crates/internal-tooling/tests/assay_fixture/widgets.md; edit the spec, not this file
module words
open shared

one sig frob extends Shword {} -- widgets.md:27
one sig spin extends Shword {} -- widgets.md:28
one sig sprocket_heap extends Shword {} -- widgets.md:29
one sig dash_dash_mode extends Shword {} -- widgets.md:43
one sig fast extends Shword {} -- widgets.md:43
one sig sprocket_path extends Shword {} -- widgets.md:43
one sig knob_word extends Shword {} -- widgets.md:45
one sig append_spin_log extends Shword {} -- widgets.md:47
one sig stderr_to_stdout extends Shword {} -- widgets.md:47
one sig twirl extends Shword {} -- widgets.md:52
one sig assay_colon extends Shword {} -- assay: the corpus book's null command
one sig gizmo extends Class {} -- widgets.md:47
fact { class = sprocket_path->gizmo }
