-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lattice]: function definitions
import Aeneas
import Lattice.Types
import Lattice.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace lattice

/-- Trait implementation: [core::fmt::{impl core::fmt::Debug for (U, T)}]
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 3087:12-3087:57
    Name pattern: [core::fmt::Debug<(@U, @T)>] -/
@[reducible, rust_trait_impl "core::fmt::Debug<(@U, @T)>"]
def Pair.Insts.CoreFmtDebug {U : Type} {T : Type} (DebugInst : core.fmt.Debug
  U) (DebugInst1 : core.fmt.Debug T) : core.fmt.Debug (U × T) := {
  fmt := Pair.Insts.CoreFmtDebug.fmt DebugInst DebugInst1
}

/-- Trait implementation: [core::tuple::{impl core::cmp::PartialEq<(U, T)> for (U, T)}]
    Source: '/rustc/library/core/src/tuple.rs', lines 28:12-28:74
    Name pattern: [core::cmp::PartialEq<(@U, @T), (@U, @T)>] -/
@[reducible, rust_trait_impl "core::cmp::PartialEq<(@U, @T), (@U, @T)>"]
def Pair.Insts.CoreCmpPartialEqPair {U : Type} {T : Type} (cmpPartialEqInst :
  core.cmp.PartialEq U U) (cmpPartialEqInst1 : core.cmp.PartialEq T T) :
  core.cmp.PartialEq (U × T) (U × T) := {
  eq := Pair.Insts.CoreCmpPartialEqPair.eq cmpPartialEqInst cmpPartialEqInst1
  ne := Pair.Insts.CoreCmpPartialEqPair.ne cmpPartialEqInst cmpPartialEqInst1
}

/-- [lattice::lattice::Lattice::leq]:
    Source: 'lattice/src/lib.rs', lines 57:8-59:9
    Visibility: public -/
@[trait_default]
def lattice.Lattice.leq.default
  {Self : Type} (LatticeInst : lattice.Lattice Self) (self : Self)
  (other : Self) :
  Result Bool
  := do
  let t ← LatticeInst.join self other
  core.cmp.impls.PartialEqShared.eq LatticeInst.corecmpEqInst.partialEqInst t
    other

/-- [lattice::lattice::{impl core::fmt::Debug for lattice::lattice::Powerset<T>}::fmt]:
    Source: 'lattice/src/lib.rs', lines 83:13-83:18
    Visibility: public -/
def lattice.Powerset.Insts.CoreFmtDebug.fmt
  {T : Type} (corefmtDebugInst : core.fmt.Debug T) (corecmpOrdInst :
  core.cmp.Ord T) (corecloneCloneInst : core.clone.Clone T)
  (self : lattice.Powerset T) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn :=
    Dyn.mk _ (core.fmt.DebugShared (core.fmt.DebugVec corefmtDebugInst)) self
  core.fmt.Formatter.debug_tuple_field1_finish f (toStr "Powerset") dyn

/-- Trait implementation: [lattice::lattice::{impl core::fmt::Debug for lattice::lattice::Powerset<T>}]
    Source: 'lattice/src/lib.rs', lines 83:13-83:18 -/
@[reducible]
def lattice.Powerset.Insts.CoreFmtDebug {T : Type} (corefmtDebugInst :
  core.fmt.Debug T) (corecmpOrdInst : core.cmp.Ord T) (corecloneCloneInst :
  core.clone.Clone T) : core.fmt.Debug (lattice.Powerset T) := {
  fmt := lattice.Powerset.Insts.CoreFmtDebug.fmt corefmtDebugInst
    corecmpOrdInst corecloneCloneInst
}

/-- [lattice::lattice::{impl core::clone::Clone for lattice::lattice::Powerset<T>}::clone]:
    Source: 'lattice/src/lib.rs', lines 83:20-83:25
    Visibility: public -/
def lattice.Powerset.Insts.CoreCloneClone.clone
  {T : Type} (corecloneCloneInst : core.clone.Clone T) (corecmpOrdInst :
  core.cmp.Ord T) (corecloneCloneInst1 : core.clone.Clone T)
  (self : lattice.Powerset T) :
  Result (lattice.Powerset T)
  := do
  let v ← alloc.vec.CloneVec.clone corecloneCloneInst self
  ok v

/-- Trait implementation: [lattice::lattice::{impl core::clone::Clone for lattice::lattice::Powerset<T>}]
    Source: 'lattice/src/lib.rs', lines 83:20-83:25 -/
@[reducible]
def lattice.Powerset.Insts.CoreCloneClone {T : Type} (corecloneCloneInst :
  core.clone.Clone T) (corecmpOrdInst : core.cmp.Ord T) (corecloneCloneInst1 :
  core.clone.Clone T) : core.clone.Clone (lattice.Powerset T) := {
  clone := lattice.Powerset.Insts.CoreCloneClone.clone corecloneCloneInst
    corecmpOrdInst corecloneCloneInst
}

/-- Trait implementation: [lattice::lattice::{impl core::marker::StructuralPartialEq for lattice::lattice::Powerset<T>}]
    Source: 'lattice/src/lib.rs', lines 83:27-83:36 -/
@[reducible]
def lattice.Powerset.Insts.CoreMarkerStructuralPartialEq {T : Type}
  (corecmpOrdInst : core.cmp.Ord T) (corecloneCloneInst : core.clone.Clone T) :
  core.marker.StructuralPartialEq (lattice.Powerset T) := {
}

/-- [lattice::lattice::{impl core::cmp::PartialEq<lattice::lattice::Powerset<T>> for lattice::lattice::Powerset<T>}::eq]:
    Source: 'lattice/src/lib.rs', lines 83:27-83:36
    Visibility: public -/
def lattice.Powerset.Insts.CoreCmpPartialEqPowerset.eq
  {T : Type} (corecmpPartialEqInst : core.cmp.PartialEq T T) (corecmpOrdInst :
  core.cmp.Ord T) (corecloneCloneInst : core.clone.Clone T)
  (self : lattice.Powerset T) (other : lattice.Powerset T) :
  Result Bool
  := do
  alloc.vec.partial_eq.PartialEqVec.eq corecmpPartialEqInst self other

/-- Trait implementation: [lattice::lattice::{impl core::cmp::PartialEq<lattice::lattice::Powerset<T>> for lattice::lattice::Powerset<T>}]
    Source: 'lattice/src/lib.rs', lines 83:27-83:36 -/
@[reducible]
impl_def lattice.Powerset.Insts.CoreCmpPartialEqPowerset {T : Type}
  (corecmpPartialEqInst : core.cmp.PartialEq T T) (corecmpOrdInst :
  core.cmp.Ord T) (corecloneCloneInst : core.clone.Clone T) :
  core.cmp.PartialEq (lattice.Powerset T) (lattice.Powerset T) := {
  eq := lattice.Powerset.Insts.CoreCmpPartialEqPowerset.eq corecmpPartialEqInst
    corecmpOrdInst corecloneCloneInst
  ne := core.cmp.PartialEq.ne.trait_default
    (lattice.Powerset.Insts.CoreCmpPartialEqPowerset corecmpPartialEqInst
    corecmpOrdInst corecloneCloneInst)
}

/-- [lattice::lattice::{impl core::cmp::Eq for lattice::lattice::Powerset<T>}::assert_fields_are_eq]:
    Source: 'lattice/src/lib.rs', lines 83:38-83:40
    Visibility: public -/
def lattice.Powerset.Insts.CoreCmpEq.assert_fields_are_eq
  {T : Type} (corecmpEqInst : core.cmp.Eq T) (corecmpOrdInst : core.cmp.Ord T)
  (corecloneCloneInst : core.clone.Clone T) (self : lattice.Powerset T) :
  Result Unit
  := do
  ok ()

/-- Trait implementation: [lattice::lattice::{impl core::cmp::Eq for lattice::lattice::Powerset<T>}]
    Source: 'lattice/src/lib.rs', lines 83:38-83:40 -/
@[reducible]
def lattice.Powerset.Insts.CoreCmpEq {T : Type} (corecmpEqInst : core.cmp.Eq T)
  (corecmpOrdInst : core.cmp.Ord T) (corecloneCloneInst : core.clone.Clone T) :
  core.cmp.Eq (lattice.Powerset T) := {
  partialEqInst := lattice.Powerset.Insts.CoreCmpPartialEqPowerset
    corecmpEqInst.partialEqInst corecmpOrdInst corecloneCloneInst
  assert_fields_are_eq := lattice.Powerset.Insts.CoreCmpEq.assert_fields_are_eq
    corecmpEqInst corecmpOrdInst corecloneCloneInst
}

/-- [lattice::lattice::{impl core::default::Default for lattice::lattice::Powerset<T>}::default]:
    Source: 'lattice/src/lib.rs', lines 87:8-89:9
    Visibility: public -/
def lattice.Powerset.Insts.CoreDefaultDefault.default
  {T : Type} (corecmpOrdInst : core.cmp.Ord T) (corecloneCloneInst :
  core.clone.Clone T) :
  Result (lattice.Powerset T)
  := do
  ok (alloc.vec.Vec.new T)

/-- Trait implementation: [lattice::lattice::{impl core::default::Default for lattice::lattice::Powerset<T>}]
    Source: 'lattice/src/lib.rs', lines 86:4-90:5 -/
@[reducible]
def lattice.Powerset.Insts.CoreDefaultDefault {T : Type} (corecmpOrdInst :
  core.cmp.Ord T) (corecloneCloneInst : core.clone.Clone T) :
  core.default.Default (lattice.Powerset T) := {
  default := lattice.Powerset.Insts.CoreDefaultDefault.default corecmpOrdInst
    corecloneCloneInst
}

/-- [lattice::lattice::{lattice::lattice::Powerset<T>}::singleton]:
    Source: 'lattice/src/lib.rs', lines 94:8-98:9
    Visibility: public -/
def lattice.Powerset.singleton
  {T : Type} (corecmpOrdInst : core.cmp.Ord T) (corecloneCloneInst :
  core.clone.Clone T) (x : T) :
  Result (lattice.Powerset T)
  := do
  let s ← alloc.vec.Vec.push (alloc.vec.Vec.new T) x
  ok s

/-- [lattice::lattice::{lattice::lattice::Powerset<T>}::contains]: loop body 0:
    Source: 'lattice/src/lib.rs', lines 103:12-110:9
    Visibility: public -/
@[rust_loop_body]
def lattice.Powerset.contains_loop.body
  {T : Type} (corecmpOrdInst : core.cmp.Ord T) (x : T)
  (self : lattice.Powerset T) (i : Std.Usize) :
  Result (ControlFlow ((lattice.Powerset T) × Std.Usize) Bool)
  := do
  let i1 := alloc.vec.Vec.len self
  if i < i1
  then
    let t ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice T) self i
    let b ← corecmpOrdInst.eqInst.partialEqInst.eq t x
    if b
    then ok (done true)
    else let i2 ← i + 1#usize
         ok (cont (self, i2))
  else ok (done false)

/-- [lattice::lattice::{lattice::lattice::Powerset<T>}::contains]: loop 0:
    Source: 'lattice/src/lib.rs', lines 103:12-110:9
    Visibility: public -/
@[rust_loop]
def lattice.Powerset.contains_loop
  {T : Type} (corecmpOrdInst : core.cmp.Ord T) (self : lattice.Powerset T)
  (x : T) (i : Std.Usize) :
  Result Bool
  := do
  loop
    (fun (self1, i1) => lattice.Powerset.contains_loop.body corecmpOrdInst x
      self1 i1)
    (self, i)

/-- [lattice::lattice::{lattice::lattice::Powerset<T>}::contains]:
    Source: 'lattice/src/lib.rs', lines 101:8-110:9
    Visibility: public -/
@[reducible]
def lattice.Powerset.contains
  {T : Type} (corecmpOrdInst : core.cmp.Ord T) (corecloneCloneInst :
  core.clone.Clone T) (self : lattice.Powerset T) (x : T) :
  Result Bool
  := do
  lattice.Powerset.contains_loop corecmpOrdInst self x 0#usize

/-- [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::Powerset<T>}::meet]: loop body 0:
    Source: 'lattice/src/lib.rs', lines 1:0-152:13
    Visibility: public -/
@[rust_loop_body]
def lattice.Powerset.Insts.LatticeLatticeLattice.meet_loop.body
  {T : Type} (corecmpOrdInst : core.cmp.Ord T) (corecloneCloneInst :
  core.clone.Clone T) (self : lattice.Powerset T) (other : lattice.Powerset T)
  (out : alloc.vec.Vec T) (i : Std.Usize) (j : Std.Usize) :
  Result (ControlFlow ((lattice.Powerset T) × (lattice.Powerset T) ×
    (alloc.vec.Vec T) × Std.Usize × Std.Usize) (alloc.vec.Vec T))
  := do
  let i1 := alloc.vec.Vec.len self
  if i < i1
  then
    let i2 := alloc.vec.Vec.len other
    if j < i2
    then
      let t ←
        alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice T) self i
      let t1 ←
        alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice T) other j
      let b ← corecmpOrdInst.partialOrdInst.lt t t1
      if b
      then let i3 ← i + 1#usize
           ok (cont (self, other, out, i3, j))
      else
        let b1 ← corecmpOrdInst.partialOrdInst.lt t1 t
        if b1
        then let j1 ← j + 1#usize
             ok (cont (self, other, out, i, j1))
        else
          let t2 ← corecloneCloneInst.clone t
          let out1 ← alloc.vec.Vec.push out t2
          let i3 ← i + 1#usize
          let j1 ← j + 1#usize
          ok (cont (self, other, out1, i3, j1))
    else ok (done out)
  else ok (done out)

/-- [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::Powerset<T>}::meet]: loop 0:
    Source: 'lattice/src/lib.rs', lines 1:0-152:13
    Visibility: public -/
@[rust_loop]
def lattice.Powerset.Insts.LatticeLatticeLattice.meet_loop
  {T : Type} (corecmpOrdInst : core.cmp.Ord T) (corecloneCloneInst :
  core.clone.Clone T) (self : lattice.Powerset T) (other : lattice.Powerset T)
  (out : alloc.vec.Vec T) (i : Std.Usize) (j : Std.Usize) :
  Result (alloc.vec.Vec T)
  := do
  loop
    (fun (self1, other1, out1, i1, j1) =>
      lattice.Powerset.Insts.LatticeLatticeLattice.meet_loop.body
      corecmpOrdInst corecloneCloneInst self1 other1 out1 i1 j1)
    (self, other, out, i, j)

/-- [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::Powerset<T>}::meet]:
    Source: 'lattice/src/lib.rs', lines 138:8-154:9
    Visibility: public -/
def lattice.Powerset.Insts.LatticeLatticeLattice.meet
  {T : Type} (corecmpOrdInst : core.cmp.Ord T) (corecloneCloneInst :
  core.clone.Clone T) (self : lattice.Powerset T) (other : lattice.Powerset T)
  :
  Result (lattice.Powerset T)
  := do
  let out ←
    lattice.Powerset.Insts.LatticeLatticeLattice.meet_loop corecmpOrdInst
      corecloneCloneInst self other (alloc.vec.Vec.new T) 0#usize 0#usize
  ok out

/-- [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::Powerset<T>}::join]: loop body 1:
    Source: 'lattice/src/lib.rs', lines 1:0-125:17
    Visibility: public -/
@[rust_loop_body]
def lattice.Powerset.Insts.LatticeLatticeLattice.join_loop0_loop0.body
  {T : Type} (corecmpOrdInst : core.cmp.Ord T) (corecloneCloneInst :
  core.clone.Clone T) (v : alloc.vec.Vec T) (i : Std.Usize)
  (other : lattice.Powerset T) (out : alloc.vec.Vec T) (j : Std.Usize) :
  Result (ControlFlow ((lattice.Powerset T) × (alloc.vec.Vec T) × Std.Usize)
    ((alloc.vec.Vec T) × (alloc.vec.Vec T) × Std.Usize))
  := do
  let i1 := alloc.vec.Vec.len other
  if j < i1
  then
    let t ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice T) other j
    let t1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice T) v i
    let b ← corecmpOrdInst.partialOrdInst.lt t t1
    if b
    then
      let t2 ← corecloneCloneInst.clone t
      let out1 ← alloc.vec.Vec.push out t2
      let j1 ← j + 1#usize
      ok (cont (other, out1, j1))
    else ok (done (other, out, j))
  else ok (done (other, out, j))

/-- [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::Powerset<T>}::join]: loop 1:
    Source: 'lattice/src/lib.rs', lines 1:0-125:17
    Visibility: public -/
@[rust_loop]
def lattice.Powerset.Insts.LatticeLatticeLattice.join_loop0_loop0
  {T : Type} (corecmpOrdInst : core.cmp.Ord T) (corecloneCloneInst :
  core.clone.Clone T) (v : alloc.vec.Vec T) (other : lattice.Powerset T)
  (out : alloc.vec.Vec T) (i : Std.Usize) (j : Std.Usize) :
  Result ((alloc.vec.Vec T) × (alloc.vec.Vec T) × Std.Usize)
  := do
  loop
    (fun (other1, out1, j1) =>
      lattice.Powerset.Insts.LatticeLatticeLattice.join_loop0_loop0.body
      corecmpOrdInst corecloneCloneInst v i other1 out1 j1)
    (other, out, j)

/-- [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::Powerset<T>}::join]: loop body 0:
    Source: 'lattice/src/lib.rs', lines 1:0-131:13
    Visibility: public -/
@[rust_loop_body]
def lattice.Powerset.Insts.LatticeLatticeLattice.join_loop0.body
  {T : Type} (corecmpOrdInst : core.cmp.Ord T) (corecloneCloneInst :
  core.clone.Clone T) (self : lattice.Powerset T) (other : lattice.Powerset T)
  (out : alloc.vec.Vec T) (i : Std.Usize) (j : Std.Usize) :
  Result (ControlFlow ((lattice.Powerset T) × (lattice.Powerset T) ×
    (alloc.vec.Vec T) × Std.Usize × Std.Usize) ((lattice.Powerset T) ×
    (alloc.vec.Vec T) × Std.Usize))
  := do
  let i1 := alloc.vec.Vec.len self
  if i < i1
  then
    let (v, out1, j1) ←
      lattice.Powerset.Insts.LatticeLatticeLattice.join_loop0_loop0
        corecmpOrdInst corecloneCloneInst self other out i j
    let i2 := alloc.vec.Vec.len v
    let j2 ←
      if j1 < i2
      then
        do
        let t ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice T) v j1
        let t1 ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice T) self i
        let b ← corecmpOrdInst.eqInst.partialEqInst.eq t t1
        if b
        then j1 + 1#usize
        else ok j1
      else ok j1
    let t ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice T) self i
    let t1 ← corecloneCloneInst.clone t
    let out2 ← alloc.vec.Vec.push out1 t1
    let i3 ← i + 1#usize
    ok (cont (self, v, out2, i3, j2))
  else ok (done (other, out, j))

/-- [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::Powerset<T>}::join]: loop 0:
    Source: 'lattice/src/lib.rs', lines 1:0-131:13
    Visibility: public -/
@[rust_loop]
def lattice.Powerset.Insts.LatticeLatticeLattice.join_loop0
  {T : Type} (corecmpOrdInst : core.cmp.Ord T) (corecloneCloneInst :
  core.clone.Clone T) (self : lattice.Powerset T) (other : lattice.Powerset T)
  (out : alloc.vec.Vec T) (i : Std.Usize) (j : Std.Usize) :
  Result ((lattice.Powerset T) × (alloc.vec.Vec T) × Std.Usize)
  := do
  loop
    (fun (self1, other1, out1, i1, j1) =>
      lattice.Powerset.Insts.LatticeLatticeLattice.join_loop0.body
      corecmpOrdInst corecloneCloneInst self1 other1 out1 i1 j1)
    (self, other, out, i, j)

/-- [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::Powerset<T>}::join]: loop body 2:
    Source: 'lattice/src/lib.rs', lines 132:12-135:13
    Visibility: public -/
@[rust_loop_body]
def lattice.Powerset.Insts.LatticeLatticeLattice.join_loop1.body
  {T : Type} (corecloneCloneInst : core.clone.Clone T)
  (other : lattice.Powerset T) (out : alloc.vec.Vec T) (j : Std.Usize) :
  Result (ControlFlow ((lattice.Powerset T) × (alloc.vec.Vec T) × Std.Usize)
    (alloc.vec.Vec T))
  := do
  let i := alloc.vec.Vec.len other
  if j < i
  then
    let t ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice T) other j
    let t1 ← corecloneCloneInst.clone t
    let out1 ← alloc.vec.Vec.push out t1
    let j1 ← j + 1#usize
    ok (cont (other, out1, j1))
  else ok (done out)

/-- [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::Powerset<T>}::join]: loop 2:
    Source: 'lattice/src/lib.rs', lines 132:12-135:13
    Visibility: public -/
@[rust_loop]
def lattice.Powerset.Insts.LatticeLatticeLattice.join_loop1
  {T : Type} (corecloneCloneInst : core.clone.Clone T)
  (other : lattice.Powerset T) (out : alloc.vec.Vec T) (j : Std.Usize) :
  Result (alloc.vec.Vec T)
  := do
  loop
    (fun (other1, out1, j1) =>
      lattice.Powerset.Insts.LatticeLatticeLattice.join_loop1.body
      corecloneCloneInst other1 out1 j1)
    (other, out, j)

/-- [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::Powerset<T>}::join]:
    Source: 'lattice/src/lib.rs', lines 117:8-137:9
    Visibility: public -/
def lattice.Powerset.Insts.LatticeLatticeLattice.join
  {T : Type} (corecmpOrdInst : core.cmp.Ord T) (corecloneCloneInst :
  core.clone.Clone T) (self : lattice.Powerset T) (other : lattice.Powerset T)
  :
  Result (lattice.Powerset T)
  := do
  let (other1, out, j) ←
    lattice.Powerset.Insts.LatticeLatticeLattice.join_loop0 corecmpOrdInst
      corecloneCloneInst self other (alloc.vec.Vec.new T) 0#usize 0#usize
  let out1 ←
    lattice.Powerset.Insts.LatticeLatticeLattice.join_loop1 corecloneCloneInst
      other1 out j
  ok out1

/-- [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::Powerset<T>}::bottom]:
    Source: 'lattice/src/lib.rs', lines 114:8-116:9
    Visibility: public -/
def lattice.Powerset.Insts.LatticeLatticeLattice.bottom
  {T : Type} (corecmpOrdInst : core.cmp.Ord T) (corecloneCloneInst :
  core.clone.Clone T) :
  Result (lattice.Powerset T)
  := do
  ok (alloc.vec.Vec.new T)

/-- Trait implementation: [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::Powerset<T>}]
    Source: 'lattice/src/lib.rs', lines 113:4-155:5 -/
@[reducible]
impl_def lattice.Powerset.Insts.LatticeLatticeLattice {T : Type}
  (corecmpOrdInst : core.cmp.Ord T) (corecloneCloneInst1 : core.clone.Clone T)
  : lattice.Lattice (lattice.Powerset T) := {
  corecloneCloneInst := lattice.Powerset.Insts.CoreCloneClone
    corecloneCloneInst1 corecmpOrdInst corecloneCloneInst1
  corecmpEqInst := lattice.Powerset.Insts.CoreCmpEq corecmpOrdInst.eqInst
    corecmpOrdInst corecloneCloneInst1
  bottom := lattice.Powerset.Insts.LatticeLatticeLattice.bottom corecmpOrdInst
    corecloneCloneInst1
  join := lattice.Powerset.Insts.LatticeLatticeLattice.join corecmpOrdInst
    corecloneCloneInst1
  meet := lattice.Powerset.Insts.LatticeLatticeLattice.meet corecmpOrdInst
    corecloneCloneInst1
  leq := lattice.Lattice.leq.default
    (lattice.Powerset.Insts.LatticeLatticeLattice corecmpOrdInst
    corecloneCloneInst1)
}

/-- [lattice::lattice::{impl core::fmt::Debug for lattice::lattice::Flat<T>}::fmt]:
    Source: 'lattice/src/lib.rs', lines 161:13-161:18
    Visibility: public -/
def lattice.Flat.Insts.CoreFmtDebug.fmt
  {T : Type} (corefmtDebugInst : core.fmt.Debug T) (corecloneCloneInst :
  core.clone.Clone T) (corecmpEqInst : core.cmp.Eq T) (self : lattice.Flat T)
  (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | lattice.Flat.Bottom => core.fmt.Formatter.write_str f (toStr "Bottom")
  | lattice.Flat.Elem __self_0 =>
    let __self_01 := Dyn.mk _ (core.fmt.DebugShared corefmtDebugInst) __self_0
    core.fmt.Formatter.debug_tuple_field1_finish f (toStr "Elem") __self_01
  | lattice.Flat.Top => core.fmt.Formatter.write_str f (toStr "Top")

/-- Trait implementation: [lattice::lattice::{impl core::fmt::Debug for lattice::lattice::Flat<T>}]
    Source: 'lattice/src/lib.rs', lines 161:13-161:18 -/
@[reducible]
def lattice.Flat.Insts.CoreFmtDebug {T : Type} (corefmtDebugInst :
  core.fmt.Debug T) (corecloneCloneInst : core.clone.Clone T) (corecmpEqInst :
  core.cmp.Eq T) : core.fmt.Debug (lattice.Flat T) := {
  fmt := lattice.Flat.Insts.CoreFmtDebug.fmt corefmtDebugInst
    corecloneCloneInst corecmpEqInst
}

/-- [lattice::lattice::{impl core::clone::Clone for lattice::lattice::Flat<T>}::clone]:
    Source: 'lattice/src/lib.rs', lines 161:20-161:25
    Visibility: public -/
def lattice.Flat.Insts.CoreCloneClone.clone
  {T : Type} (corecloneCloneInst : core.clone.Clone T) (corecloneCloneInst1 :
  core.clone.Clone T) (corecmpEqInst : core.cmp.Eq T) (self : lattice.Flat T) :
  Result (lattice.Flat T)
  := do
  match self with
  | lattice.Flat.Bottom => ok lattice.Flat.Bottom
  | lattice.Flat.Elem __self_0 =>
    let t ← corecloneCloneInst.clone __self_0
    ok (lattice.Flat.Elem t)
  | lattice.Flat.Top => ok lattice.Flat.Top

/-- Trait implementation: [lattice::lattice::{impl core::clone::Clone for lattice::lattice::Flat<T>}]
    Source: 'lattice/src/lib.rs', lines 161:20-161:25 -/
@[reducible]
def lattice.Flat.Insts.CoreCloneClone {T : Type} (corecloneCloneInst :
  core.clone.Clone T) (corecloneCloneInst1 : core.clone.Clone T) (corecmpEqInst
  : core.cmp.Eq T) : core.clone.Clone (lattice.Flat T) := {
  clone := lattice.Flat.Insts.CoreCloneClone.clone corecloneCloneInst
    corecloneCloneInst corecmpEqInst
}

/-- Trait implementation: [lattice::lattice::{impl core::marker::StructuralPartialEq for lattice::lattice::Flat<T>}]
    Source: 'lattice/src/lib.rs', lines 161:27-161:36 -/
@[reducible]
def lattice.Flat.Insts.CoreMarkerStructuralPartialEq {T : Type}
  (corecloneCloneInst : core.clone.Clone T) (corecmpEqInst : core.cmp.Eq T) :
  core.marker.StructuralPartialEq (lattice.Flat T) := {
}

/-- [lattice::lattice::{impl core::cmp::PartialEq<lattice::lattice::Flat<T>> for lattice::lattice::Flat<T>}::eq]:
    Source: 'lattice/src/lib.rs', lines 161:27-161:36
    Visibility: public -/
def lattice.Flat.Insts.CoreCmpPartialEqFlat.eq
  {T : Type} (corecmpPartialEqInst : core.cmp.PartialEq T T)
  (corecloneCloneInst : core.clone.Clone T) (corecmpEqInst : core.cmp.Eq T)
  (self : lattice.Flat T) (other : lattice.Flat T) :
  Result Bool
  := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  if self1 = other1
  then
    match self with
    | lattice.Flat.Bottom => ok true
    | lattice.Flat.Elem __self_0 =>
      match other with
      | lattice.Flat.Bottom => ok true
      | lattice.Flat.Elem __arg1_0 =>
        core.cmp.impls.PartialEqShared.eq corecmpPartialEqInst __self_0
          __arg1_0
      | lattice.Flat.Top => ok true
    | lattice.Flat.Top => ok true
  else ok false

/-- Trait implementation: [lattice::lattice::{impl core::cmp::PartialEq<lattice::lattice::Flat<T>> for lattice::lattice::Flat<T>}]
    Source: 'lattice/src/lib.rs', lines 161:27-161:36 -/
@[reducible]
impl_def lattice.Flat.Insts.CoreCmpPartialEqFlat {T : Type}
  (corecmpPartialEqInst : core.cmp.PartialEq T T) (corecloneCloneInst :
  core.clone.Clone T) (corecmpEqInst : core.cmp.Eq T) : core.cmp.PartialEq
  (lattice.Flat T) (lattice.Flat T) := {
  eq := lattice.Flat.Insts.CoreCmpPartialEqFlat.eq corecmpPartialEqInst
    corecloneCloneInst corecmpEqInst
  ne := core.cmp.PartialEq.ne.trait_default
    (lattice.Flat.Insts.CoreCmpPartialEqFlat corecmpPartialEqInst
    corecloneCloneInst corecmpEqInst)
}

/-- [lattice::lattice::{impl core::cmp::Eq for lattice::lattice::Flat<T>}::assert_fields_are_eq]:
    Source: 'lattice/src/lib.rs', lines 161:38-161:40
    Visibility: public -/
def lattice.Flat.Insts.CoreCmpEq.assert_fields_are_eq
  {T : Type} (corecmpEqInst : core.cmp.Eq T) (corecloneCloneInst :
  core.clone.Clone T) (corecmpEqInst1 : core.cmp.Eq T) (self : lattice.Flat T)
  :
  Result Unit
  := do
  ok ()

/-- Trait implementation: [lattice::lattice::{impl core::cmp::Eq for lattice::lattice::Flat<T>}]
    Source: 'lattice/src/lib.rs', lines 161:38-161:40 -/
@[reducible]
def lattice.Flat.Insts.CoreCmpEq {T : Type} (corecmpEqInst : core.cmp.Eq T)
  (corecloneCloneInst : core.clone.Clone T) (corecmpEqInst1 : core.cmp.Eq T) :
  core.cmp.Eq (lattice.Flat T) := {
  partialEqInst := lattice.Flat.Insts.CoreCmpPartialEqFlat
    corecmpEqInst.partialEqInst corecloneCloneInst corecmpEqInst
  assert_fields_are_eq := lattice.Flat.Insts.CoreCmpEq.assert_fields_are_eq
    corecmpEqInst corecloneCloneInst corecmpEqInst
}

/-- [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::Flat<T>}::meet]:
    Source: 'lattice/src/lib.rs', lines 185:8-197:9
    Visibility: public -/
def lattice.Flat.Insts.LatticeLatticeLattice.meet
  {T : Type} (corecloneCloneInst : core.clone.Clone T) (corecmpEqInst :
  core.cmp.Eq T) (self : lattice.Flat T) (other : lattice.Flat T) :
  Result (lattice.Flat T)
  := do
  match self with
  | lattice.Flat.Bottom =>
    match other with
    | lattice.Flat.Bottom => ok lattice.Flat.Bottom
    | lattice.Flat.Elem _ => ok lattice.Flat.Bottom
    | lattice.Flat.Top =>
      lattice.Flat.Insts.CoreCloneClone.clone corecloneCloneInst
        corecloneCloneInst corecmpEqInst lattice.Flat.Bottom
  | lattice.Flat.Elem a =>
    match other with
    | lattice.Flat.Bottom => ok lattice.Flat.Bottom
    | lattice.Flat.Elem b =>
      let b1 ←
        core.cmp.impls.PartialEqShared.eq corecmpEqInst.partialEqInst a b
      if b1
      then let t ← corecloneCloneInst.clone a
           ok (lattice.Flat.Elem t)
      else ok lattice.Flat.Bottom
    | lattice.Flat.Top =>
      lattice.Flat.Insts.CoreCloneClone.clone corecloneCloneInst
        corecloneCloneInst corecmpEqInst self
  | lattice.Flat.Top =>
    lattice.Flat.Insts.CoreCloneClone.clone corecloneCloneInst
      corecloneCloneInst corecmpEqInst other

/-- [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::Flat<T>}::join]:
    Source: 'lattice/src/lib.rs', lines 172:8-184:9
    Visibility: public -/
def lattice.Flat.Insts.LatticeLatticeLattice.join
  {T : Type} (corecloneCloneInst : core.clone.Clone T) (corecmpEqInst :
  core.cmp.Eq T) (self : lattice.Flat T) (other : lattice.Flat T) :
  Result (lattice.Flat T)
  := do
  match self with
  | lattice.Flat.Bottom =>
    lattice.Flat.Insts.CoreCloneClone.clone corecloneCloneInst
      corecloneCloneInst corecmpEqInst other
  | lattice.Flat.Elem a =>
    match other with
    | lattice.Flat.Bottom =>
      lattice.Flat.Insts.CoreCloneClone.clone corecloneCloneInst
        corecloneCloneInst corecmpEqInst self
    | lattice.Flat.Elem b =>
      let b1 ←
        core.cmp.impls.PartialEqShared.eq corecmpEqInst.partialEqInst a b
      if b1
      then let t ← corecloneCloneInst.clone a
           ok (lattice.Flat.Elem t)
      else ok lattice.Flat.Top
    | lattice.Flat.Top => ok lattice.Flat.Top
  | lattice.Flat.Top =>
    match other with
    | lattice.Flat.Bottom =>
      lattice.Flat.Insts.CoreCloneClone.clone corecloneCloneInst
        corecloneCloneInst corecmpEqInst lattice.Flat.Top
    | lattice.Flat.Elem _ => ok lattice.Flat.Top
    | lattice.Flat.Top => ok lattice.Flat.Top

/-- [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::Flat<T>}::bottom]:
    Source: 'lattice/src/lib.rs', lines 169:8-171:9
    Visibility: public -/
def lattice.Flat.Insts.LatticeLatticeLattice.bottom
  {T : Type} (corecloneCloneInst : core.clone.Clone T) (corecmpEqInst :
  core.cmp.Eq T) :
  Result (lattice.Flat T)
  := do
  ok lattice.Flat.Bottom

/-- Trait implementation: [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::Flat<T>}]
    Source: 'lattice/src/lib.rs', lines 168:4-198:5 -/
@[reducible]
impl_def lattice.Flat.Insts.LatticeLatticeLattice {T : Type}
  (corecloneCloneInst1 : core.clone.Clone T) (corecmpEqInst1 : core.cmp.Eq T) :
  lattice.Lattice (lattice.Flat T) := {
  corecloneCloneInst := lattice.Flat.Insts.CoreCloneClone corecloneCloneInst1
    corecloneCloneInst1 corecmpEqInst1
  corecmpEqInst := lattice.Flat.Insts.CoreCmpEq corecmpEqInst1
    corecloneCloneInst1 corecmpEqInst1
  bottom := lattice.Flat.Insts.LatticeLatticeLattice.bottom corecloneCloneInst1
    corecmpEqInst1
  join := lattice.Flat.Insts.LatticeLatticeLattice.join corecloneCloneInst1
    corecmpEqInst1
  meet := lattice.Flat.Insts.LatticeLatticeLattice.meet corecloneCloneInst1
    corecmpEqInst1
  leq := lattice.Lattice.leq.default (lattice.Flat.Insts.LatticeLatticeLattice
    corecloneCloneInst1 corecmpEqInst1)
}

/-- [lattice::lattice::{impl lattice::lattice::BoundedLattice for lattice::lattice::Flat<T>}::top]:
    Source: 'lattice/src/lib.rs', lines 201:8-203:9
    Visibility: public -/
def lattice.Flat.Insts.LatticeLatticeBoundedLattice.top
  {T : Type} (corecloneCloneInst : core.clone.Clone T) (corecmpEqInst :
  core.cmp.Eq T) :
  Result (lattice.Flat T)
  := do
  ok lattice.Flat.Top

/-- Trait implementation: [lattice::lattice::{impl lattice::lattice::BoundedLattice for lattice::lattice::Flat<T>}]
    Source: 'lattice/src/lib.rs', lines 200:4-204:5 -/
@[reducible]
def lattice.Flat.Insts.LatticeLatticeBoundedLattice {T : Type}
  (corecloneCloneInst : core.clone.Clone T) (corecmpEqInst : core.cmp.Eq T) :
  lattice.BoundedLattice (lattice.Flat T) := {
  LatticeInst := lattice.Flat.Insts.LatticeLatticeLattice corecloneCloneInst
    corecmpEqInst
  top := lattice.Flat.Insts.LatticeLatticeBoundedLattice.top corecloneCloneInst
    corecmpEqInst
}

/-- [lattice::lattice::{impl core::fmt::Debug for lattice::lattice::Product<A, B>}::fmt]:
    Source: 'lattice/src/lib.rs', lines 208:13-208:18
    Visibility: public -/
def lattice.Product.Insts.CoreFmtDebug.fmt
  {A : Type} {B : Type} (corefmtDebugInst : core.fmt.Debug A)
  (corefmtDebugInst1 : core.fmt.Debug B) (self : lattice.Product A B)
  (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let (t, t1) := self
  let dyn := Dyn.mk _ corefmtDebugInst t
  let dyn1 := Dyn.mk _ (core.fmt.DebugShared corefmtDebugInst1) t1
  core.fmt.Formatter.debug_tuple_field2_finish f (toStr "Product") dyn dyn1

/-- Trait implementation: [lattice::lattice::{impl core::fmt::Debug for lattice::lattice::Product<A, B>}]
    Source: 'lattice/src/lib.rs', lines 208:13-208:18 -/
@[reducible]
def lattice.Product.Insts.CoreFmtDebug {A : Type} {B : Type} (corefmtDebugInst
  : core.fmt.Debug A) (corefmtDebugInst1 : core.fmt.Debug B) : core.fmt.Debug
  (lattice.Product A B) := {
  fmt := lattice.Product.Insts.CoreFmtDebug.fmt corefmtDebugInst
    corefmtDebugInst1
}

/-- [lattice::lattice::{impl core::clone::Clone for lattice::lattice::Product<A, B>}::clone]:
    Source: 'lattice/src/lib.rs', lines 208:20-208:25
    Visibility: public -/
def lattice.Product.Insts.CoreCloneClone.clone
  {A : Type} {B : Type} (corecloneCloneInst : core.clone.Clone A)
  (corecloneCloneInst1 : core.clone.Clone B) (self : lattice.Product A B) :
  Result (lattice.Product A B)
  := do
  let (t, t1) := self
  let t2 ← corecloneCloneInst.clone t
  let t3 ← corecloneCloneInst1.clone t1
  ok (t2, t3)

/-- Trait implementation: [lattice::lattice::{impl core::clone::Clone for lattice::lattice::Product<A, B>}]
    Source: 'lattice/src/lib.rs', lines 208:20-208:25 -/
@[reducible]
def lattice.Product.Insts.CoreCloneClone {A : Type} {B : Type}
  (corecloneCloneInst : core.clone.Clone A) (corecloneCloneInst1 :
  core.clone.Clone B) : core.clone.Clone (lattice.Product A B) := {
  clone := lattice.Product.Insts.CoreCloneClone.clone corecloneCloneInst
    corecloneCloneInst1
}

/-- Trait implementation: [lattice::lattice::{impl core::marker::StructuralPartialEq for lattice::lattice::Product<A, B>}]
    Source: 'lattice/src/lib.rs', lines 208:27-208:36 -/
@[reducible]
def lattice.Product.Insts.CoreMarkerStructuralPartialEq (A : Type) (B : Type) :
  core.marker.StructuralPartialEq (lattice.Product A B) := {
}

/-- [lattice::lattice::{impl core::cmp::PartialEq<lattice::lattice::Product<A, B>> for lattice::lattice::Product<A, B>}::eq]:
    Source: 'lattice/src/lib.rs', lines 208:27-208:36
    Visibility: public -/
def lattice.Product.Insts.CoreCmpPartialEqProduct.eq
  {A : Type} {B : Type} (corecmpPartialEqInst : core.cmp.PartialEq A A)
  (corecmpPartialEqInst1 : core.cmp.PartialEq B B) (self : lattice.Product A B)
  (other : lattice.Product A B) :
  Result Bool
  := do
  let (t, t1) := self
  let (t2, t3) := other
  let b ← corecmpPartialEqInst.eq t t2
  if b
  then corecmpPartialEqInst1.eq t1 t3
  else ok false

/-- Trait implementation: [lattice::lattice::{impl core::cmp::PartialEq<lattice::lattice::Product<A, B>> for lattice::lattice::Product<A, B>}]
    Source: 'lattice/src/lib.rs', lines 208:27-208:36 -/
@[reducible]
impl_def lattice.Product.Insts.CoreCmpPartialEqProduct {A : Type} {B : Type}
  (corecmpPartialEqInst : core.cmp.PartialEq A A) (corecmpPartialEqInst1 :
  core.cmp.PartialEq B B) : core.cmp.PartialEq (lattice.Product A B)
  (lattice.Product A B) := {
  eq := lattice.Product.Insts.CoreCmpPartialEqProduct.eq corecmpPartialEqInst
    corecmpPartialEqInst1
  ne := core.cmp.PartialEq.ne.trait_default
    (lattice.Product.Insts.CoreCmpPartialEqProduct corecmpPartialEqInst
    corecmpPartialEqInst1)
}

/-- [lattice::lattice::{impl core::cmp::Eq for lattice::lattice::Product<A, B>}::assert_fields_are_eq]:
    Source: 'lattice/src/lib.rs', lines 208:38-208:40
    Visibility: public -/
def lattice.Product.Insts.CoreCmpEq.assert_fields_are_eq
  {A : Type} {B : Type} (corecmpEqInst : core.cmp.Eq A) (corecmpEqInst1 :
  core.cmp.Eq B) (self : lattice.Product A B) :
  Result Unit
  := do
  ok ()

/-- Trait implementation: [lattice::lattice::{impl core::cmp::Eq for lattice::lattice::Product<A, B>}]
    Source: 'lattice/src/lib.rs', lines 208:38-208:40 -/
@[reducible]
def lattice.Product.Insts.CoreCmpEq {A : Type} {B : Type} (corecmpEqInst :
  core.cmp.Eq A) (corecmpEqInst1 : core.cmp.Eq B) : core.cmp.Eq
  (lattice.Product A B) := {
  partialEqInst := lattice.Product.Insts.CoreCmpPartialEqProduct
    corecmpEqInst.partialEqInst corecmpEqInst1.partialEqInst
  assert_fields_are_eq := lattice.Product.Insts.CoreCmpEq.assert_fields_are_eq
    corecmpEqInst corecmpEqInst1
}

/-- [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::Product<A, B>}::meet]:
    Source: 'lattice/src/lib.rs', lines 218:8-220:9
    Visibility: public -/
def lattice.Product.Insts.LatticeLatticeLattice.meet
  {A : Type} {B : Type} (LatticeInst : lattice.Lattice A) (LatticeInst1 :
  lattice.Lattice B) (self : lattice.Product A B) (other : lattice.Product A B)
  :
  Result (lattice.Product A B)
  := do
  let (t, t1) := self
  let (t2, t3) := other
  let t4 ← LatticeInst.meet t t2
  let t5 ← LatticeInst1.meet t1 t3
  ok (t4, t5)

/-- [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::Product<A, B>}::join]:
    Source: 'lattice/src/lib.rs', lines 215:8-217:9
    Visibility: public -/
def lattice.Product.Insts.LatticeLatticeLattice.join
  {A : Type} {B : Type} (LatticeInst : lattice.Lattice A) (LatticeInst1 :
  lattice.Lattice B) (self : lattice.Product A B) (other : lattice.Product A B)
  :
  Result (lattice.Product A B)
  := do
  let (t, t1) := self
  let (t2, t3) := other
  let t4 ← LatticeInst.join t t2
  let t5 ← LatticeInst1.join t1 t3
  ok (t4, t5)

/-- [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::Product<A, B>}::bottom]:
    Source: 'lattice/src/lib.rs', lines 212:8-214:9
    Visibility: public -/
def lattice.Product.Insts.LatticeLatticeLattice.bottom
  {A : Type} {B : Type} (LatticeInst : lattice.Lattice A) (LatticeInst1 :
  lattice.Lattice B) :
  Result (lattice.Product A B)
  := do
  let t ← LatticeInst.bottom
  let t1 ← LatticeInst1.bottom
  ok (t, t1)

/-- Trait implementation: [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::Product<A, B>}]
    Source: 'lattice/src/lib.rs', lines 211:4-221:5 -/
@[reducible]
impl_def lattice.Product.Insts.LatticeLatticeLattice {A : Type} {B : Type}
  (LatticeInst : lattice.Lattice A) (LatticeInst1 : lattice.Lattice B) :
  lattice.Lattice (lattice.Product A B) := {
  corecloneCloneInst := lattice.Product.Insts.CoreCloneClone
    LatticeInst.corecloneCloneInst LatticeInst1.corecloneCloneInst
  corecmpEqInst := lattice.Product.Insts.CoreCmpEq LatticeInst.corecmpEqInst
    LatticeInst1.corecmpEqInst
  bottom := lattice.Product.Insts.LatticeLatticeLattice.bottom LatticeInst
    LatticeInst1
  join := lattice.Product.Insts.LatticeLatticeLattice.join LatticeInst
    LatticeInst1
  meet := lattice.Product.Insts.LatticeLatticeLattice.meet LatticeInst
    LatticeInst1
  leq := lattice.Lattice.leq.default
    (lattice.Product.Insts.LatticeLatticeLattice LatticeInst LatticeInst1)
}

/-- [lattice::lattice::{impl lattice::lattice::BoundedLattice for lattice::lattice::Product<A, B>}::top]:
    Source: 'lattice/src/lib.rs', lines 227:8-229:9
    Visibility: public -/
def lattice.Product.Insts.LatticeLatticeBoundedLattice.top
  {A : Type} {B : Type} (BoundedLatticeInst : lattice.BoundedLattice A)
  (BoundedLatticeInst1 : lattice.BoundedLattice B) :
  Result (lattice.Product A B)
  := do
  let t ← BoundedLatticeInst.top
  let t1 ← BoundedLatticeInst1.top
  ok (t, t1)

/-- Trait implementation: [lattice::lattice::{impl lattice::lattice::BoundedLattice for lattice::lattice::Product<A, B>}]
    Source: 'lattice/src/lib.rs', lines 226:4-230:5 -/
@[reducible]
def lattice.Product.Insts.LatticeLatticeBoundedLattice {A : Type} {B : Type}
  (BoundedLatticeInst : lattice.BoundedLattice A) (BoundedLatticeInst1 :
  lattice.BoundedLattice B) : lattice.BoundedLattice (lattice.Product A B) := {
  LatticeInst := lattice.Product.Insts.LatticeLatticeLattice
    BoundedLatticeInst.LatticeInst BoundedLatticeInst1.LatticeInst
  top := lattice.Product.Insts.LatticeLatticeBoundedLattice.top
    BoundedLatticeInst BoundedLatticeInst1
}

/-- [lattice::lattice::{impl core::fmt::Debug for lattice::lattice::MapL<K, V>}::fmt]:
    Source: 'lattice/src/lib.rs', lines 243:13-243:18
    Visibility: public -/
def lattice.MapL.Insts.CoreFmtDebug.fmt
  {K : Type} {V : Type} (corefmtDebugInst : core.fmt.Debug K) (corecmpOrdInst :
  core.cmp.Ord K) (corecloneCloneInst : core.clone.Clone K) (corefmtDebugInst1
  : core.fmt.Debug V) (LatticeInst : lattice.Lattice V)
  (self : lattice.MapL K V) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn :=
    Dyn.mk _ (core.fmt.DebugShared (core.fmt.DebugVec (Pair.Insts.CoreFmtDebug
      corefmtDebugInst corefmtDebugInst1))) self
  core.fmt.Formatter.debug_tuple_field1_finish f (toStr "MapL") dyn

/-- Trait implementation: [lattice::lattice::{impl core::fmt::Debug for lattice::lattice::MapL<K, V>}]
    Source: 'lattice/src/lib.rs', lines 243:13-243:18 -/
@[reducible]
def lattice.MapL.Insts.CoreFmtDebug {K : Type} {V : Type} (corefmtDebugInst :
  core.fmt.Debug K) (corecmpOrdInst : core.cmp.Ord K) (corecloneCloneInst :
  core.clone.Clone K) (corefmtDebugInst1 : core.fmt.Debug V) (LatticeInst :
  lattice.Lattice V) : core.fmt.Debug (lattice.MapL K V) := {
  fmt := lattice.MapL.Insts.CoreFmtDebug.fmt corefmtDebugInst corecmpOrdInst
    corecloneCloneInst corefmtDebugInst1 LatticeInst
}

/-- [lattice::lattice::{impl core::clone::Clone for lattice::lattice::MapL<K, V>}::clone]:
    Source: 'lattice/src/lib.rs', lines 243:20-243:25
    Visibility: public -/
def lattice.MapL.Insts.CoreCloneClone.clone
  {K : Type} {V : Type} (corecloneCloneInst : core.clone.Clone K)
  (corecmpOrdInst : core.cmp.Ord K) (corecloneCloneInst1 : core.clone.Clone K)
  (corecloneCloneInst2 : core.clone.Clone V) (LatticeInst : lattice.Lattice V)
  (self : lattice.MapL K V) :
  Result (lattice.MapL K V)
  := do
  let v ← alloc.vec.CloneVec.clone (BuiltinClone (K × V)) self
  ok v

/-- Trait implementation: [lattice::lattice::{impl core::clone::Clone for lattice::lattice::MapL<K, V>}]
    Source: 'lattice/src/lib.rs', lines 243:20-243:25 -/
@[reducible]
def lattice.MapL.Insts.CoreCloneClone {K : Type} {V : Type} (corecloneCloneInst
  : core.clone.Clone K) (corecmpOrdInst : core.cmp.Ord K) (corecloneCloneInst1
  : core.clone.Clone K) (corecloneCloneInst2 : core.clone.Clone V) (LatticeInst
  : lattice.Lattice V) : core.clone.Clone (lattice.MapL K V) := {
  clone := lattice.MapL.Insts.CoreCloneClone.clone corecloneCloneInst
    corecmpOrdInst corecloneCloneInst corecloneCloneInst2 LatticeInst
}

/-- Trait implementation: [lattice::lattice::{impl core::marker::StructuralPartialEq for lattice::lattice::MapL<K, V>}]
    Source: 'lattice/src/lib.rs', lines 243:27-243:36 -/
@[reducible]
def lattice.MapL.Insts.CoreMarkerStructuralPartialEq {K : Type} {V : Type}
  (corecmpOrdInst : core.cmp.Ord K) (corecloneCloneInst : core.clone.Clone K)
  (LatticeInst : lattice.Lattice V) : core.marker.StructuralPartialEq
  (lattice.MapL K V) := {
}

/-- [lattice::lattice::{impl core::cmp::PartialEq<lattice::lattice::MapL<K, V>> for lattice::lattice::MapL<K, V>}::eq]:
    Source: 'lattice/src/lib.rs', lines 243:27-243:36
    Visibility: public -/
def lattice.MapL.Insts.CoreCmpPartialEqMapL.eq
  {K : Type} {V : Type} (corecmpPartialEqInst : core.cmp.PartialEq K K)
  (corecmpOrdInst : core.cmp.Ord K) (corecloneCloneInst : core.clone.Clone K)
  (corecmpPartialEqInst1 : core.cmp.PartialEq V V) (LatticeInst :
  lattice.Lattice V) (self : lattice.MapL K V) (other : lattice.MapL K V) :
  Result Bool
  := do
  alloc.vec.partial_eq.PartialEqVec.eq (Pair.Insts.CoreCmpPartialEqPair
    corecmpPartialEqInst corecmpPartialEqInst1) self other

/-- Trait implementation: [lattice::lattice::{impl core::cmp::PartialEq<lattice::lattice::MapL<K, V>> for lattice::lattice::MapL<K, V>}]
    Source: 'lattice/src/lib.rs', lines 243:27-243:36 -/
@[reducible]
impl_def lattice.MapL.Insts.CoreCmpPartialEqMapL {K : Type} {V : Type}
  (corecmpPartialEqInst : core.cmp.PartialEq K K) (corecmpOrdInst :
  core.cmp.Ord K) (corecloneCloneInst : core.clone.Clone K)
  (corecmpPartialEqInst1 : core.cmp.PartialEq V V) (LatticeInst :
  lattice.Lattice V) : core.cmp.PartialEq (lattice.MapL K V) (lattice.MapL K V)
  := {
  eq := lattice.MapL.Insts.CoreCmpPartialEqMapL.eq corecmpPartialEqInst
    corecmpOrdInst corecloneCloneInst corecmpPartialEqInst1 LatticeInst
  ne := core.cmp.PartialEq.ne.trait_default
    (lattice.MapL.Insts.CoreCmpPartialEqMapL corecmpPartialEqInst
    corecmpOrdInst corecloneCloneInst corecmpPartialEqInst1 LatticeInst)
}

/-- [lattice::lattice::{impl core::cmp::Eq for lattice::lattice::MapL<K, V>}::assert_fields_are_eq]:
    Source: 'lattice/src/lib.rs', lines 243:38-243:40
    Visibility: public -/
def lattice.MapL.Insts.CoreCmpEq.assert_fields_are_eq
  {K : Type} {V : Type} (corecmpEqInst : core.cmp.Eq K) (corecmpOrdInst :
  core.cmp.Ord K) (corecloneCloneInst : core.clone.Clone K) (corecmpEqInst1 :
  core.cmp.Eq V) (LatticeInst : lattice.Lattice V) (self : lattice.MapL K V) :
  Result Unit
  := do
  ok ()

/-- Trait implementation: [lattice::lattice::{impl core::cmp::Eq for lattice::lattice::MapL<K, V>}]
    Source: 'lattice/src/lib.rs', lines 243:38-243:40 -/
@[reducible]
def lattice.MapL.Insts.CoreCmpEq {K : Type} {V : Type} (corecmpEqInst :
  core.cmp.Eq K) (corecmpOrdInst : core.cmp.Ord K) (corecloneCloneInst :
  core.clone.Clone K) (corecmpEqInst1 : core.cmp.Eq V) (LatticeInst :
  lattice.Lattice V) : core.cmp.Eq (lattice.MapL K V) := {
  partialEqInst := lattice.MapL.Insts.CoreCmpPartialEqMapL
    corecmpEqInst.partialEqInst corecmpOrdInst corecloneCloneInst
    corecmpEqInst1.partialEqInst LatticeInst
  assert_fields_are_eq := lattice.MapL.Insts.CoreCmpEq.assert_fields_are_eq
    corecmpEqInst corecmpOrdInst corecloneCloneInst corecmpEqInst1 LatticeInst
}

/-- [lattice::lattice::{impl core::default::Default for lattice::lattice::MapL<K, V>}::default]:
    Source: 'lattice/src/lib.rs', lines 247:8-249:9
    Visibility: public -/
def lattice.MapL.Insts.CoreDefaultDefault.default
  {K : Type} {V : Type} (corecmpOrdInst : core.cmp.Ord K) (corecloneCloneInst :
  core.clone.Clone K) (LatticeInst : lattice.Lattice V) :
  Result (lattice.MapL K V)
  := do
  ok (alloc.vec.Vec.new (K × V))

/-- Trait implementation: [lattice::lattice::{impl core::default::Default for lattice::lattice::MapL<K, V>}]
    Source: 'lattice/src/lib.rs', lines 246:4-250:5 -/
@[reducible]
def lattice.MapL.Insts.CoreDefaultDefault {K : Type} {V : Type} (corecmpOrdInst
  : core.cmp.Ord K) (corecloneCloneInst : core.clone.Clone K) (LatticeInst :
  lattice.Lattice V) : core.default.Default (lattice.MapL K V) := {
  default := lattice.MapL.Insts.CoreDefaultDefault.default corecmpOrdInst
    corecloneCloneInst LatticeInst
}

/-- [lattice::lattice::{lattice::lattice::MapL<K, V>}::get]: loop body 0:
    Source: 'lattice/src/lib.rs', lines 257:12-264:9
    Visibility: public -/
@[rust_loop_body]
def lattice.MapL.get_loop.body
  {K : Type} {V : Type} (corecmpOrdInst : core.cmp.Ord K) (LatticeInst :
  lattice.Lattice V) (k : K) (self : lattice.MapL K V) (i : Std.Usize) :
  Result (ControlFlow ((lattice.MapL K V) × Std.Usize) V)
  := do
  let i1 := alloc.vec.Vec.len self
  if i < i1
  then
    let (t, t1) ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (K × V)) self
        i
    let b ← corecmpOrdInst.eqInst.partialEqInst.eq t k
    if b
    then let t2 ← LatticeInst.corecloneCloneInst.clone t1
         ok (done t2)
    else let i2 ← i + 1#usize
         ok (cont (self, i2))
  else let t ← LatticeInst.bottom
       ok (done t)

/-- [lattice::lattice::{lattice::lattice::MapL<K, V>}::get]: loop 0:
    Source: 'lattice/src/lib.rs', lines 257:12-264:9
    Visibility: public -/
@[rust_loop]
def lattice.MapL.get_loop
  {K : Type} {V : Type} (corecmpOrdInst : core.cmp.Ord K) (LatticeInst :
  lattice.Lattice V) (self : lattice.MapL K V) (k : K) (i : Std.Usize) :
  Result V
  := do
  loop
    (fun (self1, i1) => lattice.MapL.get_loop.body corecmpOrdInst LatticeInst k
      self1 i1)
    (self, i)

/-- [lattice::lattice::{lattice::lattice::MapL<K, V>}::get]:
    Source: 'lattice/src/lib.rs', lines 255:8-264:9
    Visibility: public -/
@[reducible]
def lattice.MapL.get
  {K : Type} {V : Type} (corecmpOrdInst : core.cmp.Ord K) (corecloneCloneInst :
  core.clone.Clone K) (LatticeInst : lattice.Lattice V)
  (self : lattice.MapL K V) (k : K) :
  Result V
  := do
  lattice.MapL.get_loop corecmpOrdInst LatticeInst self k 0#usize

/-- [lattice::lattice::{lattice::lattice::MapL<K, V>}::insert]: loop body 0:
    Source: 'lattice/src/lib.rs', lines 1:0-289:9
    Visibility: public -/
@[rust_loop_body]
def lattice.MapL.insert_loop.body
  {K : Type} {V : Type} (corecmpOrdInst : core.cmp.Ord K) (corecloneCloneInst :
  core.clone.Clone K) (LatticeInst : lattice.Lattice V) (k : K) (v : V)
  (self : lattice.MapL K V) (i : Std.Usize) :
  Result (ControlFlow ((lattice.MapL K V) × Std.Usize) (alloc.vec.Vec (K ×
    V)))
  := do
  let i1 := alloc.vec.Vec.len self
  if i < i1
  then
    let (t, _) ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (K × V)) self
        i
    let b ← corecmpOrdInst.eqInst.partialEqInst.eq t k
    if b
    then
      let t1 ← LatticeInst.bottom
      let b1 ← LatticeInst.corecmpEqInst.partialEqInst.eq v t1
      if b1
      then let (_, v1) ← alloc.vec.Vec.remove Global self i
           ok (done v1)
      else
        let ((t2, _), index_mut_back) ←
          alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice (K ×
            V)) self i
        let v1 := index_mut_back (t2, v)
        ok (done v1)
    else
      let b1 ← corecmpOrdInst.partialOrdInst.lt k t
      if b1
      then
        let t1 ← LatticeInst.bottom
        let b2 ← LatticeInst.corecmpEqInst.partialEqInst.ne v t1
        if b2
        then let v1 ← alloc.vec.Vec.insert self i (k, v)
             ok (done v1)
        else ok (done self)
      else let i2 ← i + 1#usize
           ok (cont (self, i2))
  else
    let t ← LatticeInst.bottom
    let b ← LatticeInst.corecmpEqInst.partialEqInst.ne v t
    if b
    then let v1 ← alloc.vec.Vec.push self (k, v)
         ok (done v1)
    else ok (done self)

/-- [lattice::lattice::{lattice::lattice::MapL<K, V>}::insert]: loop 0:
    Source: 'lattice/src/lib.rs', lines 1:0-289:9
    Visibility: public -/
@[rust_loop]
def lattice.MapL.insert_loop
  {K : Type} {V : Type} (corecmpOrdInst : core.cmp.Ord K) (corecloneCloneInst :
  core.clone.Clone K) (LatticeInst : lattice.Lattice V)
  (self : lattice.MapL K V) (k : K) (v : V) (i : Std.Usize) :
  Result (alloc.vec.Vec (K × V))
  := do
  loop
    (fun (self1, i1) => lattice.MapL.insert_loop.body corecmpOrdInst
      corecloneCloneInst LatticeInst k v self1 i1)
    (self, i)

/-- [lattice::lattice::{lattice::lattice::MapL<K, V>}::insert]:
    Source: 'lattice/src/lib.rs', lines 267:8-289:9
    Visibility: public -/
def lattice.MapL.insert
  {K : Type} {V : Type} (corecmpOrdInst : core.cmp.Ord K) (corecloneCloneInst :
  core.clone.Clone K) (LatticeInst : lattice.Lattice V)
  (self : lattice.MapL K V) (k : K) (v : V) :
  Result (lattice.MapL K V)
  := do
  let v1 ←
    lattice.MapL.insert_loop corecmpOrdInst corecloneCloneInst LatticeInst self
      k v 0#usize
  ok v1

/-- [lattice::lattice::{lattice::lattice::MapL<K, V>}::has_key]: loop body 0:
    Source: 'lattice/src/lib.rs', lines 338:12-345:9 -/
@[rust_loop_body]
def lattice.MapL.has_key_loop.body
  {K : Type} {V : Type} (corecmpOrdInst : core.cmp.Ord K) (k : K)
  (self : lattice.MapL K V) (i : Std.Usize) :
  Result (ControlFlow ((lattice.MapL K V) × Std.Usize) Bool)
  := do
  let i1 := alloc.vec.Vec.len self
  if i < i1
  then
    let (t, _) ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (K × V)) self
        i
    let b ← corecmpOrdInst.eqInst.partialEqInst.eq t k
    if b
    then ok (done true)
    else let i2 ← i + 1#usize
         ok (cont (self, i2))
  else ok (done false)

/-- [lattice::lattice::{lattice::lattice::MapL<K, V>}::has_key]: loop 0:
    Source: 'lattice/src/lib.rs', lines 338:12-345:9 -/
@[rust_loop]
def lattice.MapL.has_key_loop
  {K : Type} {V : Type} (corecmpOrdInst : core.cmp.Ord K)
  (self : lattice.MapL K V) (k : K) (i : Std.Usize) :
  Result Bool
  := do
  loop
    (fun (self1, i1) => lattice.MapL.has_key_loop.body corecmpOrdInst k self1
      i1)
    (self, i)

/-- [lattice::lattice::{lattice::lattice::MapL<K, V>}::has_key]:
    Source: 'lattice/src/lib.rs', lines 336:8-345:9 -/
@[reducible]
def lattice.MapL.has_key
  {K : Type} {V : Type} (corecmpOrdInst : core.cmp.Ord K) (corecloneCloneInst :
  core.clone.Clone K) (LatticeInst : lattice.Lattice V)
  (self : lattice.MapL K V) (k : K) :
  Result Bool
  := do
  lattice.MapL.has_key_loop corecmpOrdInst self k 0#usize

/-- [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::MapL<K, V>}::meet]: loop body 0:
    Source: 'lattice/src/lib.rs', lines 319:12-326:13
    Visibility: public -/
@[rust_loop_body]
def lattice.MapL.Insts.LatticeLatticeLattice.meet_loop.body
  {K : Type} {V : Type} (corecmpOrdInst : core.cmp.Ord K) (corecloneCloneInst :
  core.clone.Clone K) (LatticeInst : lattice.Lattice V)
  (other : lattice.MapL K V) (self : lattice.MapL K V) (out : lattice.MapL K V)
  (i : Std.Usize) :
  Result (ControlFlow ((lattice.MapL K V) × (lattice.MapL K V) × Std.Usize)
    (lattice.MapL K V))
  := do
  let i1 := alloc.vec.Vec.len self
  if i < i1
  then
    let (t, t1) ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (K × V)) self
        i
    let k ← corecloneCloneInst.clone t
    let b ←
      lattice.MapL.has_key corecmpOrdInst corecloneCloneInst LatticeInst other
        k
    let out1 ←
      if b
      then
        do
        let t2 ←
          lattice.MapL.get corecmpOrdInst corecloneCloneInst LatticeInst other
            k
        let m ← LatticeInst.meet t1 t2
        lattice.MapL.insert corecmpOrdInst corecloneCloneInst LatticeInst out k
          m
      else ok out
    let i2 ← i + 1#usize
    ok (cont (self, out1, i2))
  else ok (done out)

/-- [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::MapL<K, V>}::meet]: loop 0:
    Source: 'lattice/src/lib.rs', lines 319:12-326:13
    Visibility: public -/
@[rust_loop]
def lattice.MapL.Insts.LatticeLatticeLattice.meet_loop
  {K : Type} {V : Type} (corecmpOrdInst : core.cmp.Ord K) (corecloneCloneInst :
  core.clone.Clone K) (LatticeInst : lattice.Lattice V)
  (self : lattice.MapL K V) (other : lattice.MapL K V) (out : lattice.MapL K V)
  (i : Std.Usize) :
  Result (lattice.MapL K V)
  := do
  loop
    (fun (self1, out1, i1) =>
      lattice.MapL.Insts.LatticeLatticeLattice.meet_loop.body corecmpOrdInst
      corecloneCloneInst LatticeInst other self1 out1 i1)
    (self, out, i)

/-- [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::MapL<K, V>}::meet]:
    Source: 'lattice/src/lib.rs', lines 312:8-328:9
    Visibility: public -/
def lattice.MapL.Insts.LatticeLatticeLattice.meet
  {K : Type} {V : Type} (corecmpOrdInst : core.cmp.Ord K) (corecloneCloneInst :
  core.clone.Clone K) (LatticeInst : lattice.Lattice V)
  (self : lattice.MapL K V) (other : lattice.MapL K V) :
  Result (lattice.MapL K V)
  := do
  let out ←
    lattice.MapL.Insts.CoreDefaultDefault.default corecmpOrdInst
      corecloneCloneInst LatticeInst
  lattice.MapL.Insts.LatticeLatticeLattice.meet_loop corecmpOrdInst
    corecloneCloneInst LatticeInst self other out 0#usize

/-- [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::MapL<K, V>}::join]: loop body 0:
    Source: 'lattice/src/lib.rs', lines 304:12-309:13
    Visibility: public -/
@[rust_loop_body]
def lattice.MapL.Insts.LatticeLatticeLattice.join_loop.body
  {K : Type} {V : Type} (corecmpOrdInst : core.cmp.Ord K) (corecloneCloneInst :
  core.clone.Clone K) (LatticeInst : lattice.Lattice V)
  (other : lattice.MapL K V) (out : lattice.MapL K V) (i : Std.Usize) :
  Result (ControlFlow ((lattice.MapL K V) × (lattice.MapL K V) × Std.Usize)
    (lattice.MapL K V))
  := do
  let i1 := alloc.vec.Vec.len other
  if i < i1
  then
    let (t, t1) ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (K × V))
        other i
    let k ← corecloneCloneInst.clone t
    let t2 ←
      lattice.MapL.get corecmpOrdInst corecloneCloneInst LatticeInst out k
    let joined ← LatticeInst.join t2 t1
    let out1 ←
      lattice.MapL.insert corecmpOrdInst corecloneCloneInst LatticeInst out k
        joined
    let i2 ← i + 1#usize
    ok (cont (other, out1, i2))
  else ok (done out)

/-- [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::MapL<K, V>}::join]: loop 0:
    Source: 'lattice/src/lib.rs', lines 304:12-309:13
    Visibility: public -/
@[rust_loop]
def lattice.MapL.Insts.LatticeLatticeLattice.join_loop
  {K : Type} {V : Type} (corecmpOrdInst : core.cmp.Ord K) (corecloneCloneInst :
  core.clone.Clone K) (LatticeInst : lattice.Lattice V)
  (other : lattice.MapL K V) (out : lattice.MapL K V) (i : Std.Usize) :
  Result (lattice.MapL K V)
  := do
  loop
    (fun (other1, out1, i1) =>
      lattice.MapL.Insts.LatticeLatticeLattice.join_loop.body corecmpOrdInst
      corecloneCloneInst LatticeInst other1 out1 i1)
    (other, out, i)

/-- [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::MapL<K, V>}::join]:
    Source: 'lattice/src/lib.rs', lines 301:8-311:9
    Visibility: public -/
def lattice.MapL.Insts.LatticeLatticeLattice.join
  {K : Type} {V : Type} (corecmpOrdInst : core.cmp.Ord K) (corecloneCloneInst :
  core.clone.Clone K) (LatticeInst : lattice.Lattice V)
  (self : lattice.MapL K V) (other : lattice.MapL K V) :
  Result (lattice.MapL K V)
  := do
  let out ←
    lattice.MapL.Insts.CoreCloneClone.clone corecloneCloneInst corecmpOrdInst
      corecloneCloneInst LatticeInst.corecloneCloneInst LatticeInst self
  lattice.MapL.Insts.LatticeLatticeLattice.join_loop corecmpOrdInst
    corecloneCloneInst LatticeInst other out 0#usize

/-- [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::MapL<K, V>}::bottom]:
    Source: 'lattice/src/lib.rs', lines 298:8-300:9
    Visibility: public -/
def lattice.MapL.Insts.LatticeLatticeLattice.bottom
  {K : Type} {V : Type} (corecmpOrdInst : core.cmp.Ord K) (corecloneCloneInst :
  core.clone.Clone K) (LatticeInst : lattice.Lattice V) :
  Result (lattice.MapL K V)
  := do
  ok (alloc.vec.Vec.new (K × V))

/-- Trait implementation: [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::MapL<K, V>}]
    Source: 'lattice/src/lib.rs', lines 297:4-329:5 -/
@[reducible]
impl_def lattice.MapL.Insts.LatticeLatticeLattice {K : Type} {V : Type}
  (corecmpOrdInst : core.cmp.Ord K) (corecloneCloneInst1 : core.clone.Clone K)
  (LatticeInst : lattice.Lattice V) : lattice.Lattice (lattice.MapL K V) := {
  corecloneCloneInst := lattice.MapL.Insts.CoreCloneClone corecloneCloneInst1
    corecmpOrdInst corecloneCloneInst1 LatticeInst.corecloneCloneInst
    LatticeInst
  corecmpEqInst := lattice.MapL.Insts.CoreCmpEq corecmpOrdInst.eqInst
    corecmpOrdInst corecloneCloneInst1 LatticeInst.corecmpEqInst LatticeInst
  bottom := lattice.MapL.Insts.LatticeLatticeLattice.bottom corecmpOrdInst
    corecloneCloneInst1 LatticeInst
  join := lattice.MapL.Insts.LatticeLatticeLattice.join corecmpOrdInst
    corecloneCloneInst1 LatticeInst
  meet := lattice.MapL.Insts.LatticeLatticeLattice.meet corecmpOrdInst
    corecloneCloneInst1 LatticeInst
  leq := lattice.Lattice.leq.default (lattice.MapL.Insts.LatticeLatticeLattice
    corecmpOrdInst corecloneCloneInst1 LatticeInst)
}

/-- [lattice::lattice::{impl core::fmt::Debug for lattice::lattice::May<L>}::fmt]:
    Source: 'lattice/src/lib.rs', lines 352:13-352:18
    Visibility: public -/
def lattice.May.Insts.CoreFmtDebug.fmt
  {L : Type} (corefmtDebugInst : core.fmt.Debug L) (self : lattice.May L)
  (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ (core.fmt.DebugShared corefmtDebugInst) self
  core.fmt.Formatter.debug_tuple_field1_finish f (toStr "May") dyn

/-- Trait implementation: [lattice::lattice::{impl core::fmt::Debug for lattice::lattice::May<L>}]
    Source: 'lattice/src/lib.rs', lines 352:13-352:18 -/
@[reducible]
def lattice.May.Insts.CoreFmtDebug {L : Type} (corefmtDebugInst :
  core.fmt.Debug L) : core.fmt.Debug (lattice.May L) := {
  fmt := lattice.May.Insts.CoreFmtDebug.fmt corefmtDebugInst
}

/-- [lattice::lattice::{impl core::clone::Clone for lattice::lattice::May<L>}::clone]:
    Source: 'lattice/src/lib.rs', lines 352:20-352:25
    Visibility: public -/
def lattice.May.Insts.CoreCloneClone.clone
  {L : Type} (corecloneCloneInst : core.clone.Clone L) (self : lattice.May L) :
  Result (lattice.May L)
  := do
  let t ← corecloneCloneInst.clone self
  ok t

/-- Trait implementation: [lattice::lattice::{impl core::clone::Clone for lattice::lattice::May<L>}]
    Source: 'lattice/src/lib.rs', lines 352:20-352:25 -/
@[reducible]
def lattice.May.Insts.CoreCloneClone {L : Type} (corecloneCloneInst :
  core.clone.Clone L) : core.clone.Clone (lattice.May L) := {
  clone := lattice.May.Insts.CoreCloneClone.clone corecloneCloneInst
}

/-- Trait implementation: [lattice::lattice::{impl core::marker::StructuralPartialEq for lattice::lattice::May<L>}]
    Source: 'lattice/src/lib.rs', lines 352:27-352:36 -/
@[reducible]
def lattice.May.Insts.CoreMarkerStructuralPartialEq (L : Type) :
  core.marker.StructuralPartialEq (lattice.May L) := {
}

/-- [lattice::lattice::{impl core::cmp::PartialEq<lattice::lattice::May<L>> for lattice::lattice::May<L>}::eq]:
    Source: 'lattice/src/lib.rs', lines 352:27-352:36
    Visibility: public -/
def lattice.May.Insts.CoreCmpPartialEqMay.eq
  {L : Type} (corecmpPartialEqInst : core.cmp.PartialEq L L)
  (self : lattice.May L) (other : lattice.May L) :
  Result Bool
  := do
  corecmpPartialEqInst.eq self other

/-- Trait implementation: [lattice::lattice::{impl core::cmp::PartialEq<lattice::lattice::May<L>> for lattice::lattice::May<L>}]
    Source: 'lattice/src/lib.rs', lines 352:27-352:36 -/
@[reducible]
impl_def lattice.May.Insts.CoreCmpPartialEqMay {L : Type} (corecmpPartialEqInst
  : core.cmp.PartialEq L L) : core.cmp.PartialEq (lattice.May L) (lattice.May
  L) := {
  eq := lattice.May.Insts.CoreCmpPartialEqMay.eq corecmpPartialEqInst
  ne := core.cmp.PartialEq.ne.trait_default
    (lattice.May.Insts.CoreCmpPartialEqMay corecmpPartialEqInst)
}

/-- [lattice::lattice::{impl core::cmp::Eq for lattice::lattice::May<L>}::assert_fields_are_eq]:
    Source: 'lattice/src/lib.rs', lines 352:38-352:40
    Visibility: public -/
def lattice.May.Insts.CoreCmpEq.assert_fields_are_eq
  {L : Type} (corecmpEqInst : core.cmp.Eq L) (self : lattice.May L) :
  Result Unit
  := do
  ok ()

/-- Trait implementation: [lattice::lattice::{impl core::cmp::Eq for lattice::lattice::May<L>}]
    Source: 'lattice/src/lib.rs', lines 352:38-352:40 -/
@[reducible]
def lattice.May.Insts.CoreCmpEq {L : Type} (corecmpEqInst : core.cmp.Eq L) :
  core.cmp.Eq (lattice.May L) := {
  partialEqInst := lattice.May.Insts.CoreCmpPartialEqMay
    corecmpEqInst.partialEqInst
  assert_fields_are_eq := lattice.May.Insts.CoreCmpEq.assert_fields_are_eq
    corecmpEqInst
}

/-- [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::May<L>}::meet]:
    Source: 'lattice/src/lib.rs', lines 362:8-364:9
    Visibility: public -/
def lattice.May.Insts.LatticeLatticeLattice.meet
  {L : Type} (LatticeInst : lattice.Lattice L) (self : lattice.May L)
  (other : lattice.May L) :
  Result (lattice.May L)
  := do
  let t ← LatticeInst.meet self other
  ok t

/-- [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::May<L>}::join]:
    Source: 'lattice/src/lib.rs', lines 359:8-361:9
    Visibility: public -/
def lattice.May.Insts.LatticeLatticeLattice.join
  {L : Type} (LatticeInst : lattice.Lattice L) (self : lattice.May L)
  (other : lattice.May L) :
  Result (lattice.May L)
  := do
  let t ← LatticeInst.join self other
  ok t

/-- [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::May<L>}::bottom]:
    Source: 'lattice/src/lib.rs', lines 356:8-358:9
    Visibility: public -/
def lattice.May.Insts.LatticeLatticeLattice.bottom
  {L : Type} (LatticeInst : lattice.Lattice L) : Result (lattice.May L) := do
  let t ← LatticeInst.bottom
  ok t

/-- Trait implementation: [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::May<L>}]
    Source: 'lattice/src/lib.rs', lines 355:4-365:5 -/
@[reducible]
impl_def lattice.May.Insts.LatticeLatticeLattice {L : Type} (LatticeInst :
  lattice.Lattice L) : lattice.Lattice (lattice.May L) := {
  corecloneCloneInst := lattice.May.Insts.CoreCloneClone
    LatticeInst.corecloneCloneInst
  corecmpEqInst := lattice.May.Insts.CoreCmpEq LatticeInst.corecmpEqInst
  bottom := lattice.May.Insts.LatticeLatticeLattice.bottom LatticeInst
  join := lattice.May.Insts.LatticeLatticeLattice.join LatticeInst
  meet := lattice.May.Insts.LatticeLatticeLattice.meet LatticeInst
  leq := lattice.Lattice.leq.default (lattice.May.Insts.LatticeLatticeLattice
    LatticeInst)
}

/-- [lattice::lattice::{impl lattice::lattice::BoundedLattice for lattice::lattice::May<L>}::top]:
    Source: 'lattice/src/lib.rs', lines 368:8-370:9
    Visibility: public -/
def lattice.May.Insts.LatticeLatticeBoundedLattice.top
  {L : Type} (BoundedLatticeInst : lattice.BoundedLattice L) :
  Result (lattice.May L)
  := do
  let t ← BoundedLatticeInst.top
  ok t

/-- Trait implementation: [lattice::lattice::{impl lattice::lattice::BoundedLattice for lattice::lattice::May<L>}]
    Source: 'lattice/src/lib.rs', lines 367:4-371:5 -/
@[reducible]
def lattice.May.Insts.LatticeLatticeBoundedLattice {L : Type}
  (BoundedLatticeInst : lattice.BoundedLattice L) : lattice.BoundedLattice
  (lattice.May L) := {
  LatticeInst := lattice.May.Insts.LatticeLatticeLattice
    BoundedLatticeInst.LatticeInst
  top := lattice.May.Insts.LatticeLatticeBoundedLattice.top BoundedLatticeInst
}

/-- [lattice::lattice::{impl core::fmt::Debug for lattice::lattice::Must<L>}::fmt]:
    Source: 'lattice/src/lib.rs', lines 389:13-389:18
    Visibility: public -/
def lattice.Must.Insts.CoreFmtDebug.fmt
  {L : Type} (corefmtDebugInst : core.fmt.Debug L) (self : lattice.Must L)
  (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ (core.fmt.DebugShared corefmtDebugInst) self
  core.fmt.Formatter.debug_tuple_field1_finish f (toStr "Must") dyn

/-- Trait implementation: [lattice::lattice::{impl core::fmt::Debug for lattice::lattice::Must<L>}]
    Source: 'lattice/src/lib.rs', lines 389:13-389:18 -/
@[reducible]
def lattice.Must.Insts.CoreFmtDebug {L : Type} (corefmtDebugInst :
  core.fmt.Debug L) : core.fmt.Debug (lattice.Must L) := {
  fmt := lattice.Must.Insts.CoreFmtDebug.fmt corefmtDebugInst
}

/-- [lattice::lattice::{impl core::clone::Clone for lattice::lattice::Must<L>}::clone]:
    Source: 'lattice/src/lib.rs', lines 389:20-389:25
    Visibility: public -/
def lattice.Must.Insts.CoreCloneClone.clone
  {L : Type} (corecloneCloneInst : core.clone.Clone L) (self : lattice.Must L)
  :
  Result (lattice.Must L)
  := do
  let t ← corecloneCloneInst.clone self
  ok t

/-- Trait implementation: [lattice::lattice::{impl core::clone::Clone for lattice::lattice::Must<L>}]
    Source: 'lattice/src/lib.rs', lines 389:20-389:25 -/
@[reducible]
def lattice.Must.Insts.CoreCloneClone {L : Type} (corecloneCloneInst :
  core.clone.Clone L) : core.clone.Clone (lattice.Must L) := {
  clone := lattice.Must.Insts.CoreCloneClone.clone corecloneCloneInst
}

/-- Trait implementation: [lattice::lattice::{impl core::marker::StructuralPartialEq for lattice::lattice::Must<L>}]
    Source: 'lattice/src/lib.rs', lines 389:27-389:36 -/
@[reducible]
def lattice.Must.Insts.CoreMarkerStructuralPartialEq (L : Type) :
  core.marker.StructuralPartialEq (lattice.Must L) := {
}

/-- [lattice::lattice::{impl core::cmp::PartialEq<lattice::lattice::Must<L>> for lattice::lattice::Must<L>}::eq]:
    Source: 'lattice/src/lib.rs', lines 389:27-389:36
    Visibility: public -/
def lattice.Must.Insts.CoreCmpPartialEqMust.eq
  {L : Type} (corecmpPartialEqInst : core.cmp.PartialEq L L)
  (self : lattice.Must L) (other : lattice.Must L) :
  Result Bool
  := do
  corecmpPartialEqInst.eq self other

/-- Trait implementation: [lattice::lattice::{impl core::cmp::PartialEq<lattice::lattice::Must<L>> for lattice::lattice::Must<L>}]
    Source: 'lattice/src/lib.rs', lines 389:27-389:36 -/
@[reducible]
impl_def lattice.Must.Insts.CoreCmpPartialEqMust {L : Type}
  (corecmpPartialEqInst : core.cmp.PartialEq L L) : core.cmp.PartialEq
  (lattice.Must L) (lattice.Must L) := {
  eq := lattice.Must.Insts.CoreCmpPartialEqMust.eq corecmpPartialEqInst
  ne := core.cmp.PartialEq.ne.trait_default
    (lattice.Must.Insts.CoreCmpPartialEqMust corecmpPartialEqInst)
}

/-- [lattice::lattice::{impl core::cmp::Eq for lattice::lattice::Must<L>}::assert_fields_are_eq]:
    Source: 'lattice/src/lib.rs', lines 389:38-389:40
    Visibility: public -/
def lattice.Must.Insts.CoreCmpEq.assert_fields_are_eq
  {L : Type} (corecmpEqInst : core.cmp.Eq L) (self : lattice.Must L) :
  Result Unit
  := do
  ok ()

/-- Trait implementation: [lattice::lattice::{impl core::cmp::Eq for lattice::lattice::Must<L>}]
    Source: 'lattice/src/lib.rs', lines 389:38-389:40 -/
@[reducible]
def lattice.Must.Insts.CoreCmpEq {L : Type} (corecmpEqInst : core.cmp.Eq L) :
  core.cmp.Eq (lattice.Must L) := {
  partialEqInst := lattice.Must.Insts.CoreCmpPartialEqMust
    corecmpEqInst.partialEqInst
  assert_fields_are_eq := lattice.Must.Insts.CoreCmpEq.assert_fields_are_eq
    corecmpEqInst
}

/-- [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::Must<L>}::meet]:
    Source: 'lattice/src/lib.rs', lines 399:8-401:9
    Visibility: public -/
def lattice.Must.Insts.LatticeLatticeLattice.meet
  {L : Type} (BoundedLatticeInst : lattice.BoundedLattice L)
  (self : lattice.Must L) (other : lattice.Must L) :
  Result (lattice.Must L)
  := do
  let t ← BoundedLatticeInst.LatticeInst.join self other
  ok t

/-- [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::Must<L>}::join]:
    Source: 'lattice/src/lib.rs', lines 396:8-398:9
    Visibility: public -/
def lattice.Must.Insts.LatticeLatticeLattice.join
  {L : Type} (BoundedLatticeInst : lattice.BoundedLattice L)
  (self : lattice.Must L) (other : lattice.Must L) :
  Result (lattice.Must L)
  := do
  let t ← BoundedLatticeInst.LatticeInst.meet self other
  ok t

/-- [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::Must<L>}::bottom]:
    Source: 'lattice/src/lib.rs', lines 393:8-395:9
    Visibility: public -/
def lattice.Must.Insts.LatticeLatticeLattice.bottom
  {L : Type} (BoundedLatticeInst : lattice.BoundedLattice L) :
  Result (lattice.Must L)
  := do
  let t ← BoundedLatticeInst.top
  ok t

/-- Trait implementation: [lattice::lattice::{impl lattice::lattice::Lattice for lattice::lattice::Must<L>}]
    Source: 'lattice/src/lib.rs', lines 392:4-402:5 -/
@[reducible]
impl_def lattice.Must.Insts.LatticeLatticeLattice {L : Type}
  (BoundedLatticeInst : lattice.BoundedLattice L) : lattice.Lattice
  (lattice.Must L) := {
  corecloneCloneInst := lattice.Must.Insts.CoreCloneClone
    BoundedLatticeInst.LatticeInst.corecloneCloneInst
  corecmpEqInst := lattice.Must.Insts.CoreCmpEq
    BoundedLatticeInst.LatticeInst.corecmpEqInst
  bottom := lattice.Must.Insts.LatticeLatticeLattice.bottom BoundedLatticeInst
  join := lattice.Must.Insts.LatticeLatticeLattice.join BoundedLatticeInst
  meet := lattice.Must.Insts.LatticeLatticeLattice.meet BoundedLatticeInst
  leq := lattice.Lattice.leq.default (lattice.Must.Insts.LatticeLatticeLattice
    BoundedLatticeInst)
}

/-- [lattice::lattice::{impl lattice::lattice::BoundedLattice for lattice::lattice::Must<L>}::top]:
    Source: 'lattice/src/lib.rs', lines 405:8-407:9
    Visibility: public -/
def lattice.Must.Insts.LatticeLatticeBoundedLattice.top
  {L : Type} (BoundedLatticeInst : lattice.BoundedLattice L) :
  Result (lattice.Must L)
  := do
  let t ← BoundedLatticeInst.LatticeInst.bottom
  ok t

/-- Trait implementation: [lattice::lattice::{impl lattice::lattice::BoundedLattice for lattice::lattice::Must<L>}]
    Source: 'lattice/src/lib.rs', lines 404:4-408:5 -/
@[reducible]
def lattice.Must.Insts.LatticeLatticeBoundedLattice {L : Type}
  (BoundedLatticeInst : lattice.BoundedLattice L) : lattice.BoundedLattice
  (lattice.Must L) := {
  LatticeInst := lattice.Must.Insts.LatticeLatticeLattice BoundedLatticeInst
  top := lattice.Must.Insts.LatticeLatticeBoundedLattice.top BoundedLatticeInst
}

/-- [lattice::solve::{impl core::fmt::Debug for lattice::solve::Direction}::fmt]:
    Source: 'lattice/src/lib.rs', lines 448:13-448:18
    Visibility: public -/
def solve.Direction.Insts.CoreFmtDebug.fmt
  (self : solve.Direction) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | solve.Direction.Forward => core.fmt.Formatter.write_str f (toStr "Forward")
  | solve.Direction.Backward =>
    core.fmt.Formatter.write_str f (toStr "Backward")

/-- Trait implementation: [lattice::solve::{impl core::fmt::Debug for lattice::solve::Direction}]
    Source: 'lattice/src/lib.rs', lines 448:13-448:18 -/
@[reducible]
def solve.Direction.Insts.CoreFmtDebug : core.fmt.Debug solve.Direction := {
  fmt := solve.Direction.Insts.CoreFmtDebug.fmt
}

/-- [lattice::solve::{impl core::clone::Clone for lattice::solve::Direction}::clone]:
    Source: 'lattice/src/lib.rs', lines 448:20-448:25
    Visibility: public -/
def solve.Direction.Insts.CoreCloneClone.clone
  (self : solve.Direction) : Result solve.Direction := do
  ok self

/-- Trait implementation: [lattice::solve::{impl core::clone::Clone for lattice::solve::Direction}]
    Source: 'lattice/src/lib.rs', lines 448:20-448:25 -/
@[reducible]
def solve.Direction.Insts.CoreCloneClone : core.clone.Clone solve.Direction
  := {
  clone := solve.Direction.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [lattice::solve::{impl core::marker::Copy for lattice::solve::Direction}]
    Source: 'lattice/src/lib.rs', lines 448:27-448:31 -/
@[reducible]
def solve.Direction.Insts.CoreMarkerCopy : core.marker.Copy solve.Direction
  := {
  cloneInst := solve.Direction.Insts.CoreCloneClone
}

/-- Trait implementation: [lattice::solve::{impl core::marker::StructuralPartialEq for lattice::solve::Direction}]
    Source: 'lattice/src/lib.rs', lines 448:33-448:42 -/
@[reducible]
def solve.Direction.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq solve.Direction := {
}

/-- [lattice::solve::{impl core::cmp::PartialEq<lattice::solve::Direction> for lattice::solve::Direction}::eq]:
    Source: 'lattice/src/lib.rs', lines 448:33-448:42
    Visibility: public -/
def solve.Direction.Insts.CoreCmpPartialEqDirection.eq
  (self : solve.Direction) (other : solve.Direction) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [lattice::solve::{impl core::cmp::PartialEq<lattice::solve::Direction> for lattice::solve::Direction}]
    Source: 'lattice/src/lib.rs', lines 448:33-448:42 -/
@[reducible]
impl_def solve.Direction.Insts.CoreCmpPartialEqDirection : core.cmp.PartialEq
  solve.Direction solve.Direction := {
  eq := solve.Direction.Insts.CoreCmpPartialEqDirection.eq
  ne := core.cmp.PartialEq.ne.trait_default
    solve.Direction.Insts.CoreCmpPartialEqDirection
}

/-- [lattice::solve::{impl core::cmp::Eq for lattice::solve::Direction}::assert_fields_are_eq]:
    Source: 'lattice/src/lib.rs', lines 448:44-448:46
    Visibility: public -/
def solve.Direction.Insts.CoreCmpEq.assert_fields_are_eq
  (self : solve.Direction) : Result Unit := do
  ok ()

/-- Trait implementation: [lattice::solve::{impl core::cmp::Eq for lattice::solve::Direction}]
    Source: 'lattice/src/lib.rs', lines 448:44-448:46 -/
@[reducible]
def solve.Direction.Insts.CoreCmpEq : core.cmp.Eq solve.Direction := {
  partialEqInst := solve.Direction.Insts.CoreCmpPartialEqDirection
  assert_fields_are_eq := solve.Direction.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [lattice::solve::{impl core::fmt::Debug for lattice::solve::Solution<L>}::fmt]:
    Source: 'lattice/src/lib.rs', lines 462:13-462:18
    Visibility: public -/
def solve.Solution.Insts.CoreFmtDebug.fmt
  {L : Type} (corefmtDebugInst : core.fmt.Debug L) (self : solve.Solution L)
  (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ (core.fmt.DebugVec corefmtDebugInst) self.states
  let dyn1 := Dyn.mk _ core.fmt.DebugBool self.converged
  let dyn2 := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugUsize) self.rounds
  core.fmt.Formatter.debug_struct_field3_finish f (toStr "Solution") (toStr
    "states") dyn (toStr "converged") dyn1 (toStr "rounds") dyn2

/-- Trait implementation: [lattice::solve::{impl core::fmt::Debug for lattice::solve::Solution<L>}]
    Source: 'lattice/src/lib.rs', lines 462:13-462:18 -/
@[reducible]
def solve.Solution.Insts.CoreFmtDebug {L : Type} (corefmtDebugInst :
  core.fmt.Debug L) : core.fmt.Debug (solve.Solution L) := {
  fmt := solve.Solution.Insts.CoreFmtDebug.fmt corefmtDebugInst
}

/-- [lattice::solve::{impl core::clone::Clone for lattice::solve::Solution<L>}::clone]:
    Source: 'lattice/src/lib.rs', lines 462:20-462:25
    Visibility: public -/
def solve.Solution.Insts.CoreCloneClone.clone
  {L : Type} (corecloneCloneInst : core.clone.Clone L)
  (self : solve.Solution L) :
  Result (solve.Solution L)
  := do
  let v ← alloc.vec.CloneVec.clone corecloneCloneInst self.states
  let b ← lift (core.clone.impls.CloneBool.clone self.converged)
  let i ← lift (core.clone.impls.CloneUsize.clone self.rounds)
  ok { states := v, converged := b, rounds := i }

/-- Trait implementation: [lattice::solve::{impl core::clone::Clone for lattice::solve::Solution<L>}]
    Source: 'lattice/src/lib.rs', lines 462:20-462:25 -/
@[reducible]
def solve.Solution.Insts.CoreCloneClone {L : Type} (corecloneCloneInst :
  core.clone.Clone L) : core.clone.Clone (solve.Solution L) := {
  clone := solve.Solution.Insts.CoreCloneClone.clone corecloneCloneInst
}

/-- Trait implementation: [lattice::solve::{impl core::marker::StructuralPartialEq for lattice::solve::Solution<L>}]
    Source: 'lattice/src/lib.rs', lines 462:27-462:36 -/
@[reducible]
def solve.Solution.Insts.CoreMarkerStructuralPartialEq (L : Type) :
  core.marker.StructuralPartialEq (solve.Solution L) := {
}

/-- [lattice::solve::{impl core::cmp::PartialEq<lattice::solve::Solution<L>> for lattice::solve::Solution<L>}::eq]:
    Source: 'lattice/src/lib.rs', lines 462:27-462:36
    Visibility: public -/
def solve.Solution.Insts.CoreCmpPartialEqSolution.eq
  {L : Type} (corecmpPartialEqInst : core.cmp.PartialEq L L)
  (self : solve.Solution L) (other : solve.Solution L) :
  Result Bool
  := do
  if self.converged = other.converged
  then
    let b ←
      alloc.vec.partial_eq.PartialEqVec.eq corecmpPartialEqInst self.states
        other.states
    if b
    then ok (self.rounds = other.rounds)
    else ok false
  else ok false

/-- Trait implementation: [lattice::solve::{impl core::cmp::PartialEq<lattice::solve::Solution<L>> for lattice::solve::Solution<L>}]
    Source: 'lattice/src/lib.rs', lines 462:27-462:36 -/
@[reducible]
impl_def solve.Solution.Insts.CoreCmpPartialEqSolution {L : Type}
  (corecmpPartialEqInst : core.cmp.PartialEq L L) : core.cmp.PartialEq
  (solve.Solution L) (solve.Solution L) := {
  eq := solve.Solution.Insts.CoreCmpPartialEqSolution.eq corecmpPartialEqInst
  ne := core.cmp.PartialEq.ne.trait_default
    (solve.Solution.Insts.CoreCmpPartialEqSolution corecmpPartialEqInst)
}

/-- [lattice::solve::{impl core::cmp::Eq for lattice::solve::Solution<L>}::assert_fields_are_eq]:
    Source: 'lattice/src/lib.rs', lines 462:38-462:40
    Visibility: public -/
def solve.Solution.Insts.CoreCmpEq.assert_fields_are_eq
  {L : Type} (corecmpEqInst : core.cmp.Eq L) (self : solve.Solution L) :
  Result Unit
  := do
  ok ()

/-- Trait implementation: [lattice::solve::{impl core::cmp::Eq for lattice::solve::Solution<L>}]
    Source: 'lattice/src/lib.rs', lines 462:38-462:40 -/
@[reducible]
def solve.Solution.Insts.CoreCmpEq {L : Type} (corecmpEqInst : core.cmp.Eq L) :
  core.cmp.Eq (solve.Solution L) := {
  partialEqInst := solve.Solution.Insts.CoreCmpPartialEqSolution
    corecmpEqInst.partialEqInst
  assert_fields_are_eq := solve.Solution.Insts.CoreCmpEq.assert_fields_are_eq
    corecmpEqInst
}

/-- [lattice::solve::flows_to]:
    Source: 'lattice/src/lib.rs', lines 568:4-573:5 -/
def solve.flows_to
  {G : Type} (GraphInst : solve.Graph G) (graph : G)
  (direction : solve.Direction) (v : Std.Usize) :
  Result (Slice Std.Usize)
  := do
  match direction with
  | solve.Direction.Forward => GraphInst.succ graph v
  | solve.Direction.Backward => GraphInst.pred graph v

/-- [lattice::solve::solve]: loop body 0:
    Source: 'lattice/src/lib.rs', lines 503:8-507:9
    Visibility: public -/
@[rust_loop_body]
def solve.solve_loop0.body
  {L : Type} (latticeLatticeInst : lattice.Lattice L) (n : Std.Usize)
  (state : alloc.vec.Vec L) (queued : alloc.vec.Vec Bool) (init : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec L) × (alloc.vec.Vec Bool) × Std.Usize)
    ((alloc.vec.Vec L) × (alloc.vec.Vec Bool)))
  := do
  if init < n
  then
    let t ← latticeLatticeInst.bottom
    let state1 ← alloc.vec.Vec.push state t
    let queued1 ← alloc.vec.Vec.push queued true
    let init1 ← init + 1#usize
    ok (cont (state1, queued1, init1))
  else ok (done (state, queued))

/-- [lattice::solve::solve]: loop 0:
    Source: 'lattice/src/lib.rs', lines 503:8-507:9
    Visibility: public -/
@[rust_loop]
def solve.solve_loop0
  {L : Type} (latticeLatticeInst : lattice.Lattice L) (n : Std.Usize)
  (state : alloc.vec.Vec L) (queued : alloc.vec.Vec Bool) (init : Std.Usize) :
  Result ((alloc.vec.Vec L) × (alloc.vec.Vec Bool))
  := do
  loop
    (fun (state1, queued1, init1) => solve.solve_loop0.body latticeLatticeInst
      n state1 queued1 init1)
    (state, queued, init)

/-- [lattice::solve::solve]: loop body 1:
    Source: 'lattice/src/lib.rs', lines 517:8-520:9
    Visibility: public -/
@[rust_loop_body]
def solve.solve_loop1.body
  (n : Std.Usize) (work : alloc.vec.Vec Std.Usize) (seed : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.Usize) × Std.Usize) (alloc.vec.Vec
    Std.Usize))
  := do
  if seed < n
  then
    let work1 ← alloc.vec.Vec.push work seed
    let seed1 ← seed + 1#usize
    ok (cont (work1, seed1))
  else ok (done work)

/-- [lattice::solve::solve]: loop 1:
    Source: 'lattice/src/lib.rs', lines 517:8-520:9
    Visibility: public -/
@[rust_loop]
def solve.solve_loop1
  (n : Std.Usize) (work : alloc.vec.Vec Std.Usize) (seed : Std.Usize) :
  Result (alloc.vec.Vec Std.Usize)
  := do
  loop
    (fun (work1, seed1) => solve.solve_loop1.body n work1 seed1)
    (work, seed)

/-- [lattice::solve::solve]: loop body 3:
    Source: 'lattice/src/lib.rs', lines 1:0-559:13
    Visibility: public -/
@[rust_loop_body]
def solve.solve_loop2_loop0.body
  {G : Type} {L : Type} (GraphInst : solve.Graph G) (latticeLatticeInst :
  lattice.Lattice L) (graph : G) (direction : solve.Direction) (n : Std.Usize)
  (v : Std.Usize) (out : L) (state : alloc.vec.Vec L)
  (queued : alloc.vec.Vec Bool) (work : alloc.vec.Vec Std.Usize)
  (e : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec L) × (alloc.vec.Vec Bool) ×
    (alloc.vec.Vec Std.Usize) × Std.Usize) ((alloc.vec.Vec L) ×
    (alloc.vec.Vec Bool) × (alloc.vec.Vec Std.Usize)))
  := do
  let s ← solve.flows_to GraphInst graph direction v
  let i := Slice.len s
  if e < i
  then
    let w ← Slice.index_usize s e
    let e1 ← e + 1#usize
    if w >= n
    then ok (cont (state, queued, work, e1))
    else
      let t ←
        alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice L) state w
      let joined ← latticeLatticeInst.join t out
      let b ← latticeLatticeInst.corecmpEqInst.partialEqInst.ne joined t
      if b
      then
        let t1 ← latticeLatticeInst.corecloneCloneInst.clone joined
        let (_, index_mut_back) ←
          alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice L)
            state w
        let b1 ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Bool)
            queued w
        if b1
        then
          let state1 := index_mut_back t1
          ok (cont (state1, queued, work, e1))
        else
          let (_, index_mut_back1) ←
            alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice
              Bool) queued w
          let work1 ← alloc.vec.Vec.push work w
          let queued1 := index_mut_back1 true
          let state1 := index_mut_back t1
          ok (cont (state1, queued1, work1, e1))
      else ok (cont (state, queued, work, e1))
  else ok (done (state, queued, work))

/-- [lattice::solve::solve]: loop 3:
    Source: 'lattice/src/lib.rs', lines 1:0-559:13
    Visibility: public -/
@[rust_loop]
def solve.solve_loop2_loop0
  {G : Type} {L : Type} (GraphInst : solve.Graph G) (latticeLatticeInst :
  lattice.Lattice L) (graph : G) (direction : solve.Direction) (n : Std.Usize)
  (state : alloc.vec.Vec L) (queued : alloc.vec.Vec Bool)
  (work : alloc.vec.Vec Std.Usize) (v : Std.Usize) (out : L) (e : Std.Usize) :
  Result ((alloc.vec.Vec L) × (alloc.vec.Vec Bool) × (alloc.vec.Vec
    Std.Usize))
  := do
  loop
    (fun (state1, queued1, work1, e1) => solve.solve_loop2_loop0.body GraphInst
      latticeLatticeInst graph direction n v out state1 queued1 work1 e1)
    (state, queued, work, e)

/-- [lattice::solve::solve]: loop body 2:
    Source: 'lattice/src/lib.rs', lines 1:0-560:9
    Visibility: public -/
@[rust_loop_body]
def solve.solve_loop2.body
  {G : Type} {L : Type} {T2 : Type} (GraphInst : solve.Graph G)
  (latticeLatticeInst : lattice.Lattice L)
  (coreopsfunctionFnT2PairUsizeSharedLLInst : core.ops.function.Fn T2
  (Std.Usize × L) L) (graph : G) (direction : solve.Direction) (transfer : T2)
  (n : Std.Usize) (cap : Std.Usize) (state : alloc.vec.Vec L)
  (queued : alloc.vec.Vec Bool) (work : alloc.vec.Vec Std.Usize)
  (head : Std.Usize) (rounds : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec L) × (alloc.vec.Vec Bool) ×
    (alloc.vec.Vec Std.Usize) × Std.Usize × Std.Usize) ((alloc.vec.Vec L) ×
    Std.Usize × Bool))
  := do
  let i := alloc.vec.Vec.len work
  if head < i
  then
    let v ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.Usize)
        work head
    let head1 ← head + 1#usize
    if rounds >= cap
    then ok (done (state, rounds, false))
    else
      let rounds1 ← rounds + 1#usize
      let (_, index_mut_back) ←
        alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice Bool)
          queued v
      let t ←
        alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice L) state v
      let out ← coreopsfunctionFnT2PairUsizeSharedLLInst.call transfer (v, t)
      let queued1 := index_mut_back false
      let (state1, queued2, work1) ←
        solve.solve_loop2_loop0 GraphInst latticeLatticeInst graph direction n
          state queued1 work v out 0#usize
      ok (cont (state1, queued2, work1, head1, rounds1))
  else ok (done (state, rounds, true))

/-- [lattice::solve::solve]: loop 2:
    Source: 'lattice/src/lib.rs', lines 1:0-560:9
    Visibility: public -/
@[rust_loop]
def solve.solve_loop2
  {G : Type} {L : Type} {T2 : Type} (GraphInst : solve.Graph G)
  (latticeLatticeInst : lattice.Lattice L)
  (coreopsfunctionFnT2PairUsizeSharedLLInst : core.ops.function.Fn T2
  (Std.Usize × L) L) (graph : G) (direction : solve.Direction) (transfer : T2)
  (n : Std.Usize) (state : alloc.vec.Vec L) (queued : alloc.vec.Vec Bool)
  (work : alloc.vec.Vec Std.Usize) (head : Std.Usize) (cap : Std.Usize)
  (rounds : Std.Usize) :
  Result ((alloc.vec.Vec L) × Std.Usize × Bool)
  := do
  loop
    (fun (state1, queued1, work1, head1, rounds1) => solve.solve_loop2.body
      GraphInst latticeLatticeInst coreopsfunctionFnT2PairUsizeSharedLLInst
      graph direction transfer n cap state1 queued1 work1 head1 rounds1)
    (state, queued, work, head, rounds)

/-- [lattice::solve::solve]:
    Source: 'lattice/src/lib.rs', lines 483:4-566:5
    Visibility: public -/
def solve.solve
  {G : Type} {L : Type} {T2 : Type} (GraphInst : solve.Graph G)
  (latticeLatticeInst : lattice.Lattice L)
  (coreopsfunctionFnT2PairUsizeShared0LLInst : core.ops.function.Fn T2
  (Std.Usize × L) L) (graph : G) (direction : solve.Direction) (transfer : T2)
  :
  Result (solve.Solution L)
  := do
  let n ← GraphInst.node_count graph
  let (state, queued) ←
    solve.solve_loop0 latticeLatticeInst n (alloc.vec.Vec.new L)
      (alloc.vec.Vec.new Bool) 0#usize
  let work ← solve.solve_loop1 n (alloc.vec.Vec.new Std.Usize) 0#usize
  let i ← core.num.Usize.saturating_mul n 1024#usize
  let cap ← lift (core.num.Usize.saturating_add i 4096#usize)
  let (state1, rounds, converged) ←
    solve.solve_loop2 GraphInst latticeLatticeInst
      coreopsfunctionFnT2PairUsizeShared0LLInst graph direction transfer n
      state queued work 0#usize cap 0#usize
  ok { states := state1, converged, rounds }

end lattice
