-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lattice]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace lattice

/-- Trait declaration: [lattice::lattice::Lattice]
    Source: 'lattice/src/lib.rs', lines 40:4-60:5
    Visibility: public -/
structure lattice.Lattice (Self : Type) where
  corecloneCloneInst : core.clone.Clone Self
  corecmpEqInst : core.cmp.Eq Self
  bottom : Result Self
  join : Self → Self → Result Self
  meet : Self → Self → Result Self
  leq : Self → Self → Result Bool

/-- Trait declaration: [lattice::lattice::BoundedLattice]
    Source: 'lattice/src/lib.rs', lines 68:4-71:5
    Visibility: public -/
structure lattice.BoundedLattice (Self : Type) where
  LatticeInst : lattice.Lattice Self
  top : Result Self

/-- [lattice::lattice::Powerset]
    Source: 'lattice/src/lib.rs', lines 84:4-84:52
    Visibility: public -/
@[reducible]
def lattice.Powerset (T : Type) := alloc.vec.Vec T

/-- [lattice::lattice::Flat]
    Source: 'lattice/src/lib.rs', lines 162:4-166:5
    Visibility: public -/
@[discriminant isize]
inductive lattice.Flat (T : Type) where
| Bottom : lattice.Flat T
| Elem : T → lattice.Flat T
| Top : lattice.Flat T

/-- [lattice::lattice::Product]
    Source: 'lattice/src/lib.rs', lines 209:4-209:43
    Visibility: public -/
def lattice.Product (A : Type) (B : Type) := A × B

/-- [lattice::lattice::MapL]
    Source: 'lattice/src/lib.rs', lines 244:4-244:61
    Visibility: public -/
@[reducible]
def lattice.MapL (K : Type) (V : Type) := alloc.vec.Vec (K × V)

/-- [lattice::lattice::May]
    Source: 'lattice/src/lib.rs', lines 353:4-353:29
    Visibility: public -/
@[reducible]
def lattice.May (L : Type) := L

/-- [lattice::lattice::Must]
    Source: 'lattice/src/lib.rs', lines 390:4-390:30
    Visibility: public -/
@[reducible]
def lattice.Must (L : Type) := L

/-- Trait declaration: [lattice::solve::Graph]
    Source: 'lattice/src/lib.rs', lines 437:4-443:5
    Visibility: public -/
structure solve.Graph (Self : Type) where
  node_count : Self → Result Std.Usize
  succ : Self → Std.Usize → Result (Slice Std.Usize)
  pred : Self → Std.Usize → Result (Slice Std.Usize)

/-- [lattice::solve::Direction]
    Source: 'lattice/src/lib.rs', lines 449:4-452:5
    Visibility: public -/
@[discriminant isize]
inductive solve.Direction where
| Forward : solve.Direction
| Backward : solve.Direction

/-- [lattice::solve::Solution]
    Source: 'lattice/src/lib.rs', lines 463:4-467:5
    Visibility: public -/
structure solve.Solution (L : Type) where
  states : alloc.vec.Vec L
  converged : Bool
  rounds : Std.Usize

end lattice
