//! @generated by `dorc-verify promote` — do not edit by hand.
//!
//! The promote-gated catalogue lock (`301` §5). Every row's badge expectation was COMPUTED
//! from evidence at promote time; the gate recomputes and refuses a mismatch in either
//! direction, so a silent demotion (rot) and a silent promotion (ambition) are both loud.
//!
//! Promoting is a spec-side act under `301:law-spec-touch-frontier-human-only`. Review is the
//! git diff of this file. Claim inputs a promote cannot derive — a typed `excepted(reason)`
//! above all — are authored here and carried forward by the generator untouched.

use crate::badge::Expectation;
use crate::catalogue::LawRow;

/// Every catalogued law, sorted by slug.
pub const LAWS: [LawRow; 3] = [
    LawRow {
        slug: "JoinIsAssociative",
        seat: "dorc_analysis::lattice::Lattice::join",
        proof: None,
        harness: None,
        bindings: &[],
        expected: [
            Expectation::Earned,
            Expectation::Earned,
            Expectation::Todo,
            Expectation::Todo,
            Expectation::Todo,
            Expectation::Todo,
        ],
    },
    LawRow {
        slug: "JoinIsCommutative",
        seat: "dorc_analysis::lattice::Lattice::join",
        proof: None,
        harness: None,
        bindings: &[],
        expected: [
            Expectation::Earned,
            Expectation::Earned,
            Expectation::Todo,
            Expectation::Todo,
            Expectation::Todo,
            Expectation::Todo,
        ],
    },
    LawRow {
        slug: "JoinIsIdempotent",
        seat: "dorc_analysis::lattice::Lattice::join",
        proof: None,
        harness: None,
        bindings: &[],
        expected: [
            Expectation::Earned,
            Expectation::Earned,
            Expectation::Todo,
            Expectation::Todo,
            Expectation::Todo,
            Expectation::Todo,
        ],
    },
];
