//! The report (`301` §5) — generated, never authored.
//!
//! Its job is `post-halo-is-the-hazard`: a reader who sees a lean directory must not infer
//! "there are proofs, so it's covered". So every badge of every law renders, absence with the
//! same mechanical weight as presence, and the tier that could not look says so instead of
//! echoing what was promoted.
//!
//! The last section is the **verified boundary**: "the subsets of the analysis engine we have
//! opted to verify with Lean", computed as the census of cited seats. It is the one named,
//! maintained-for-free vocabulary boundary among the kernel/engine/algebra layers — free
//! because it falls out of citations that exist for other reasons.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;

use crate::badge::{Badge, Evidence};
use crate::catalogue::LawRow;
use crate::evidence::Tier;
use crate::unit::{Statement, Unit};

/// Everything one row of the report needs.
#[derive(Debug)]
pub struct Row<'a> {
    /// The catalogue row.
    pub law: &'a LawRow,
    /// Its unit, when the file exists.
    pub unit: Option<&'a Unit>,
    /// Computed evidence, in [`Badge::ALL`] order.
    pub evidence: Vec<Evidence>,
}

/// Render the whole report.
///
/// `repo_root` is taken so every path in the artifact is written repo-RELATIVE. The committed
/// copy is byte-compared against a fresh render, so an absolute path pins the report to the
/// worktree that produced it and makes it permanently stale everywhere else.
#[must_use]
pub fn render(rows: &[Row<'_>], tier: Tier<'_>, census: Census, repo_root: &Path) -> String {
    let mut out = String::new();
    out.push_str("# minispec coverage report\n\n");
    out.push_str(
        "@generated by `dorc-verify report` — do not edit by hand.\n\n\
         Badges are an independent SET, not a ladder: cross-states are real, and a scalar score \
         would force an order the evidence does not have. Every badge is computed from \
         evidence; the catalogue's expectation is compared against it and a mismatch in either \
         direction is a refusal.\n\n",
    );
    let _ = writeln!(out, "Tier: {}\n", tier_line(tier));

    let _ = writeln!(out, "## Laws\n");
    for row in rows {
        let _ = writeln!(out, "### {}\n", row.law.slug);
        let _ = writeln!(out, "- seat: `{}`", row.law.seat);
        let _ = writeln!(
            out,
            "- statement: {}",
            match row.unit {
                Some(u) if u.statement == Statement::Unwritten =>
                    "UNWRITTEN STUB — asserts nothing".to_owned(),
                Some(u) => format!(
                    "`{}` ({} bytes)",
                    crate::relative(repo_root, &u.path),
                    u.bytes
                ),
                None => "MISSING".to_owned(),
            }
        );
        let _ = writeln!(out, "- proof: {}", row.law.proof.unwrap_or("none claimed"));
        let _ = writeln!(out, "- bindings: {}", row.law.bindings.len());
        let _ = writeln!(out, "\n| badge | promoted | evidence |");
        let _ = writeln!(out, "|---|---|---|");
        for (index, badge) in Badge::ALL.iter().enumerate() {
            let promoted = row.law.expectation(*badge).render();
            let computed = row
                .evidence
                .get(index)
                .map_or_else(|| "unknown".to_owned(), Evidence::render);
            let _ = writeln!(out, "| {badge} | {promoted} | {computed} |");
        }
        out.push('\n');
    }

    let _ = writeln!(out, "## The verified boundary\n");
    out.push_str(
        "The subsets of the analysis engine opted into Lean verification, as the census of \
         cited seats. Everything not listed is outside the boundary, whatever else guards it.\n\n",
    );
    let mut seats: Vec<&str> = rows.iter().map(|r| r.law.seat).collect();
    seats.sort_unstable();
    seats.dedup();
    for seat in seats {
        let _ = writeln!(out, "- `{seat}`");
    }

    let _ = writeln!(out, "\n## The trusted base\n");
    let _ = writeln!(
        out,
        "- `minispec/Generated/` proof holes: **{}**. A lenient translation emits SILENT holes \
         and a hole typechecks, so a green build proves nothing without this number.",
        census.holes
    );
    let _ = writeln!(
        out,
        "- external axioms in `Generated/`: **{}**. Each is a std or fenced function the \
         translator does not model, standing in for a body nothing checks. The fence — which \
         items are axiomatized and why — is `spike/verify/aeneas/Cargo.toml`, where every entry \
         carries its class and its reason.",
        census.axioms
    );
    // The RECORDED digest, never a live comparison: a live one would make every source edit
    // restale this artifact, turning a warn-tier alarm into a gate on a Linux-only act.
    let _ = writeln!(
        out,
        "- derivation digest: **{}**. `Generated/` is derived from the Rust the translation \
         unit includes; this is the digest of those inputs as of the derivation that produced \
         it (`spike/verify/aeneas/derivation.lock`). Whether the sources have MOVED since is a warning \
         `dorc-verify check` and `report` print, never a value in this file.",
        crate::derivation::recorded(repo_root).map_or_else(
            || "NONE RECORDED".to_owned(),
            |lock| crate::derivation::short(&lock)
        )
    );
    out.push('\n');
    out
}

/// Which engines this render's numbers came from. Named per engine rather than as one label,
/// because the lanes are independently opt-in and a reader has to be able to tell a `pinned`
/// that was not looked at from one that was looked at and found absent.
fn tier_line(tier: Tier<'_>) -> String {
    match tier {
        Tier::Cheap => {
            "cheap (filesystem + parsing only; Lean/Kani/mutant evidence is not recomputed here)"
                .to_owned()
        }
        Tier::WithEngines { lean_built, kani } => {
            let lean = match lean_built {
                None => "Lean not run",
                Some(true) => "lake build GREEN",
                Some(false) => "lake build FAILED",
            };
            let kani = match kani {
                None => "Kani not run".to_owned(),
                Some(report) if report.failed.is_empty() => {
                    format!("Kani GREEN ({} harnesses)", report.green.len())
                }
                Some(report) => format!("Kani FAILED ({} harnesses)", report.failed.len()),
            };
            format!("with-engines ({lean}; {kani})")
        }
    }
}

/// The trusted-base numbers a report carries.
#[derive(Clone, Copy, Debug)]
pub struct Census {
    /// Proof holes in the generated tree.
    pub holes: usize,
    /// External axioms in the generated tree.
    pub axioms: usize,
}

/// Where the committed report lives.
#[must_use]
pub fn path(repo_root: &Path) -> std::path::PathBuf {
    repo_root.join("minispec").join("REPORT.md")
}

/// What the committed report is, relative to what the evidence now says.
#[derive(Debug)]
pub enum Freshness {
    /// Byte-identical to a fresh render.
    Current,
    /// No committed copy at all.
    Missing,
    /// Present and diverged, with WHERE.
    Stale(Vec<Divergence>),
}

/// One section of the report whose cells diverged.
#[derive(Debug)]
pub struct Divergence {
    /// The heading the divergence sits under, or `(preamble)` above the first one.
    pub section: String,
    /// The cells that moved, each as what the committed copy says against what the evidence
    /// says. `None` on a side is a cell only the other side has.
    pub cells: Vec<(Option<String>, Option<String>)>,
}

/// Compare the committed report against a fresh render.
///
/// # Errors
/// Never — an unreadable committed copy is [`Freshness::Missing`], which is a finding rather
/// than an error: the remedy for both is the same republish.
#[must_use]
pub fn freshness(repo_root: &Path, computed: &str) -> Freshness {
    match std::fs::read_to_string(path(repo_root)) {
        Err(_) => Freshness::Missing,
        Ok(committed) if committed == computed => Freshness::Current,
        Ok(committed) => Freshness::Stale(diverge(&committed, computed)),
    }
}

/// Group both texts by heading, then pair up each section's CELLS and report only the ones
/// whose values moved.
///
/// Section- and cell-scoped rather than line-scoped, because that is what makes the answer
/// STRUCTURAL: a reader learns which law's which row moved, a law added or removed shows up as
/// its own section rather than as an avalanche of shifted lines, and the unchanged lines
/// between two moved cells never appear at all.
fn diverge(committed: &str, computed: &str) -> Vec<Divergence> {
    let (old, new) = (sections(committed), sections(computed));
    let mut order: Vec<&String> = old.keys().collect();
    order.extend(new.keys().filter(|k| !old.contains_key(*k)));
    let empty: BTreeMap<String, String> = BTreeMap::new();
    let mut out = Vec::new();
    for section in order {
        let (was, is) = (
            old.get(section).unwrap_or(&empty),
            new.get(section).unwrap_or(&empty),
        );
        let mut cells: Vec<(Option<String>, Option<String>)> = Vec::new();
        for (key, before) in was {
            match is.get(key) {
                Some(after) if after == before => {}
                after => cells.push((Some(before.clone()), after.cloned())),
            }
        }
        for (key, after) in is {
            if !was.contains_key(key) {
                cells.push((None, Some(after.clone())));
            }
        }
        if !cells.is_empty() {
            out.push(Divergence {
                section: section.clone(),
                cells,
            });
        }
    }
    out
}

/// The report's lines, grouped by heading and keyed by CELL within it.
fn sections(text: &str) -> BTreeMap<String, BTreeMap<String, String>> {
    let mut out: BTreeMap<String, BTreeMap<String, String>> = BTreeMap::new();
    let mut current = "(preamble)".to_owned();
    for line in text.lines() {
        if line.starts_with('#') {
            current.clear();
            current.push_str(line.trim_start_matches('#').trim());
            continue;
        }
        if !line.trim().is_empty() {
            out.entry(current.clone())
                .or_default()
                .insert(cell_key(line), line.trim().to_owned());
        }
    }
    out
}

/// The label a report line is keyed by: a bullet's name, a badge-table row's badge, or — for
/// anything else — the line itself.
///
/// Keying is what makes the answer per-cell: a moved value pairs with the value it replaced,
/// instead of the two surfacing as an unrelated removal and addition.
fn cell_key(line: &str) -> String {
    let trimmed = line.trim();
    if let Some(bullet) = trimmed.strip_prefix("- ")
        && let Some((label, _)) = bullet.split_once(':')
    {
        return format!("- {label}");
    }
    if let Some(row) = trimmed.strip_prefix('|')
        && let Some((badge, _)) = row.split_once('|')
    {
        return format!("| {}", badge.trim());
    }
    trimmed.to_owned()
}

/// How many moved cells one refusal names per section before it stops. A stale report is read
/// by somebody deciding whether the change is expected; a dump of the whole artifact is the
/// thing they were already failing to read.
const SHOWN_PER_SECTION: usize = 4;

/// The refusal text: what diverged, where, and the one command that fixes it.
#[must_use]
pub fn describe_staleness(freshness: &Freshness) -> String {
    let divergences = match freshness {
        Freshness::Current => return String::new(),
        Freshness::Missing => {
            return "minispec/REPORT.md is MISSING — republish it with \
                    `mise run verify:report -- --write`"
                .to_owned();
        }
        Freshness::Stale(divergences) => divergences,
    };
    let cells: usize = divergences.iter().map(|d| d.cells.len()).sum();
    let mut out = format!(
        "minispec/REPORT.md is STALE — {cells} cell(s) moved across {} section(s). Republish \
         with `mise run verify:report -- --write` and review the diff:",
        divergences.len()
    );
    for divergence in divergences {
        let _ = write!(out, "\n  {}", divergence.section);
        for (before, after) in divergence.cells.iter().take(SHOWN_PER_SECTION) {
            let _ = write!(
                out,
                "\n    committed: {}\n    evidence:  {}",
                before.as_deref().unwrap_or("(absent)"),
                after.as_deref().unwrap_or("(absent)")
            );
        }
        let hidden = divergence.cells.len().saturating_sub(SHOWN_PER_SECTION);
        if hidden > 0 {
            let _ = write!(out, "\n    … and {hidden} more cell(s) in this section");
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    const COMMITTED: &str = "\
# minispec coverage report

Tier: cheap

## Laws

### JoinIsIdempotent

- statement: `minispec/Minispec/JoinIsIdempotent.lean` (2172 bytes)
- proof: none claimed

## The trusted base

- external axioms: **13**.
";

    #[test]
    fn staleness_names_the_section_and_the_cell_that_moved() {
        // "stale — re-run with --write" is the failure this replaces: it tells a reader that
        // something moved and makes them regenerate to find out what, which is exactly when a
        // republish stops being a review and becomes a rubber stamp.
        let computed = COMMITTED.replace("2172 bytes", "2669 bytes");
        let found = diverge(COMMITTED, &computed);
        assert_eq!(found.len(), 1, "one section moved, not the whole file");
        assert_eq!(found[0].section, "JoinIsIdempotent");
        assert_eq!(found[0].cells.len(), 1, "the `proof:` cell is unchanged");
        let described = describe_staleness(&Freshness::Stale(found));
        assert!(described.contains("JoinIsIdempotent"));
        assert!(described.contains("2172"), "what is committed");
        assert!(described.contains("2669"), "what the evidence says");
        assert!(described.contains("--write"), "and the remedy");
        assert!(
            !described.contains("none claimed"),
            "an unchanged neighbour is not part of the finding"
        );
    }

    #[test]
    fn a_badge_row_pairs_with_the_row_it_replaced() {
        // Table rows key on their badge, so a moved evidence cell reads as one before/after
        // pair rather than as an unrelated removal beside an unrelated addition.
        let old = "### L\n\n| pinned | todo | absent(no paired harness) |\n";
        let new = "### L\n\n| pinned | todo | earned |\n";
        let found = diverge(old, new);
        assert_eq!(found.len(), 1);
        assert_eq!(found[0].cells.len(), 1, "one row moved, one cell reported");
        let (before, after) = &found[0].cells[0];
        assert!(before.as_ref().is_some_and(|line| line.contains("absent")));
        assert!(after.as_ref().is_some_and(|line| line.contains("earned")));
    }

    #[test]
    fn a_whole_law_appearing_is_one_section_and_not_an_avalanche() {
        // Line-number diffing would report every line after an inserted law. Sections are what
        // keep a promote's report readable.
        let computed = COMMITTED.replace(
            "## The trusted base",
            "### JoinIsCommutative\n\n- proof: none claimed\n\n## The trusted base",
        );
        let found = diverge(COMMITTED, &computed);
        assert_eq!(found.len(), 1);
        assert_eq!(found[0].section, "JoinIsCommutative");
        assert!(
            found[0].cells.iter().all(|(before, _)| before.is_none()),
            "every cell in it is new"
        );
    }

    #[test]
    fn a_byte_identical_report_is_current() {
        assert!(diverge(COMMITTED, COMMITTED).is_empty());
        assert!(describe_staleness(&Freshness::Current).is_empty());
    }
}
