//! The report (`301` §5) — generated, never authored.
//!
//! Its job is `post-halo-is-the-hazard`: a reader who sees a lean directory must not infer
//! "there are proofs, so it's covered". So every badge of every law renders, absence with the
//! same mechanical weight as presence, and the tier that could not look says so instead of
//! echoing what was promoted.
//!
//! The last section is the **verified boundary**: "the subsets of the analysis engine we have
//! opted to verify with Lean", computed as the census of cited seats. It is the one named,
//! maintained-for-free vocabulary boundary among the kernel/engine/algebra layers — free
//! because it falls out of citations that exist for other reasons.

use std::fmt::Write as _;
use std::path::Path;

use crate::badge::{Badge, Evidence};
use crate::catalogue::LawRow;
use crate::evidence::Tier;
use crate::unit::{Statement, Unit};

/// Everything one row of the report needs.
#[derive(Debug)]
pub struct Row<'a> {
    /// The catalogue row.
    pub law: &'a LawRow,
    /// Its unit, when the file exists.
    pub unit: Option<&'a Unit>,
    /// Computed evidence, in [`Badge::ALL`] order.
    pub evidence: Vec<Evidence>,
}

/// Render the whole report.
#[must_use]
pub fn render(rows: &[Row<'_>], tier: Tier<'_>, census: Census) -> String {
    let mut out = String::new();
    out.push_str("# minispec coverage report\n\n");
    out.push_str(
        "@generated by `dorc-verify report` — do not edit by hand.\n\n\
         Badges are an independent SET, not a ladder: cross-states are real, and a scalar score \
         would force an order the evidence does not have. Every badge is computed from \
         evidence; the catalogue's expectation is compared against it and a mismatch in either \
         direction is a refusal.\n\n",
    );
    let _ = writeln!(out, "Tier: {}\n", tier_line(tier));

    let _ = writeln!(out, "## Laws\n");
    for row in rows {
        let _ = writeln!(out, "### {}\n", row.law.slug);
        let _ = writeln!(out, "- seat: `{}`", row.law.seat);
        let _ = writeln!(
            out,
            "- statement: {}",
            match row.unit {
                Some(u) if u.statement == Statement::Unwritten =>
                    "UNWRITTEN STUB — asserts nothing".to_owned(),
                Some(u) => format!("`{}` ({} bytes)", u.path.display(), u.bytes),
                None => "MISSING".to_owned(),
            }
        );
        let _ = writeln!(out, "- proof: {}", row.law.proof.unwrap_or("none claimed"));
        let _ = writeln!(out, "- bindings: {}", row.law.bindings.len());
        let _ = writeln!(out, "\n| badge | promoted | evidence |");
        let _ = writeln!(out, "|---|---|---|");
        for (index, badge) in Badge::ALL.iter().enumerate() {
            let promoted = row.law.expectation(*badge).render();
            let computed = row
                .evidence
                .get(index)
                .map_or_else(|| "unknown".to_owned(), Evidence::render);
            let _ = writeln!(out, "| {badge} | {promoted} | {computed} |");
        }
        out.push('\n');
    }

    let _ = writeln!(out, "## The verified boundary\n");
    out.push_str(
        "The subsets of the analysis engine opted into Lean verification, as the census of \
         cited seats. Everything not listed is outside the boundary, whatever else guards it.\n\n",
    );
    let mut seats: Vec<&str> = rows.iter().map(|r| r.law.seat).collect();
    seats.sort_unstable();
    seats.dedup();
    for seat in seats {
        let _ = writeln!(out, "- `{seat}`");
    }

    let _ = writeln!(out, "\n## The trusted base\n");
    let _ = writeln!(
        out,
        "- `minispec/Generated/` proof holes: **{}**. A lenient translation emits SILENT holes \
         and a hole typechecks, so a green build proves nothing without this number.",
        census.holes
    );
    let _ = writeln!(
        out,
        "- external axioms in `Generated/`: **{}**. Each is a std or fenced function the \
         translator does not model, standing in for a body nothing checks. The fence — which \
         items are axiomatized and why — is `spike/verify/aeneas/Cargo.toml`, where every entry \
         carries its class and its reason.",
        census.axioms
    );
    out.push('\n');
    out
}

/// Which engines this render's numbers came from. Named per engine rather than as one label,
/// because the lanes are independently opt-in and a reader has to be able to tell a `pinned`
/// that was not looked at from one that was looked at and found absent.
fn tier_line(tier: Tier<'_>) -> String {
    match tier {
        Tier::Cheap => {
            "cheap (filesystem + parsing only; Lean/Kani/mutant evidence is not recomputed here)"
                .to_owned()
        }
        Tier::WithEngines { lean_built, kani } => {
            let lean = match lean_built {
                None => "Lean not run",
                Some(true) => "lake build GREEN",
                Some(false) => "lake build FAILED",
            };
            let kani = match kani {
                None => "Kani not run".to_owned(),
                Some(report) if report.failed.is_empty() => {
                    format!("Kani GREEN ({} harnesses)", report.green.len())
                }
                Some(report) => format!("Kani FAILED ({} harnesses)", report.failed.len()),
            };
            format!("with-engines ({lean}; {kani})")
        }
    }
}

/// The trusted-base numbers a report carries.
#[derive(Clone, Copy, Debug)]
pub struct Census {
    /// Proof holes in the generated tree.
    pub holes: usize,
    /// External axioms in the generated tree.
    pub axioms: usize,
}

/// Where the committed report lives.
#[must_use]
pub fn path(repo_root: &Path) -> std::path::PathBuf {
    repo_root.join("minispec").join("REPORT.md")
}
