//! The orphan-arrangement instrument (`30Rk:the-arrangement-mirror-is-its-own-lock`): which
//! arrangement-lock rows no living source declares.
//!
//! # An instrument, never a gate
//!
//! It reports and it deletes nothing, on `doctor-inventories-never-reaps`'s footing and for a
//! sharper reason: a RED gate here would make the shortest path "delete the row", and removing a
//! user-facing string is a conductor-at-least decision. A string that quietly disappears has many
//! ways to be a bad thing, and none of them is a thing a test should be able to provoke.
//!
//! # Why a scan is the right instrument for this
//!
//! `lexical-fences-are-human-ack-instruments` targets grep-gates standing in for TYPECHECKING. This
//! is not that: an arrangement slug is DECLARED in inherently textual material — a case's own
//! frontmatter, and a string literal at the seat that renders it — and there is no type that could
//! answer the question. Scanning text is what asking it looks like.
//!
//! # What "declared" means
//!
//! Either a case declares the slug (`arrangement:` or `owns:` in a `.loom` frontmatter), or some
//! production source spells it as a literal. Both are real homes: the first is where its words are
//! edited, the second is where its words are rendered. A row with neither is an orphan — nobody
//! edits it and nothing prints it.

use std::path::Path;
use std::process::ExitCode;

/// The generated lock this instrument reads. Textual, like `prose_census`: one serializer, one
/// field per line, and no dependency on the crate that generates it.
const LOCK: &str = "spike/crates/aid/src/arrangement_lock.rs";

/// Every arrangement slug the lock carries, in lock order.
fn rows(lock: &str) -> Vec<String> {
    lock.lines()
        .filter_map(|line| line.trim_start().strip_prefix("slug: \""))
        .filter_map(|rest| rest.split('"').next())
        .map(str::to_owned)
        .collect()
}

/// Whether `slug` is declared anywhere in `haystacks`.
///
/// Quoted for a source literal and bare for a frontmatter declaration, which is what makes
/// `why-total-role-root` not answer for `why-total-role-rooted`: a prefix is not a declaration.
fn declared(slug: &str, haystacks: &[String]) -> bool {
    let quoted = format!("\"{slug}\"");
    let listed = format!(" {slug}\n");
    let scalared = format!(": {slug}\n");
    haystacks
        .iter()
        .any(|text| text.contains(&quoted) || text.contains(&listed) || text.contains(&scalared))
}

/// Every file under `dir` whose extension is `ext`, read, in sorted order.
fn texts(dir: &Path, ext: &str, out: &mut Vec<String>) {
    let mut entries: Vec<_> = std::fs::read_dir(dir)
        .into_iter()
        .flatten()
        .flatten()
        .map(|entry| entry.path())
        .collect();
    entries.sort();
    for path in entries {
        if path.is_dir() {
            texts(&path, ext, out);
        } else if path.extension().is_some_and(|found| found == ext) {
            out.push(std::fs::read_to_string(&path).unwrap_or_default());
        }
    }
}

/// Every place an arrangement slug may be declared: the loom corpora, and production sources.
///
/// A GENERATED lock is skipped — a mirror of the rows is not a declaration of them, and counting
/// one would make every row declare itself.
fn declarations(root: &Path) -> Vec<String> {
    let mut out = Vec::new();
    let crates = root.join("spike").join("crates");
    for entry in std::fs::read_dir(&crates).into_iter().flatten().flatten() {
        let path = entry.path();
        texts(&path.join("tests"), "loom", &mut out);
        let src = path.join("src");
        let mut sources = Vec::new();
        texts(&src, "rs", &mut sources);
        out.extend(
            sources
                .into_iter()
                .filter(|text| !text.starts_with("// @generated by dorc-loom")),
        );
    }
    out
}

pub(crate) fn run() -> ExitCode {
    let root = internal_tooling::repo_root();
    let path = root.join(LOCK);
    let Ok(lock) = std::fs::read_to_string(&path) else {
        eprintln!("arrangement-census: cannot read {}", path.display());
        return ExitCode::from(2);
    };
    let haystacks = declarations(root);
    let all = rows(&lock);
    let mut orphans: Vec<&String> = all
        .iter()
        .filter(|slug| !declared(slug, &haystacks))
        .collect();
    orphans.sort();
    println!("{LOCK}: {} rows, {} undeclared", all.len(), orphans.len());
    for slug in &orphans {
        println!("  {slug}");
    }
    println!(
        "reported, never reaped: removing a user-facing string is a conductor decision, so this \
         instrument names them and stops."
    );
    ExitCode::SUCCESS
}

#[cfg(test)]
mod tests {
    use super::{declared, rows};

    /// Rows come off the serializer's own field, and a slug is declared by a literal, a `list`
    /// item, or a `scalar:` — stated over synthesized material so real corpus churn cannot redden
    /// this.
    #[test]
    fn a_row_is_declared_by_a_literal_a_list_item_or_a_scalar() {
        let lock = "// @generated\n    ArrangementEntry {\n        slug: \"used-by-a-seat\",\n    },\n    \
                    ArrangementEntry {\n        slug: \"used-by-a-case\",\n    },\n    \
                    ArrangementEntry {\n        slug: \"nobody-declares-this\",\n    },\n";
        assert_eq!(
            rows(lock),
            vec![
                "used-by-a-seat".to_owned(),
                "used-by-a-case".to_owned(),
                "nobody-declares-this".to_owned()
            ]
        );
        let haystacks = vec![
            "Said::words(\"used-by-a-seat\", &[])\n".to_owned(),
            "arrangement: used-by-a-case\n".to_owned(),
        ];
        assert!(declared("used-by-a-seat", &haystacks));
        assert!(declared("used-by-a-case", &haystacks));
        assert!(!declared("nobody-declares-this", &haystacks));
    }

    /// A PREFIX is not a declaration: the quoted and delimited forms are what keep
    /// `why-total-role-root` from answering for a longer neighbour.
    #[test]
    fn a_prefix_of_a_declared_slug_is_not_declared() {
        let haystacks = vec!["Said::words(\"role-rooted\", &[])\n".to_owned()];
        assert!(!declared("role-root", &haystacks));
    }
}
