-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [census]: function definitions
import Aeneas
import Census.Types
import Census.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace census

/-- Trait implementation: [core::fmt::{impl core::fmt::Debug for core::marker::PhantomData<T>}]
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 3135:0-3135:40
    Name pattern: [core::fmt::Debug<core::marker::PhantomData<@T>>] -/
@[reducible, rust_trait_impl "core::fmt::Debug<core::marker::PhantomData<@T>>"]
def core.marker.PhantomData.Insts.CoreFmtDebug (T : Type) : core.fmt.Debug
  (core.marker.PhantomData T) := {
  fmt := core.marker.PhantomData.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [core::option::{impl core::fmt::Debug for core::option::Option<T>}]
    Source: '/rustc/library/core/src/option.rs', lines 591:15-591:20
    Name pattern: [core::fmt::Debug<core::option::Option<@T>>] -/
@[reducible, rust_trait_impl "core::fmt::Debug<core::option::Option<@T>>"]
def core.option.Option.Insts.CoreFmtDebug {T : Type} (fmtDebugInst :
  core.fmt.Debug T) : core.fmt.Debug (Option T) := {
  fmt := core.option.Option.Insts.CoreFmtDebug.fmt fmtDebugInst
}

/-- [census::{impl core::fmt::Debug for census::ObservationTier}::fmt]:
    Source: 'census/src/lib.rs', lines 17:9-17:14
    Visibility: public -/
def ObservationTier.Insts.CoreFmtDebug.fmt
  (self : ObservationTier) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  fail panic

/-- Trait implementation: [census::{impl core::fmt::Debug for census::ObservationTier}]
    Source: 'census/src/lib.rs', lines 17:9-17:14 -/
@[reducible]
def ObservationTier.Insts.CoreFmtDebug : core.fmt.Debug ObservationTier := {
  fmt := ObservationTier.Insts.CoreFmtDebug.fmt
}

/-- [census::{impl core::clone::Clone for census::ObservationTier}::clone]:
    Source: 'census/src/lib.rs', lines 17:16-17:21
    Visibility: public -/
def ObservationTier.Insts.CoreCloneClone.clone
  (self : ObservationTier) : Result ObservationTier := do
  ok self

/-- Trait implementation: [census::{impl core::clone::Clone for census::ObservationTier}]
    Source: 'census/src/lib.rs', lines 17:16-17:21 -/
@[reducible]
def ObservationTier.Insts.CoreCloneClone : core.clone.Clone ObservationTier
  := {
  clone := ObservationTier.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [census::{impl core::marker::Copy for census::ObservationTier}]
    Source: 'census/src/lib.rs', lines 17:23-17:27 -/
@[reducible]
def ObservationTier.Insts.CoreMarkerCopy : core.marker.Copy ObservationTier
  := {
  cloneInst := ObservationTier.Insts.CoreCloneClone
}

/-- Trait implementation: [census::{impl core::marker::StructuralPartialEq for census::ObservationTier}]
    Source: 'census/src/lib.rs', lines 17:29-17:38 -/
@[reducible]
def ObservationTier.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq ObservationTier := {
}

/-- [census::{impl core::cmp::PartialEq<census::ObservationTier> for census::ObservationTier}::eq]:
    Source: 'census/src/lib.rs', lines 17:29-17:38
    Visibility: public -/
def ObservationTier.Insts.CoreCmpPartialEqObservationTier.eq
  (self : ObservationTier) (other : ObservationTier) : Result Bool := do
  fail panic

/-- Trait implementation: [census::{impl core::cmp::PartialEq<census::ObservationTier> for census::ObservationTier}]
    Source: 'census/src/lib.rs', lines 17:29-17:38 -/
@[reducible]
impl_def ObservationTier.Insts.CoreCmpPartialEqObservationTier :
  core.cmp.PartialEq ObservationTier ObservationTier := {
  eq := ObservationTier.Insts.CoreCmpPartialEqObservationTier.eq
  ne := core.cmp.PartialEq.ne.trait_default
    ObservationTier.Insts.CoreCmpPartialEqObservationTier
}

/-- [census::{impl core::cmp::Eq for census::ObservationTier}::assert_fields_are_eq]:
    Source: 'census/src/lib.rs', lines 17:40-17:42
    Visibility: public -/
def ObservationTier.Insts.CoreCmpEq.assert_fields_are_eq
  (self : ObservationTier) : Result Unit := do
  ok ()

/-- Trait implementation: [census::{impl core::cmp::Eq for census::ObservationTier}]
    Source: 'census/src/lib.rs', lines 17:40-17:42 -/
@[reducible]
def ObservationTier.Insts.CoreCmpEq : core.cmp.Eq ObservationTier := {
  partialEqInst := ObservationTier.Insts.CoreCmpPartialEqObservationTier
  assert_fields_are_eq := ObservationTier.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [census::{impl core::fmt::Debug for census::VouchTier}::fmt]:
    Source: 'census/src/lib.rs', lines 20:9-20:14
    Visibility: public -/
def VouchTier.Insts.CoreFmtDebug.fmt
  (self : VouchTier) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  fail panic

/-- Trait implementation: [census::{impl core::fmt::Debug for census::VouchTier}]
    Source: 'census/src/lib.rs', lines 20:9-20:14 -/
@[reducible]
def VouchTier.Insts.CoreFmtDebug : core.fmt.Debug VouchTier := {
  fmt := VouchTier.Insts.CoreFmtDebug.fmt
}

/-- [census::{impl core::clone::Clone for census::VouchTier}::clone]:
    Source: 'census/src/lib.rs', lines 20:16-20:21
    Visibility: public -/
def VouchTier.Insts.CoreCloneClone.clone
  (self : VouchTier) : Result VouchTier := do
  ok self

/-- Trait implementation: [census::{impl core::clone::Clone for census::VouchTier}]
    Source: 'census/src/lib.rs', lines 20:16-20:21 -/
@[reducible]
def VouchTier.Insts.CoreCloneClone : core.clone.Clone VouchTier := {
  clone := VouchTier.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [census::{impl core::marker::Copy for census::VouchTier}]
    Source: 'census/src/lib.rs', lines 20:23-20:27 -/
@[reducible]
def VouchTier.Insts.CoreMarkerCopy : core.marker.Copy VouchTier := {
  cloneInst := VouchTier.Insts.CoreCloneClone
}

/-- Trait implementation: [census::{impl core::marker::StructuralPartialEq for census::VouchTier}]
    Source: 'census/src/lib.rs', lines 20:29-20:38 -/
@[reducible]
def VouchTier.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq VouchTier := {
}

/-- [census::{impl core::cmp::PartialEq<census::VouchTier> for census::VouchTier}::eq]:
    Source: 'census/src/lib.rs', lines 20:29-20:38
    Visibility: public -/
def VouchTier.Insts.CoreCmpPartialEqVouchTier.eq
  (self : VouchTier) (other : VouchTier) : Result Bool := do
  fail panic

/-- Trait implementation: [census::{impl core::cmp::PartialEq<census::VouchTier> for census::VouchTier}]
    Source: 'census/src/lib.rs', lines 20:29-20:38 -/
@[reducible]
impl_def VouchTier.Insts.CoreCmpPartialEqVouchTier : core.cmp.PartialEq
  VouchTier VouchTier := {
  eq := VouchTier.Insts.CoreCmpPartialEqVouchTier.eq
  ne := core.cmp.PartialEq.ne.trait_default
    VouchTier.Insts.CoreCmpPartialEqVouchTier
}

/-- [census::{impl core::cmp::Eq for census::VouchTier}::assert_fields_are_eq]:
    Source: 'census/src/lib.rs', lines 20:40-20:42
    Visibility: public -/
def VouchTier.Insts.CoreCmpEq.assert_fields_are_eq
  (self : VouchTier) : Result Unit := do
  ok ()

/-- Trait implementation: [census::{impl core::cmp::Eq for census::VouchTier}]
    Source: 'census/src/lib.rs', lines 20:40-20:42 -/
@[reducible]
def VouchTier.Insts.CoreCmpEq : core.cmp.Eq VouchTier := {
  partialEqInst := VouchTier.Insts.CoreCmpPartialEqVouchTier
  assert_fields_are_eq := VouchTier.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- Trait implementation: [census::{impl census::sealed::Sealed for census::ObservationTier}]
    Source: 'census/src/lib.rs', lines 23:0-23:42 -/
@[reducible]
def ObservationTier.Insts.CensusSealedSealed : sealed.Sealed ObservationTier
  := {
}

/-- Trait implementation: [census::{impl census::sealed::Sealed for census::VouchTier}]
    Source: 'census/src/lib.rs', lines 24:0-24:36 -/
@[reducible]
def VouchTier.Insts.CensusSealedSealed : sealed.Sealed VouchTier := {
}

/-- Trait implementation: [census::{impl census::Tier for census::ObservationTier}]
    Source: 'census/src/lib.rs', lines 25:0-25:32 -/
@[reducible]
def ObservationTier.Insts.CensusTier : Tier ObservationTier := {
  sealedSealedInst := ObservationTier.Insts.CensusSealedSealed
}

/-- Trait implementation: [census::{impl census::Tier for census::VouchTier}]
    Source: 'census/src/lib.rs', lines 26:0-26:26 -/
@[reducible]
def VouchTier.Insts.CensusTier : Tier VouchTier := {
  sealedSealedInst := VouchTier.Insts.CensusSealedSealed
}

/-- [census::{impl core::fmt::Debug for census::Rung}::fmt]:
    Source: 'census/src/lib.rs', lines 28:9-28:14
    Visibility: public -/
def Rung.Insts.CoreFmtDebug.fmt
  (self : Rung) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  core.fmt.Formatter.write_str f (toStr "Both")

/-- Trait implementation: [census::{impl core::fmt::Debug for census::Rung}]
    Source: 'census/src/lib.rs', lines 28:9-28:14 -/
@[reducible]
def Rung.Insts.CoreFmtDebug : core.fmt.Debug Rung := {
  fmt := Rung.Insts.CoreFmtDebug.fmt
}

/-- [census::{impl core::clone::Clone for census::Rung}::clone]:
    Source: 'census/src/lib.rs', lines 28:16-28:21
    Visibility: public -/
def Rung.Insts.CoreCloneClone.clone (self : Rung) : Result Rung := do
  ok self

/-- Trait implementation: [census::{impl core::clone::Clone for census::Rung}]
    Source: 'census/src/lib.rs', lines 28:16-28:21 -/
@[reducible]
def Rung.Insts.CoreCloneClone : core.clone.Clone Rung := {
  clone := Rung.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [census::{impl core::marker::Copy for census::Rung}]
    Source: 'census/src/lib.rs', lines 28:23-28:27 -/
@[reducible]
def Rung.Insts.CoreMarkerCopy : core.marker.Copy Rung := {
  cloneInst := Rung.Insts.CoreCloneClone
}

/-- Trait implementation: [census::{impl core::marker::StructuralPartialEq for census::Rung}]
    Source: 'census/src/lib.rs', lines 28:29-28:38 -/
@[reducible]
def Rung.Insts.CoreMarkerStructuralPartialEq : core.marker.StructuralPartialEq
  Rung := {
}

/-- [census::{impl core::cmp::PartialEq<census::Rung> for census::Rung}::eq]:
    Source: 'census/src/lib.rs', lines 28:29-28:38
    Visibility: public -/
def Rung.Insts.CoreCmpPartialEqRung.eq
  (self : Rung) (other : Rung) : Result Bool := do
  ok true

/-- Trait implementation: [census::{impl core::cmp::PartialEq<census::Rung> for census::Rung}]
    Source: 'census/src/lib.rs', lines 28:29-28:38 -/
@[reducible]
impl_def Rung.Insts.CoreCmpPartialEqRung : core.cmp.PartialEq Rung Rung := {
  eq := Rung.Insts.CoreCmpPartialEqRung.eq
  ne := core.cmp.PartialEq.ne.trait_default Rung.Insts.CoreCmpPartialEqRung
}

/-- [census::{impl core::cmp::Eq for census::Rung}::assert_fields_are_eq]:
    Source: 'census/src/lib.rs', lines 28:40-28:42
    Visibility: public -/
def Rung.Insts.CoreCmpEq.assert_fields_are_eq (self : Rung) : Result Unit := do
  ok ()

/-- Trait implementation: [census::{impl core::cmp::Eq for census::Rung}]
    Source: 'census/src/lib.rs', lines 28:40-28:42 -/
@[reducible]
def Rung.Insts.CoreCmpEq : core.cmp.Eq Rung := {
  partialEqInst := Rung.Insts.CoreCmpPartialEqRung
  assert_fields_are_eq := Rung.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [census::{impl core::cmp::PartialOrd<census::Rung> for census::Rung}::partial_cmp]:
    Source: 'census/src/lib.rs', lines 28:44-28:54
    Visibility: public -/
def Rung.Insts.CoreCmpPartialOrdRung.partial_cmp
  (self : Rung) (other : Rung) : Result (Option Ordering) := do
  ok (some Ordering.eq)

/-- Trait implementation: [census::{impl core::cmp::PartialOrd<census::Rung> for census::Rung}]
    Source: 'census/src/lib.rs', lines 28:44-28:54 -/
@[reducible]
def Rung.Insts.CoreCmpPartialOrdRung : core.cmp.PartialOrd Rung Rung := {
  partialEqInst := Rung.Insts.CoreCmpPartialEqRung
  partial_cmp := Rung.Insts.CoreCmpPartialOrdRung.partial_cmp
}

/-- [census::{impl core::cmp::Ord for census::Rung}::cmp]:
    Source: 'census/src/lib.rs', lines 28:56-28:59
    Visibility: public -/
def Rung.Insts.CoreCmpOrd.cmp
  (self : Rung) (other : Rung) : Result Ordering := do
  ok Ordering.eq

/-- Trait implementation: [census::{impl core::cmp::Ord for census::Rung}]
    Source: 'census/src/lib.rs', lines 28:56-28:59 -/
@[reducible]
def Rung.Insts.CoreCmpOrd : core.cmp.Ord Rung := {
  eqInst := Rung.Insts.CoreCmpEq
  partialOrdInst := Rung.Insts.CoreCmpPartialOrdRung
  cmp := Rung.Insts.CoreCmpOrd.cmp
}

/-- [census::{impl core::hash::Hash for census::Rung}::hash]:
    Source: 'census/src/lib.rs', lines 28:61-28:65
    Visibility: public -/
def Rung.Insts.CoreHashHash.hash
  {__H : Type} (corehashHasherInst : core.hash.Hasher __H) (self : Rung)
  (state : __H) :
  Result __H
  := do
  ok state

/-- Trait implementation: [census::{impl core::hash::Hash for census::Rung}]
    Source: 'census/src/lib.rs', lines 28:61-28:65 -/
@[reducible]
def Rung.Insts.CoreHashHash : core.hash.Hash Rung := {
  hash := fun {H : Type} (corehashHasherInst : core.hash.Hasher H) =>
    Rung.Insts.CoreHashHash.hash corehashHasherInst
}

/-- [census::{impl core::fmt::Debug for census::Claim<T, P>}::fmt]:
    Source: 'census/src/lib.rs', lines 36:9-36:14
    Visibility: public -/
def Claim.Insts.CoreFmtDebug.fmt
  {T : Type} {P : Type} (corefmtDebugInst : core.fmt.Debug T) (TierInst : Tier
  T) (corefmtDebugInst1 : core.fmt.Debug P) (self : Claim T P)
  (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ corefmtDebugInst1 self.payload
  let dyn1 :=
    Dyn.mk _ (core.fmt.DebugShared (core.marker.PhantomData.Insts.CoreFmtDebug
      T)) self._tier
  core.fmt.Formatter.debug_struct_field2_finish f (toStr "Claim") (toStr
    "payload") dyn (toStr "_tier") dyn1

/-- Trait implementation: [census::{impl core::fmt::Debug for census::Claim<T, P>}]
    Source: 'census/src/lib.rs', lines 36:9-36:14 -/
@[reducible]
def Claim.Insts.CoreFmtDebug {T : Type} {P : Type} (corefmtDebugInst :
  core.fmt.Debug T) (TierInst : Tier T) (corefmtDebugInst1 : core.fmt.Debug P)
  : core.fmt.Debug (Claim T P) := {
  fmt := Claim.Insts.CoreFmtDebug.fmt corefmtDebugInst TierInst
    corefmtDebugInst1
}

/-- [census::{impl core::clone::Clone for census::Claim<T, P>}::clone]:
    Source: 'census/src/lib.rs', lines 36:16-36:21
    Visibility: public -/
def Claim.Insts.CoreCloneClone.clone
  {T : Type} {P : Type} (corecloneCloneInst : core.clone.Clone T) (TierInst :
  Tier T) (corecloneCloneInst1 : core.clone.Clone P) (self : Claim T P) :
  Result (Claim T P)
  := do
  let t ← corecloneCloneInst1.clone self.payload
  let pd ← core.marker.PhantomData.Insts.CoreCloneClone.clone self._tier
  ok { payload := t, _tier := pd }

/-- Trait implementation: [census::{impl core::clone::Clone for census::Claim<T, P>}]
    Source: 'census/src/lib.rs', lines 36:16-36:21 -/
@[reducible]
def Claim.Insts.CoreCloneClone {T : Type} {P : Type} (corecloneCloneInst :
  core.clone.Clone T) (TierInst : Tier T) (corecloneCloneInst1 :
  core.clone.Clone P) : core.clone.Clone (Claim T P) := {
  clone := Claim.Insts.CoreCloneClone.clone corecloneCloneInst TierInst
    corecloneCloneInst1
}

/-- Trait implementation: [census::{impl core::marker::Copy for census::Claim<T, P>}]
    Source: 'census/src/lib.rs', lines 36:23-36:27 -/
@[reducible]
def Claim.Insts.CoreMarkerCopy {T : Type} {P : Type} (coremarkerCopyInst :
  core.marker.Copy T) (TierInst : Tier T) (coremarkerCopyInst1 :
  core.marker.Copy P) : core.marker.Copy (Claim T P) := {
  cloneInst := Claim.Insts.CoreCloneClone coremarkerCopyInst.cloneInst TierInst
    coremarkerCopyInst1.cloneInst
}

/-- Trait implementation: [census::{impl core::marker::StructuralPartialEq for census::Claim<T, P>}]
    Source: 'census/src/lib.rs', lines 36:29-36:38 -/
@[reducible]
def Claim.Insts.CoreMarkerStructuralPartialEq {T : Type} (P : Type) (TierInst :
  Tier T) : core.marker.StructuralPartialEq (Claim T P) := {
}

/-- [census::{impl core::cmp::PartialEq<census::Claim<T, P>> for census::Claim<T, P>}::eq]:
    Source: 'census/src/lib.rs', lines 36:29-36:38
    Visibility: public -/
def Claim.Insts.CoreCmpPartialEqClaim.eq
  {T : Type} {P : Type} (corecmpPartialEqInst : core.cmp.PartialEq T T)
  (TierInst : Tier T) (corecmpPartialEqInst1 : core.cmp.PartialEq P P)
  (self : Claim T P) (other : Claim T P) :
  Result Bool
  := do
  let b ← corecmpPartialEqInst1.eq self.payload other.payload
  if b
  then
    core.marker.PhantomData.Insts.CoreCmpPartialEqPhantomData.eq self._tier
      other._tier
  else ok false

/-- Trait implementation: [census::{impl core::cmp::PartialEq<census::Claim<T, P>> for census::Claim<T, P>}]
    Source: 'census/src/lib.rs', lines 36:29-36:38 -/
@[reducible]
impl_def Claim.Insts.CoreCmpPartialEqClaim {T : Type} {P : Type}
  (corecmpPartialEqInst : core.cmp.PartialEq T T) (TierInst : Tier T)
  (corecmpPartialEqInst1 : core.cmp.PartialEq P P) : core.cmp.PartialEq (Claim
  T P) (Claim T P) := {
  eq := Claim.Insts.CoreCmpPartialEqClaim.eq corecmpPartialEqInst TierInst
    corecmpPartialEqInst1
  ne := core.cmp.PartialEq.ne.trait_default (Claim.Insts.CoreCmpPartialEqClaim
    corecmpPartialEqInst TierInst corecmpPartialEqInst1)
}

/-- [census::{impl core::cmp::Eq for census::Claim<T, P>}::assert_fields_are_eq]:
    Source: 'census/src/lib.rs', lines 36:40-36:42
    Visibility: public -/
def Claim.Insts.CoreCmpEq.assert_fields_are_eq
  {T : Type} {P : Type} (corecmpEqInst : core.cmp.Eq T) (TierInst : Tier T)
  (corecmpEqInst1 : core.cmp.Eq P) (self : Claim T P) :
  Result Unit
  := do
  ok ()

/-- Trait implementation: [census::{impl core::cmp::Eq for census::Claim<T, P>}]
    Source: 'census/src/lib.rs', lines 36:40-36:42 -/
@[reducible]
def Claim.Insts.CoreCmpEq {T : Type} {P : Type} (corecmpEqInst : core.cmp.Eq T)
  (TierInst : Tier T) (corecmpEqInst1 : core.cmp.Eq P) : core.cmp.Eq (Claim T
  P) := {
  partialEqInst := Claim.Insts.CoreCmpPartialEqClaim
    corecmpEqInst.partialEqInst TierInst corecmpEqInst1.partialEqInst
  assert_fields_are_eq := Claim.Insts.CoreCmpEq.assert_fields_are_eq
    corecmpEqInst TierInst corecmpEqInst1
}

/-- [census::{impl core::fmt::Debug for census::VouchAndRung<P>}::fmt]:
    Source: 'census/src/lib.rs', lines 45:9-45:14
    Visibility: public -/
def VouchAndRung.Insts.CoreFmtDebug.fmt
  {P : Type} (corefmtDebugInst : core.fmt.Debug P) (self : VouchAndRung P)
  (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ corefmtDebugInst self.vouch
  let dyn1 := Dyn.mk _ (core.fmt.DebugShared Rung.Insts.CoreFmtDebug) self.rung
  core.fmt.Formatter.debug_struct_field2_finish f (toStr "VouchAndRung") (toStr
    "vouch") dyn (toStr "rung") dyn1

/-- Trait implementation: [census::{impl core::fmt::Debug for census::VouchAndRung<P>}]
    Source: 'census/src/lib.rs', lines 45:9-45:14 -/
@[reducible]
def VouchAndRung.Insts.CoreFmtDebug {P : Type} (corefmtDebugInst :
  core.fmt.Debug P) : core.fmt.Debug (VouchAndRung P) := {
  fmt := VouchAndRung.Insts.CoreFmtDebug.fmt corefmtDebugInst
}

/-- [census::{impl core::clone::Clone for census::VouchAndRung<P>}::clone]:
    Source: 'census/src/lib.rs', lines 45:16-45:21
    Visibility: public -/
def VouchAndRung.Insts.CoreCloneClone.clone
  {P : Type} (corecloneCloneInst : core.clone.Clone P) (self : VouchAndRung P)
  :
  Result (VouchAndRung P)
  := do
  let t ← corecloneCloneInst.clone self.vouch
  let r ← Rung.Insts.CoreCloneClone.clone self.rung
  ok { vouch := t, rung := r }

/-- Trait implementation: [census::{impl core::clone::Clone for census::VouchAndRung<P>}]
    Source: 'census/src/lib.rs', lines 45:16-45:21 -/
@[reducible]
def VouchAndRung.Insts.CoreCloneClone {P : Type} (corecloneCloneInst :
  core.clone.Clone P) : core.clone.Clone (VouchAndRung P) := {
  clone := VouchAndRung.Insts.CoreCloneClone.clone corecloneCloneInst
}

/-- Trait implementation: [census::{impl core::marker::Copy for census::VouchAndRung<P>}]
    Source: 'census/src/lib.rs', lines 45:23-45:27 -/
@[reducible]
def VouchAndRung.Insts.CoreMarkerCopy {P : Type} (coremarkerCopyInst :
  core.marker.Copy P) : core.marker.Copy (VouchAndRung P) := {
  cloneInst := VouchAndRung.Insts.CoreCloneClone coremarkerCopyInst.cloneInst
}

/-- Trait implementation: [census::{impl core::marker::StructuralPartialEq for census::VouchAndRung<P>}]
    Source: 'census/src/lib.rs', lines 45:29-45:38 -/
@[reducible]
def VouchAndRung.Insts.CoreMarkerStructuralPartialEq (P : Type) :
  core.marker.StructuralPartialEq (VouchAndRung P) := {
}

/-- [census::{impl core::cmp::PartialEq<census::VouchAndRung<P>> for census::VouchAndRung<P>}::eq]:
    Source: 'census/src/lib.rs', lines 45:29-45:38
    Visibility: public -/
def VouchAndRung.Insts.CoreCmpPartialEqVouchAndRung.eq
  {P : Type} (corecmpPartialEqInst : core.cmp.PartialEq P P)
  (self : VouchAndRung P) (other : VouchAndRung P) :
  Result Bool
  := do
  let b ← corecmpPartialEqInst.eq self.vouch other.vouch
  if b
  then Rung.Insts.CoreCmpPartialEqRung.eq self.rung other.rung
  else ok false

/-- Trait implementation: [census::{impl core::cmp::PartialEq<census::VouchAndRung<P>> for census::VouchAndRung<P>}]
    Source: 'census/src/lib.rs', lines 45:29-45:38 -/
@[reducible]
impl_def VouchAndRung.Insts.CoreCmpPartialEqVouchAndRung {P : Type}
  (corecmpPartialEqInst : core.cmp.PartialEq P P) : core.cmp.PartialEq
  (VouchAndRung P) (VouchAndRung P) := {
  eq := VouchAndRung.Insts.CoreCmpPartialEqVouchAndRung.eq corecmpPartialEqInst
  ne := core.cmp.PartialEq.ne.trait_default
    (VouchAndRung.Insts.CoreCmpPartialEqVouchAndRung corecmpPartialEqInst)
}

/-- [census::{impl core::cmp::Eq for census::VouchAndRung<P>}::assert_fields_are_eq]:
    Source: 'census/src/lib.rs', lines 45:40-45:42
    Visibility: public -/
def VouchAndRung.Insts.CoreCmpEq.assert_fields_are_eq
  {P : Type} (corecmpEqInst : core.cmp.Eq P) (self : VouchAndRung P) :
  Result Unit
  := do
  ok ()

/-- Trait implementation: [census::{impl core::cmp::Eq for census::VouchAndRung<P>}]
    Source: 'census/src/lib.rs', lines 45:40-45:42 -/
@[reducible]
def VouchAndRung.Insts.CoreCmpEq {P : Type} (corecmpEqInst : core.cmp.Eq P) :
  core.cmp.Eq (VouchAndRung P) := {
  partialEqInst := VouchAndRung.Insts.CoreCmpPartialEqVouchAndRung
    corecmpEqInst.partialEqInst
  assert_fields_are_eq := VouchAndRung.Insts.CoreCmpEq.assert_fields_are_eq
    corecmpEqInst
}

/-- [census::{census::Claim<census::ObservationTier, P>}::observed]:
    Source: 'census/src/lib.rs', lines 53:4-58:5
    Visibility: public -/
def ClaimObservationTierP.observed
  {P : Type} (payload : P) : Result (Claim ObservationTier P) := do
  ok { payload, _tier := () }

/-- [census::{census::Claim<census::ObservationTier, P>}::observation]:
    Source: 'census/src/lib.rs', lines 61:4-63:5
    Visibility: public -/
def ClaimObservationTierP.observation
  {P : Type} (self : Claim ObservationTier P) : Result P := do
  ok self.payload

/-- [census::{census::Claim<census::VouchTier, census::VouchAndRung<P>>}::vouched]:
    Source: 'census/src/lib.rs', lines 68:4-73:5
    Visibility: public -/
def ClaimVouchTierVouchAndRung.vouched
  {P : Type} (vouch : P) (rung : Rung) :
  Result (Claim VouchTier (VouchAndRung P))
  := do
  ok { payload := { vouch, rung }, _tier := () }

/-- [census::{census::Claim<census::VouchTier, census::VouchAndRung<P>>}::into_vouch]:
    Source: 'census/src/lib.rs', lines 76:4-78:5
    Visibility: public -/
def ClaimVouchTierVouchAndRung.into_vouch
  {P : Type} (self : Claim VouchTier (VouchAndRung P)) : Result P := do
  ok self.payload.vouch

/-- [census::VOUCH_SITE]
    Source: 'census/src/lib.rs', lines 85:0-85:50 -/
@[global_simps, irreducible]
def VOUCH_SITE : Str := toStr "systemctl.oracle.sh:12"

/-- [census::vouch_a_site]:
    Source: 'census/src/lib.rs', lines 87:0-89:1
    Visibility: public -/
def vouch_a_site : Result (Claim VouchTier (VouchAndRung Str)) := do
  ClaimVouchTierVouchAndRung.vouched VOUCH_SITE Rung.Both

/-- [census::{impl core::fmt::Debug for census::SelectorId}::fmt]:
    Source: 'census/src/lib.rs', lines 92:9-92:14
    Visibility: public -/
def SelectorId.Insts.CoreFmtDebug.fmt
  (self : SelectorId) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU32) self
  core.fmt.Formatter.debug_tuple_field1_finish f (toStr "SelectorId") dyn

/-- Trait implementation: [census::{impl core::fmt::Debug for census::SelectorId}]
    Source: 'census/src/lib.rs', lines 92:9-92:14 -/
@[reducible]
def SelectorId.Insts.CoreFmtDebug : core.fmt.Debug SelectorId := {
  fmt := SelectorId.Insts.CoreFmtDebug.fmt
}

/-- [census::{impl core::clone::Clone for census::SelectorId}::clone]:
    Source: 'census/src/lib.rs', lines 92:16-92:21
    Visibility: public -/
def SelectorId.Insts.CoreCloneClone.clone
  (self : SelectorId) : Result SelectorId := do
  ok self

/-- Trait implementation: [census::{impl core::clone::Clone for census::SelectorId}]
    Source: 'census/src/lib.rs', lines 92:16-92:21 -/
@[reducible]
def SelectorId.Insts.CoreCloneClone : core.clone.Clone SelectorId := {
  clone := SelectorId.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [census::{impl core::marker::Copy for census::SelectorId}]
    Source: 'census/src/lib.rs', lines 92:23-92:27 -/
@[reducible]
def SelectorId.Insts.CoreMarkerCopy : core.marker.Copy SelectorId := {
  cloneInst := SelectorId.Insts.CoreCloneClone
}

/-- Trait implementation: [census::{impl core::marker::StructuralPartialEq for census::SelectorId}]
    Source: 'census/src/lib.rs', lines 92:29-92:38 -/
@[reducible]
def SelectorId.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq SelectorId := {
}

/-- [census::{impl core::cmp::PartialEq<census::SelectorId> for census::SelectorId}::eq]:
    Source: 'census/src/lib.rs', lines 92:29-92:38
    Visibility: public -/
def SelectorId.Insts.CoreCmpPartialEqSelectorId.eq
  (self : SelectorId) (other : SelectorId) : Result Bool := do
  ok (self = other)

/-- Trait implementation: [census::{impl core::cmp::PartialEq<census::SelectorId> for census::SelectorId}]
    Source: 'census/src/lib.rs', lines 92:29-92:38 -/
@[reducible]
impl_def SelectorId.Insts.CoreCmpPartialEqSelectorId : core.cmp.PartialEq
  SelectorId SelectorId := {
  eq := SelectorId.Insts.CoreCmpPartialEqSelectorId.eq
  ne := core.cmp.PartialEq.ne.trait_default
    SelectorId.Insts.CoreCmpPartialEqSelectorId
}

/-- [census::{impl core::cmp::Eq for census::SelectorId}::assert_fields_are_eq]:
    Source: 'census/src/lib.rs', lines 92:40-92:42
    Visibility: public -/
def SelectorId.Insts.CoreCmpEq.assert_fields_are_eq
  (self : SelectorId) : Result Unit := do
  ok ()

/-- Trait implementation: [census::{impl core::cmp::Eq for census::SelectorId}]
    Source: 'census/src/lib.rs', lines 92:40-92:42 -/
@[reducible]
def SelectorId.Insts.CoreCmpEq : core.cmp.Eq SelectorId := {
  partialEqInst := SelectorId.Insts.CoreCmpPartialEqSelectorId
  assert_fields_are_eq := SelectorId.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [census::{impl core::cmp::Ord for census::SelectorId}::cmp]:
    Source: 'census/src/lib.rs', lines 92:56-92:59
    Visibility: public -/
def SelectorId.Insts.CoreCmpOrd.cmp
  (self : SelectorId) (other : SelectorId) : Result Ordering := do
  ok (core.cmp.impls.OrdU32.cmp self other)

/-- [census::{impl core::cmp::PartialOrd<census::SelectorId> for census::SelectorId}::partial_cmp]:
    Source: 'census/src/lib.rs', lines 92:44-92:54
    Visibility: public -/
def SelectorId.Insts.CoreCmpPartialOrdSelectorId.partial_cmp
  (self : SelectorId) (other : SelectorId) : Result (Option Ordering) := do
  let o ← SelectorId.Insts.CoreCmpOrd.cmp self other
  ok (some o)

/-- Trait implementation: [census::{impl core::cmp::PartialOrd<census::SelectorId> for census::SelectorId}]
    Source: 'census/src/lib.rs', lines 92:44-92:54 -/
@[reducible]
def SelectorId.Insts.CoreCmpPartialOrdSelectorId : core.cmp.PartialOrd
  SelectorId SelectorId := {
  partialEqInst := SelectorId.Insts.CoreCmpPartialEqSelectorId
  partial_cmp := SelectorId.Insts.CoreCmpPartialOrdSelectorId.partial_cmp
}

/-- Trait implementation: [census::{impl core::cmp::Ord for census::SelectorId}]
    Source: 'census/src/lib.rs', lines 92:56-92:59 -/
@[reducible]
def SelectorId.Insts.CoreCmpOrd : core.cmp.Ord SelectorId := {
  eqInst := SelectorId.Insts.CoreCmpEq
  partialOrdInst := SelectorId.Insts.CoreCmpPartialOrdSelectorId
  cmp := SelectorId.Insts.CoreCmpOrd.cmp
}

/-- [census::{impl core::hash::Hash for census::SelectorId}::hash]:
    Source: 'census/src/lib.rs', lines 92:61-92:65
    Visibility: public -/
def SelectorId.Insts.CoreHashHash.hash
  {__H : Type} (corehashHasherInst : core.hash.Hasher __H) (self : SelectorId)
  (state : __H) :
  Result __H
  := do
  U32.Insts.CoreHashHash.hash corehashHasherInst self state

/-- Trait implementation: [census::{impl core::hash::Hash for census::SelectorId}]
    Source: 'census/src/lib.rs', lines 92:61-92:65 -/
@[reducible]
def SelectorId.Insts.CoreHashHash : core.hash.Hash SelectorId := {
  hash := fun {H : Type} (corehashHasherInst : core.hash.Hasher H) =>
    SelectorId.Insts.CoreHashHash.hash corehashHasherInst
}

/-- [census::{impl core::fmt::Debug for census::KindId}::fmt]:
    Source: 'census/src/lib.rs', lines 95:9-95:14
    Visibility: public -/
def KindId.Insts.CoreFmtDebug.fmt
  (self : KindId) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU32) self
  core.fmt.Formatter.debug_tuple_field1_finish f (toStr "KindId") dyn

/-- Trait implementation: [census::{impl core::fmt::Debug for census::KindId}]
    Source: 'census/src/lib.rs', lines 95:9-95:14 -/
@[reducible]
def KindId.Insts.CoreFmtDebug : core.fmt.Debug KindId := {
  fmt := KindId.Insts.CoreFmtDebug.fmt
}

/-- [census::{impl core::clone::Clone for census::KindId}::clone]:
    Source: 'census/src/lib.rs', lines 95:16-95:21
    Visibility: public -/
def KindId.Insts.CoreCloneClone.clone (self : KindId) : Result KindId := do
  ok self

/-- Trait implementation: [census::{impl core::clone::Clone for census::KindId}]
    Source: 'census/src/lib.rs', lines 95:16-95:21 -/
@[reducible]
def KindId.Insts.CoreCloneClone : core.clone.Clone KindId := {
  clone := KindId.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [census::{impl core::marker::Copy for census::KindId}]
    Source: 'census/src/lib.rs', lines 95:23-95:27 -/
@[reducible]
def KindId.Insts.CoreMarkerCopy : core.marker.Copy KindId := {
  cloneInst := KindId.Insts.CoreCloneClone
}

/-- Trait implementation: [census::{impl core::marker::StructuralPartialEq for census::KindId}]
    Source: 'census/src/lib.rs', lines 95:29-95:38 -/
@[reducible]
def KindId.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq KindId := {
}

/-- [census::{impl core::cmp::PartialEq<census::KindId> for census::KindId}::eq]:
    Source: 'census/src/lib.rs', lines 95:29-95:38
    Visibility: public -/
def KindId.Insts.CoreCmpPartialEqKindId.eq
  (self : KindId) (other : KindId) : Result Bool := do
  ok (self = other)

/-- Trait implementation: [census::{impl core::cmp::PartialEq<census::KindId> for census::KindId}]
    Source: 'census/src/lib.rs', lines 95:29-95:38 -/
@[reducible]
impl_def KindId.Insts.CoreCmpPartialEqKindId : core.cmp.PartialEq KindId KindId
  := {
  eq := KindId.Insts.CoreCmpPartialEqKindId.eq
  ne := core.cmp.PartialEq.ne.trait_default KindId.Insts.CoreCmpPartialEqKindId
}

/-- [census::{impl core::cmp::Eq for census::KindId}::assert_fields_are_eq]:
    Source: 'census/src/lib.rs', lines 95:40-95:42
    Visibility: public -/
def KindId.Insts.CoreCmpEq.assert_fields_are_eq
  (self : KindId) : Result Unit := do
  ok ()

/-- Trait implementation: [census::{impl core::cmp::Eq for census::KindId}]
    Source: 'census/src/lib.rs', lines 95:40-95:42 -/
@[reducible]
def KindId.Insts.CoreCmpEq : core.cmp.Eq KindId := {
  partialEqInst := KindId.Insts.CoreCmpPartialEqKindId
  assert_fields_are_eq := KindId.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [census::{impl core::cmp::Ord for census::KindId}::cmp]:
    Source: 'census/src/lib.rs', lines 95:56-95:59
    Visibility: public -/
def KindId.Insts.CoreCmpOrd.cmp
  (self : KindId) (other : KindId) : Result Ordering := do
  ok (core.cmp.impls.OrdU32.cmp self other)

/-- [census::{impl core::cmp::PartialOrd<census::KindId> for census::KindId}::partial_cmp]:
    Source: 'census/src/lib.rs', lines 95:44-95:54
    Visibility: public -/
def KindId.Insts.CoreCmpPartialOrdKindId.partial_cmp
  (self : KindId) (other : KindId) : Result (Option Ordering) := do
  let o ← KindId.Insts.CoreCmpOrd.cmp self other
  ok (some o)

/-- Trait implementation: [census::{impl core::cmp::PartialOrd<census::KindId> for census::KindId}]
    Source: 'census/src/lib.rs', lines 95:44-95:54 -/
@[reducible]
def KindId.Insts.CoreCmpPartialOrdKindId : core.cmp.PartialOrd KindId KindId
  := {
  partialEqInst := KindId.Insts.CoreCmpPartialEqKindId
  partial_cmp := KindId.Insts.CoreCmpPartialOrdKindId.partial_cmp
}

/-- Trait implementation: [census::{impl core::cmp::Ord for census::KindId}]
    Source: 'census/src/lib.rs', lines 95:56-95:59 -/
@[reducible]
def KindId.Insts.CoreCmpOrd : core.cmp.Ord KindId := {
  eqInst := KindId.Insts.CoreCmpEq
  partialOrdInst := KindId.Insts.CoreCmpPartialOrdKindId
  cmp := KindId.Insts.CoreCmpOrd.cmp
}

/-- [census::{impl core::hash::Hash for census::KindId}::hash]:
    Source: 'census/src/lib.rs', lines 95:61-95:65
    Visibility: public -/
def KindId.Insts.CoreHashHash.hash
  {__H : Type} (corehashHasherInst : core.hash.Hasher __H) (self : KindId)
  (state : __H) :
  Result __H
  := do
  U32.Insts.CoreHashHash.hash corehashHasherInst self state

/-- Trait implementation: [census::{impl core::hash::Hash for census::KindId}]
    Source: 'census/src/lib.rs', lines 95:61-95:65 -/
@[reducible]
def KindId.Insts.CoreHashHash : core.hash.Hash KindId := {
  hash := fun {H : Type} (corehashHasherInst : core.hash.Hasher H) =>
    KindId.Insts.CoreHashHash.hash corehashHasherInst
}

/-- [census::{impl core::default::Default for census::KindId}::default]:
    Source: 'census/src/lib.rs', lines 95:67-95:74
    Visibility: public -/
def KindId.Insts.CoreDefaultDefault.default : Result KindId := do
  ok (core.default.DefaultU32.default)

/-- Trait implementation: [census::{impl core::default::Default for census::KindId}]
    Source: 'census/src/lib.rs', lines 95:67-95:74 -/
@[reducible]
def KindId.Insts.CoreDefaultDefault : core.default.Default KindId := {
  default := KindId.Insts.CoreDefaultDefault.default
}

/-- [census::{impl core::fmt::Debug for census::Coord}::fmt]:
    Source: 'census/src/lib.rs', lines 98:9-98:14
    Visibility: public -/
def Coord.Insts.CoreFmtDebug.fmt
  (self : Coord) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ KindId.Insts.CoreFmtDebug self.kind
  let dyn1 := Dyn.mk _ core.fmt.DebugU32 self.entity
  let dyn2 :=
    Dyn.mk _ (core.fmt.DebugShared (core.option.Option.Insts.CoreFmtDebug
      SelectorId.Insts.CoreFmtDebug)) self.selector
  core.fmt.Formatter.debug_struct_field3_finish f (toStr "Coord") (toStr
    "kind") dyn (toStr "entity") dyn1 (toStr "selector") dyn2

/-- Trait implementation: [census::{impl core::fmt::Debug for census::Coord}]
    Source: 'census/src/lib.rs', lines 98:9-98:14 -/
@[reducible]
def Coord.Insts.CoreFmtDebug : core.fmt.Debug Coord := {
  fmt := Coord.Insts.CoreFmtDebug.fmt
}

/-- [census::{impl core::clone::Clone for census::Coord}::clone]:
    Source: 'census/src/lib.rs', lines 98:16-98:21
    Visibility: public -/
def Coord.Insts.CoreCloneClone.clone (self : Coord) : Result Coord := do
  ok self

/-- Trait implementation: [census::{impl core::clone::Clone for census::Coord}]
    Source: 'census/src/lib.rs', lines 98:16-98:21 -/
@[reducible]
def Coord.Insts.CoreCloneClone : core.clone.Clone Coord := {
  clone := Coord.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [census::{impl core::marker::Copy for census::Coord}]
    Source: 'census/src/lib.rs', lines 98:23-98:27 -/
@[reducible]
def Coord.Insts.CoreMarkerCopy : core.marker.Copy Coord := {
  cloneInst := Coord.Insts.CoreCloneClone
}

/-- Trait implementation: [census::{impl core::marker::StructuralPartialEq for census::Coord}]
    Source: 'census/src/lib.rs', lines 98:29-98:38 -/
@[reducible]
def Coord.Insts.CoreMarkerStructuralPartialEq : core.marker.StructuralPartialEq
  Coord := {
}

/-- [census::{impl core::cmp::PartialEq<census::Coord> for census::Coord}::eq]:
    Source: 'census/src/lib.rs', lines 98:29-98:38
    Visibility: public -/
def Coord.Insts.CoreCmpPartialEqCoord.eq
  (self : Coord) (other : Coord) : Result Bool := do
  if self.entity = other.entity
  then
    let b ← KindId.Insts.CoreCmpPartialEqKindId.eq self.kind other.kind
    if b
    then
      core.option.Option.Insts.CoreCmpPartialEqOption.eq
        SelectorId.Insts.CoreCmpPartialEqSelectorId self.selector
        other.selector
    else ok false
  else ok false

/-- Trait implementation: [census::{impl core::cmp::PartialEq<census::Coord> for census::Coord}]
    Source: 'census/src/lib.rs', lines 98:29-98:38 -/
@[reducible]
impl_def Coord.Insts.CoreCmpPartialEqCoord : core.cmp.PartialEq Coord Coord
  := {
  eq := Coord.Insts.CoreCmpPartialEqCoord.eq
  ne := core.cmp.PartialEq.ne.trait_default Coord.Insts.CoreCmpPartialEqCoord
}

/-- [census::{impl core::cmp::Eq for census::Coord}::assert_fields_are_eq]:
    Source: 'census/src/lib.rs', lines 98:40-98:42
    Visibility: public -/
def Coord.Insts.CoreCmpEq.assert_fields_are_eq
  (self : Coord) : Result Unit := do
  ok ()

/-- Trait implementation: [census::{impl core::cmp::Eq for census::Coord}]
    Source: 'census/src/lib.rs', lines 98:40-98:42 -/
@[reducible]
def Coord.Insts.CoreCmpEq : core.cmp.Eq Coord := {
  partialEqInst := Coord.Insts.CoreCmpPartialEqCoord
  assert_fields_are_eq := Coord.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [census::{impl core::fmt::Debug for census::Compare}::fmt]:
    Source: 'census/src/lib.rs', lines 107:9-107:14
    Visibility: public -/
def Compare.Insts.CoreFmtDebug.fmt
  (self : Compare) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | Compare.Same => core.fmt.Formatter.write_str f (toStr "Same")
  | Compare.ProvablyDisjoint =>
    core.fmt.Formatter.write_str f (toStr "ProvablyDisjoint")
  | Compare.Unknown => core.fmt.Formatter.write_str f (toStr "Unknown")

/-- Trait implementation: [census::{impl core::fmt::Debug for census::Compare}]
    Source: 'census/src/lib.rs', lines 107:9-107:14 -/
@[reducible]
def Compare.Insts.CoreFmtDebug : core.fmt.Debug Compare := {
  fmt := Compare.Insts.CoreFmtDebug.fmt
}

/-- [census::{impl core::clone::Clone for census::Compare}::clone]:
    Source: 'census/src/lib.rs', lines 107:16-107:21
    Visibility: public -/
def Compare.Insts.CoreCloneClone.clone (self : Compare) : Result Compare := do
  ok self

/-- Trait implementation: [census::{impl core::clone::Clone for census::Compare}]
    Source: 'census/src/lib.rs', lines 107:16-107:21 -/
@[reducible]
def Compare.Insts.CoreCloneClone : core.clone.Clone Compare := {
  clone := Compare.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [census::{impl core::marker::Copy for census::Compare}]
    Source: 'census/src/lib.rs', lines 107:23-107:27 -/
@[reducible]
def Compare.Insts.CoreMarkerCopy : core.marker.Copy Compare := {
  cloneInst := Compare.Insts.CoreCloneClone
}

/-- Trait implementation: [census::{impl core::marker::StructuralPartialEq for census::Compare}]
    Source: 'census/src/lib.rs', lines 107:29-107:38 -/
@[reducible]
def Compare.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq Compare := {
}

/-- [census::{impl core::cmp::PartialEq<census::Compare> for census::Compare}::eq]:
    Source: 'census/src/lib.rs', lines 107:29-107:38
    Visibility: public -/
def Compare.Insts.CoreCmpPartialEqCompare.eq
  (self : Compare) (other : Compare) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [census::{impl core::cmp::PartialEq<census::Compare> for census::Compare}]
    Source: 'census/src/lib.rs', lines 107:29-107:38 -/
@[reducible]
impl_def Compare.Insts.CoreCmpPartialEqCompare : core.cmp.PartialEq Compare
  Compare := {
  eq := Compare.Insts.CoreCmpPartialEqCompare.eq
  ne := core.cmp.PartialEq.ne.trait_default
    Compare.Insts.CoreCmpPartialEqCompare
}

/-- [census::{impl core::cmp::Eq for census::Compare}::assert_fields_are_eq]:
    Source: 'census/src/lib.rs', lines 107:40-107:42
    Visibility: public -/
def Compare.Insts.CoreCmpEq.assert_fields_are_eq
  (self : Compare) : Result Unit := do
  ok ()

/-- Trait implementation: [census::{impl core::cmp::Eq for census::Compare}]
    Source: 'census/src/lib.rs', lines 107:40-107:42 -/
@[reducible]
def Compare.Insts.CoreCmpEq : core.cmp.Eq Compare := {
  partialEqInst := Compare.Insts.CoreCmpPartialEqCompare
  assert_fields_are_eq := Compare.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [census::selector_covers]:
    Source: 'census/src/lib.rs', lines 117:0-123:1
    Visibility: public -/
def selector_covers
  (a : Option SelectorId) (b : Option SelectorId) : Result Bool := do
  match a with
  | none => ok true
  | some x =>
    match b with
    | none => ok true
    | some y => SelectorId.Insts.CoreCmpPartialEqSelectorId.eq x y

/-- [census::compare]:
    Source: 'census/src/lib.rs', lines 126:0-138:1
    Visibility: public -/
def compare (a : Coord) (b : Coord) : Result Compare := do
  let b1 ←
    core.cmp.PartialEq.ne.trait_default KindId.Insts.CoreCmpPartialEqKindId
      a.kind b.kind
  if b1
  then ok Compare.ProvablyDisjoint
  else
    if a.entity != b.entity
    then ok Compare.Unknown
    else
      let b2 ← selector_covers a.selector b.selector
      if b2
      then ok Compare.Same
      else ok Compare.ProvablyDisjoint

end census
