-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [census]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import Census.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open census

/-- [core::fmt::{impl core::fmt::Debug for core::marker::PhantomData<T>}::fmt]:
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 3136:4-3136:50
    Name pattern: [core::fmt::{core::fmt::Debug<core::marker::PhantomData<@T>>}::fmt]
    Visibility: public -/
@[rust_fun "core::fmt::{core::fmt::Debug<core::marker::PhantomData<@T>>}::fmt"]
axiom core.marker.PhantomData.Insts.CoreFmtDebug.fmt
  {T : Type} :
  core.marker.PhantomData T → core.fmt.Formatter → Result
    ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)

/-- [core::hash::impls::{impl core::hash::Hash for u32}::hash]:
    Source: '/rustc/library/core/src/hash/mod.rs', lines 812:16-812:56
    Name pattern: [core::hash::impls::{core::hash::Hash<u32>}::hash]
    Visibility: public -/
@[rust_fun "core::hash::impls::{core::hash::Hash<u32>}::hash"]
axiom U32.Insts.CoreHashHash.hash
  {H : Type} (HasherInst : core.hash.Hasher H) : Std.U32 → H → Result H

/-- [core::marker::{impl core::cmp::PartialEq<core::marker::PhantomData<T>> for core::marker::PhantomData<T>}::eq]:
    Source: '/rustc/library/core/src/marker.rs', lines 821:4-821:49
    Name pattern: [core::marker::{core::cmp::PartialEq<core::marker::PhantomData<@T>, core::marker::PhantomData<@T>>}::eq]
    Visibility: public -/
@[rust_fun
  "core::marker::{core::cmp::PartialEq<core::marker::PhantomData<@T>, core::marker::PhantomData<@T>>}::eq"]
axiom core.marker.PhantomData.Insts.CoreCmpPartialEqPhantomData.eq
  {T : Type} :
  core.marker.PhantomData T → core.marker.PhantomData T → Result Bool

/-- [core::marker::{impl core::clone::Clone for core::marker::PhantomData<T>}::clone]:
    Source: '/rustc/library/core/src/marker.rs', lines 848:4-848:27
    Name pattern: [core::marker::{core::clone::Clone<core::marker::PhantomData<@T>>}::clone]
    Visibility: public -/
@[rust_fun
  "core::marker::{core::clone::Clone<core::marker::PhantomData<@T>>}::clone"]
axiom core.marker.PhantomData.Insts.CoreCloneClone.clone
  {T : Type} : core.marker.PhantomData T → Result (core.marker.PhantomData T)

/-- [core::option::{impl core::fmt::Debug for core::option::Option<T>}::fmt]:
    Source: '/rustc/library/core/src/option.rs', lines 591:15-591:20
    Name pattern: [core::option::{core::fmt::Debug<core::option::Option<@T>>}::fmt]
    Visibility: public -/
@[rust_fun "core::option::{core::fmt::Debug<core::option::Option<@T>>}::fmt"]
axiom core.option.Option.Insts.CoreFmtDebug.fmt
  {T : Type} (fmtDebugInst : core.fmt.Debug T) :
  Option T → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- [core::option::{impl core::cmp::PartialEq<core::option::Option<T>> for core::option::Option<T>}::eq]:
    Source: '/rustc/library/core/src/option.rs', lines 2440:4-2440:38
    Name pattern: [core::option::{core::cmp::PartialEq<core::option::Option<@T>, core::option::Option<@T>>}::eq]
    Visibility: public -/
@[rust_fun
  "core::option::{core::cmp::PartialEq<core::option::Option<@T>, core::option::Option<@T>>}::eq"]
axiom core.option.Option.Insts.CoreCmpPartialEqOption.eq
  {T : Type} (cmpPartialEqInst : core.cmp.PartialEq T T) :
  Option T → Option T → Result Bool

