-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [census]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace census

/-- [core::marker::PhantomData]
    Source: '/rustc/library/core/src/marker.rs', lines 811:0-811:39
    Name pattern: [core::marker::PhantomData]
    Visibility: public -/
@[reducible, rust_type "core::marker::PhantomData"]
def core.marker.PhantomData (T : Type) := Unit

/-- Trait declaration: [census::sealed::Sealed]
    Source: 'census/src/lib.rs', lines 12:4-12:23
    Visibility: public -/
structure sealed.Sealed (Self : Type) where

/-- Trait declaration: [census::Tier]
    Source: 'census/src/lib.rs', lines 15:0-15:33
    Visibility: public -/
structure Tier (Self : Type) where
  sealedSealedInst : sealed.Sealed Self

/-- [census::ObservationTier]
    Source: 'census/src/lib.rs', lines 18:0-18:27
    Visibility: public -/
inductive ObservationTier where

/-- [census::VouchTier]
    Source: 'census/src/lib.rs', lines 21:0-21:21
    Visibility: public -/
inductive VouchTier where

/-- [census::Rung]
    Source: 'census/src/lib.rs', lines 29:0-31:1
    Visibility: public -/
@[discriminant isize]
inductive Rung where
| Both : Rung

/-- [census::Claim]
    Source: 'census/src/lib.rs', lines 37:0-40:1
    Visibility: public -/
structure Claim (T : Type) (P : Type) where
  payload : P
  _tier : core.marker.PhantomData T

/-- [census::VouchAndRung]
    Source: 'census/src/lib.rs', lines 46:0-49:1
    Visibility: public -/
structure VouchAndRung (P : Type) where
  vouch : P
  rung : Rung

/-- [census::SelectorId]
    Source: 'census/src/lib.rs', lines 93:0-93:27
    Visibility: public -/
@[reducible]
def SelectorId := Std.U32

/-- [census::KindId]
    Source: 'census/src/lib.rs', lines 96:0-96:23
    Visibility: public -/
@[reducible]
def KindId := Std.U32

/-- [census::Coord]
    Source: 'census/src/lib.rs', lines 99:0-103:1
    Visibility: public -/
structure Coord where
  kind : KindId
  entity : Std.U32
  selector : Option SelectorId

/-- [census::Compare]
    Source: 'census/src/lib.rs', lines 108:0-112:1
    Visibility: public -/
@[discriminant isize]
inductive Compare where
| Same : Compare
| ProvablyDisjoint : Compare
| Unknown : Compare

end census
