-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lattice]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import Lattice.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open lattice

/-- [core::fmt::{core::fmt::Formatter<'a>}::debug_tuple_field2_finish]:
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 2627:4-2632:15
    Name pattern: [core::fmt::{core::fmt::Formatter<'a>}::debug_tuple_field2_finish]
    Visibility: public -/
@[rust_fun "core::fmt::{core::fmt::Formatter<'a>}::debug_tuple_field2_finish"]
axiom core.fmt.Formatter.debug_tuple_field2_finish
  :
  core.fmt.Formatter → Str → Dyn (fun _dyn => core.fmt.Debug _dyn) → Dyn
    (fun _dyn => core.fmt.Debug _dyn) → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- [core::fmt::{impl core::fmt::Debug for (U, T)}::fmt]:
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 3089:16-3089:62
    Name pattern: [core::fmt::{core::fmt::Debug<(@U, @T)>}::fmt]
    Visibility: public -/
@[rust_fun "core::fmt::{core::fmt::Debug<(@U, @T)>}::fmt"]
axiom Pair.Insts.CoreFmtDebug.fmt
  {U : Type} {T : Type} (DebugInst : core.fmt.Debug U) (DebugInst1 :
  core.fmt.Debug T) :
  (U × T) → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- [core::num::{usize}::saturating_mul]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 2516:8-2516:60
    Name pattern: [core::num::{usize}::saturating_mul]
    Visibility: public -/
@[rust_fun "core::num::{usize}::saturating_mul"]
axiom core.num.Usize.saturating_mul
  : Std.Usize → Std.Usize → Result Std.Usize

/-- [core::tuple::{impl core::cmp::PartialEq<(U, T)> for (U, T)}::ne]:
    Source: '/rustc/library/core/src/tuple.rs', lines 34:16-34:55
    Name pattern: [core::tuple::{core::cmp::PartialEq<(@U, @T), (@U, @T)>}::ne]
    Visibility: public -/
@[rust_fun "core::tuple::{core::cmp::PartialEq<(@U, @T), (@U, @T)>}::ne"]
axiom Pair.Insts.CoreCmpPartialEqPair.ne
  {U : Type} {T : Type} (cmpPartialEqInst : core.cmp.PartialEq U U)
  (cmpPartialEqInst1 : core.cmp.PartialEq T T) :
  (U × T) → (U × T) → Result Bool

/-- [core::tuple::{impl core::cmp::PartialEq<(U, T)> for (U, T)}::eq]:
    Source: '/rustc/library/core/src/tuple.rs', lines 30:16-30:55
    Name pattern: [core::tuple::{core::cmp::PartialEq<(@U, @T), (@U, @T)>}::eq]
    Visibility: public -/
@[rust_fun "core::tuple::{core::cmp::PartialEq<(@U, @T), (@U, @T)>}::eq"]
axiom Pair.Insts.CoreCmpPartialEqPair.eq
  {U : Type} {T : Type} (cmpPartialEqInst : core.cmp.PartialEq U U)
  (cmpPartialEqInst1 : core.cmp.PartialEq T T) :
  (U × T) → (U × T) → Result Bool

/-- [alloc::vec::{alloc::vec::Vec<T>}::remove]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 2401:4-2401:47
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::remove]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::remove"]
axiom alloc.vec.Vec.remove
  {T : Type} (A : Type) :
  alloc.vec.Vec T → Std.Usize → Result (T × (alloc.vec.Vec T))

