-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [strings]: function definitions
import Aeneas
import Strings.Types
import Strings.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace strings

/-- [strings::return_literal]:
    Source: 'strings/src/lib.rs', lines 7:0-9:1
    Visibility: public -/
def return_literal : Result Str := do
  sorry

/-- [strings::SLUG]
    Source: 'strings/src/lib.rs', lines 11:0-11:48
    Visibility: public -/
@[global_simps, irreducible] def SLUG : Str := toStr "systemctl.oracle.sh:12"

/-- [strings::return_const]:
    Source: 'strings/src/lib.rs', lines 13:0-15:1
    Visibility: public -/
def return_const : Result Str := do
  ok SLUG

/-- [strings::consume_str]:
    Source: 'strings/src/lib.rs', lines 17:0-19:1
    Visibility: public -/
def consume_str (s : Str) : Result Std.Usize := do
  core.str.Str.len s

/-- [strings::return_bytes]:
    Source: 'strings/src/lib.rs', lines 21:0-23:1
    Visibility: public -/
def return_bytes : Result (Slice Std.U8) := do
  sorry

end strings
