-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [strings]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import Strings.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open strings

/-- [core::str::{str}::len]:
    Source: '/rustc/library/core/src/str/mod.rs', lines 153:4-153:36
    Name pattern: [core::str::{str}::len]
    Visibility: public -/
@[rust_fun "core::str::{str}::len"]
axiom core.str.Str.len : Str → Result Std.Usize

