#!/bin/sh
# Regenerate every file under `renders/` from the current engine.
#
# WHY THIS EXISTS: the renders are the baselines `livetest` asserts its live plan summaries
# against, so they must be re-derivable on demand rather than hand-assembled once. The engine
# moves; a baseline nobody can reproduce is a baseline nobody can trust.
#
# EXECUTES NO BOOK AND NO ORACLE BYTES. `dorc probe` and `dorc plan` only render artifacts to
# stdout; neither this script nor they ever run one.
#
# usage: DORC=<path-to-dorc> ./render-baselines.sh        (run from anywhere)

set -eu

here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
root=$(CDPATH= cd -- "$here/../../.." && pwd)
dorc=${DORC:-$root/spike/target/debug/dorc}
DORC=$dorc
export DORC
kit=Research/trial/r26

work=${TMPDIR:-/tmp}/dorc-r26-renders.$$
mkdir -p "$work"

# The ceiling variant is the same book minus its single bare index-refresh, with its own framed
# records (removing L1 renumbers every site below it). Never committed — both exist only to measure
# what that one line costs — but built IN-TREE rather than under TMPDIR: the render names both
# paths, and a $$-stamped absolute temp path made this one render differ on every run and every
# machine, alone among the five.
ceiling=$here/.ceiling-book.sh
ceiling_records=$here/.ceiling-records.txt
trap 'rm -rf "$work"; rm -f "$ceiling" "$ceiling_records"' EXIT INT TERM
grep -v '^apt-get update$' "$here/smoke-book.sh" >"$ceiling"

render() {
   title=$1
   book=$2
   records=$3
   out=$4

   printf '# dorc plan -- %s\n' "$title"
   printf '#   dorc plan --book=%s --oracle-dir %s/oracles --results %s\n' "$book" "$kit" "$records"
   printf '# Regenerated by %s/render-baselines.sh; paths are worktree-root-relative.\n' "$kit"
   printf '\n===== stderr: diagnostics, why-lens, plan summary =====\n\n'
   "$dorc" plan --book="$book" --oracle-dir "$kit/oracles" --results "$records" --no-receipt \
      2>"$work/err" >"$work/out" || true
   cat "$work/err"
   printf '\n===== stdout: the plan artifact =====\n\n'
   cat "$work/out"
} >"$here/renders/$4"

cd "$root"

"$here/frame-records.sh" "$kit/smoke-book.sh" "$kit/oracles" "$kit/records/pristine.txt" \
   >"$here/records/pristine.framed.txt"
"$here/frame-records.sh" "$kit/smoke-book.sh" "$kit/oracles" "$kit/records/converged.txt" \
   >"$here/records/converged.framed.txt"

render 'PRISTINE world (hermetic; records hand-authored, nothing executed)' \
   "$kit/smoke-book.sh" "$kit/records/pristine.framed.txt" plan-pristine.txt
render 'CONVERGED world (hermetic; records hand-authored, nothing executed)' \
   "$kit/smoke-book.sh" "$kit/records/converged.framed.txt" plan-converged.txt

# The ceiling's site ids renumber (L1 removal shifts everything down), so its records are framed
# against its own book.
DORC=$dorc "$here/frame-records.sh" "$kit/.ceiling-book.sh" "$kit/oracles" \
   "$kit/records/ceiling.txt" >"$ceiling_records"
render 'CONVERGED world, CEILING VARIANT (the book minus its bare `apt-get update`)' \
   "$kit/.ceiling-book.sh" "$kit/.ceiling-records.txt" plan-ceiling-converged.txt

# `container-book.sh` — what `mise run livetest` drives. These two are the baselines the live loop
# asserts its summary COUNTS against, so they are the ones that must stay re-derivable.
"$here/frame-records.sh" "$kit/container-book.sh" "$kit/oracles" \
   "$kit/records/container-pristine.txt" >"$here/records/container-pristine.framed.txt"
"$here/frame-records.sh" "$kit/container-book.sh" "$kit/oracles" \
   "$kit/records/container-converged.txt" >"$here/records/container-converged.framed.txt"
render 'CONTAINER book, PRISTINE world (the livetest baseline for plan 1)' \
   "$kit/container-book.sh" "$kit/records/container-pristine.framed.txt" plan-container-pristine.txt
render 'CONTAINER book, CONVERGED world (the livetest baseline for plan 2)' \
   "$kit/container-book.sh" "$kit/records/container-converged.framed.txt" plan-container-converged.txt

printf 'renders refreshed:\n' >&2
grep -h 'plan-summary' "$here"/renders/*.txt >&2
