#!/bin/sh
# Regenerate every file under `renders/` from the current engine.
#
# WHY THIS EXISTS: the renders are the baselines `livetest` asserts its live plan summaries
# against, so they must be re-derivable on demand rather than hand-assembled once. The engine
# moves; a baseline nobody can reproduce is a baseline nobody can trust.
#
# EXECUTES NO BOOK AND NO ORACLE BYTES. `dorc probe` and `dorc plan` only render artifacts to
# stdout; neither this script nor they ever run one.
#
# usage: DORC=<path-to-dorc> ./render-baselines.sh        (run from anywhere)

set -eu

here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
root=$(CDPATH= cd -- "$here/../../.." && pwd)
dorc=${DORC:-$root/spike/target/debug/dorc}
DORC=$dorc
export DORC
kit=Research/trial/r26

work=${TMPDIR:-/tmp}/dorc-r26-renders.$$
mkdir -p "$work"
trap 'rm -rf "$work"' EXIT INT TERM

# The ceiling variant is the same book minus its single bare index-refresh. Never committed: it
# exists only to measure what that one line costs.
grep -v '^apt-get update$' "$here/smoke-book.sh" >"$work/ceiling-book.sh"

render() {
   title=$1
   book=$2
   records=$3
   out=$4

   printf '# dorc plan -- %s\n' "$title"
   printf '#   dorc plan --book=%s --oracle-dir %s/oracles --results %s\n' "$book" "$kit" "$records"
   printf '# Regenerated by %s/render-baselines.sh; paths are worktree-root-relative.\n' "$kit"
   printf '\n===== stderr: diagnostics, why-lens, plan summary =====\n\n'
   "$dorc" plan --book="$book" --oracle-dir "$kit/oracles" --results "$records" --no-whylog \
      2>"$work/err" >"$work/out" || true
   cat "$work/err"
   printf '\n===== stdout: the plan artifact =====\n\n'
   cat "$work/out"
} >"$here/renders/$4"

cd "$root"

"$here/frame-records.sh" "$kit/smoke-book.sh" "$kit/oracles" "$kit/records/pristine.txt" \
   >"$here/records/pristine.framed.txt"
"$here/frame-records.sh" "$kit/smoke-book.sh" "$kit/oracles" "$kit/records/converged.txt" \
   >"$here/records/converged.framed.txt"

render 'PRISTINE world (hermetic; records hand-authored, nothing executed)' \
   "$kit/smoke-book.sh" "$kit/records/pristine.framed.txt" plan-pristine.txt
render 'CONVERGED world (hermetic; records hand-authored, nothing executed)' \
   "$kit/smoke-book.sh" "$kit/records/converged.framed.txt" plan-converged.txt

# The ceiling's site ids renumber (L1 removal shifts everything down), so its records are framed
# against its own book.
DORC=$dorc "$here/frame-records.sh" "$work/ceiling-book.sh" "$kit/oracles" \
   "$kit/records/ceiling.txt" >"$work/ceiling.framed.txt"
render 'CONVERGED world, CEILING VARIANT (the book minus its bare `apt-get update`)' \
   "$work/ceiling-book.sh" "$work/ceiling.framed.txt" plan-ceiling-converged.txt

printf 'renders refreshed:\n' >&2
grep -h 'plan-summary' "$here"/renders/*.txt >&2
